### ISSUE TITLE
When the Android app starts the update, the react-native-code-push throws an runtime exception: Caused by: com.microsoft.codepush.react.CodePushUnknownException: Error in getting binary resources modified time

### ISSUE THREAD

**Issue by heart-bool** [Microsoft/react-native-code-push#1046]
react-native-code-push version: ^5.1.3-beta
 react-native version: 0.49.3
 Android/Windows version: 7.1.0/Windows 10

app normal package and run, code push pop-up whether the update will choose to install the exception will be thrown

`java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                       at java.lang.Thread.run(Thread.java:761)
                                                    Caused by: com.microsoft.codepush.react.CodePushUnknownException: Error in getting binary resources modified time
                                                       at com.microsoft.codepush.react.CodePush.getBinaryResourcesModifiedTime(CodePush.java:160)
                                                       at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:209)
                                                       at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:204)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                       at java.lang.Thread.run(Thread.java:761) 
                                                    Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
                                                       at android.content.res.Resources.getText(Resources.java:335)
                                                       at android.content.res.Resources.getString(Resources.java:381)
                                                       at com.microsoft.codepush.react.CodePush.getBinaryResourcesModifiedTime(CodePush.java:156)
                                                       at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:209) 
                                                       at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:204) 
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:305) 
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                       at java.lang.Thread.run(Thread.java:761) `

**Comment by heart-bool** [comment]
Sorry, the configuration file does not have codePush.gradle referenced in build.gradle.
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"

**Comment by muratoner** [comment]
> Sorry, the configuration file does not have codePush.gradle referenced in build.gradle.
> apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"

This row solved my problem thanks.
