### ISSUE TITLE
code-push release-react for my project

### ISSUE THREAD

**Issue by wuyingtong** [Microsoft/react-native-code-push#1143]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.code-push release-react CodePushDemo-android android -d Staging
2. 
3.

### Environment

* react-native-code-push version:^5.1.3-beta
* react-native version:0.50.3
* iOS/Android/Windows version:WIN10
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

[Error]  <!DOCTYPE html><html><head><title></title><link rel="stylesheet" href="/js/bootstrap-3.3.7/css/bootstrap.min.css"></head><body><h1>Not Found</h1><h2>404</h2><pre>Error
    at /stage/node771/lib/node_modules/code-push-server/app.js:87:15
    at Layer.handle [as handle_request] (/stage/node771/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/stage/node771/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
    at /stage/node771/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/stage/node771/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:335:12)
    at next (/stage/node771/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:275:10)
    at /stage/node771/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:635:15
    at next (/stage/node771/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/stage/node771/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:174:3)
    at router (/stage/node771/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/stage/node771/lib/node_modules/code-push-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/stage/node771/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:317:13)
    at /stage/node771/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/stage/node771/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:335:12)
    at next (/stage/node771/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:275:10)
    at /stage/node771/lib/node_modules/code-push-server/node_modules/express/lib/router/index.js:635:15</pre></body><script src="/js/jquery-3.1.1.min.js"></script><script src="/js/bootstrap-3.3.7/js/bootstrap.min.js"></script></
html>

**Comment by max-mironov** [comment]
Hello there @wuyingtong, thanks for sharing.
Could you please clarify - is it the first time you see the issue or it was working great previously for you?

As a solution you could try two things firstly:
1) Try to use https://github.com/Microsoft/appcenter-cli and release update with it
2) Try to completely reinstall old CLI as it seems to be broken. 

Please let me know if it helps.

**Comment by wuyingtong** [comment]
Thank you for your answer, but can not help me solve the problem

**Comment by max-mironov** [comment]
@wuyingtong what does `appcenter codepush release-react` command output says?

**Comment by wuyingtong** [comment]
Thank you very much. I used code-push to build my own service. I have a colleague computer to use. I should configure the environment. I'll check it again.
