### ISSUE TITLE
Error when running command code-push register

### ISSUE THREAD

**Issue by aurorasimran** [Microsoft/react-native-code-push#1181]
When i try running code-push register it gives the following error :-
module.js:472
    throw err;
    ^

Error: Cannot find module 'superagent'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/code-push-cli/node_modules/code-push/script/management-sdk.js:6:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

It gives the above error.
React Native version:- 0.51.0
React:- 16.0.0

**Comment by iTOYS** [comment]
Hi @aurorasimran 
Please try to clear npm cache `npm cache celean ~/.npm` and reinstall `code-push-cli`:
```
npm install -g code-push-cli
```

Please check that you don't have any installation errors

**Comment by aurorasimran** [comment]
when i run npm cache clean ~/.npm
i get this error
npm cache clean ~/.npm
npm ERR! npm cache clear does not accept arguments

npm ERR! A complete log of this run can be found in:

**Comment by iTOYS** [comment]
Hm, then please try `npm cache verify` and after `npm install -g code-push-cli`

Thanks!

**Comment by aurorasimran** [comment]
Still the same 
1. I ran 
npm cache verify ~/.npm ->
Cache verified and compressed (~/.npm/_cacache):
Content verified: 0 (0 bytes)
Index entries: 0
Finished in 0.042s
2. npm install -g code-push-cli
/usr/local/bin/code-push -> /usr/local/lib/node_modules/code-push-cli/script/cli.js
+ code-push-cli@2.1.6
updated 1 package in 40.038s
3.  Again same error :- 
code-push register
module.js:472
    throw err;
    ^

Error: Cannot find module 'superagent'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/code-push-cli/node_modules/code-push/script/management-sdk.js:6:18)
    at Module._compile (module.js:571:32)

**Comment by iTOYS** [comment]
Looks like some issue with your `npm`.

Could you please check if `/usr/local/lib/node_modules/code-push-cli/node_modules/superagent` exists.

If not, could you please try to install it manually:
```bash
$ cd /usr/local/lib/node_modules/code-push-cli/node_modules/
$ npm install superagent
```
That should fix your issue

**Comment by aurorasimran** [comment]
still not working for me

**Comment by aurorasimran** [comment]
After installing now, I am getting this error
code-push register
module.js:472
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/code-push-cli/node_modules/proxy-agent/index.js:11:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by iTOYS** [comment]
It's definitely `npm` problem((
Which version of npm do you use(`npm -v`)?

Also you can try reinstall package:
```
$ npm uninstall -g code-push-cli
$ npm install -g code-push-cli
```

**Comment by aurorasimran** [comment]
It's 5.6.0

**Comment by iTOYS** [comment]
@aurorasimran 
Please see https://stackoverflow.com/questions/18401606/npm-doesnt-install-module-dependencies

**Comment by iTOYS** [comment]
@aurorasimran 
Is it work for you?

**Comment by aurorasimran** [comment]
no still the same issue tried everything

**Comment by aurorasimran** [comment]
now i am getting this weird error
 Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/code-push-cli/node_modules/proxy-agent/index.js:11:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by aurorasimran** [comment]
finally worked after installing all the module that it was unable to find
Closing the issue
