### ISSUE TITLE
Android: java.lang.IllegalArgumentException: unexpected url when bundling SVG files

### ISSUE THREAD

**Issue by sujayjaju** [Microsoft/react-native-code-push#1217]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Include a .svg image in assets, use it using require(...path/to/image.svg)
2. Release-React
3. Run app after update

### Expected Behavior
The app should display the image

### Actual Behavior
Fails with java.lang.IllegalArgumentException: unexpected url: Error
```
at okhttp3.Request$Builder.url(Request.java:142)
at com.facebook.react.modules.network.NetworkingModule.sendRequest(NetworkingModule.java:171)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
 at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
at android.os.Looper.loop(Looper.java:214)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
at java.lang.Thread.run(Thread.java:818)
```

### Environment

* react-native-code-push version: 5.2.1
* react-native version: 0.50.4
* iOS/Android/Windows version: 5.1
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by iTOYS** [comment]
Hi @sujayjaju, thanks for reaching us!
As I remember React Native doesn't support `.svg` from the box:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> /Users/TOYS/projects/AwesomeProject/android/app/build/generated/res/react/release/drawable-mdpi/image.svg: Error: The file name must end with .xml or .png
```

Could you please describe your use case. Also would be better if you could create little example project which I can use to reproduce.

Thanks!

**Comment by sujayjaju** [comment]
@iTOYS Thanks for getting back
I have the below setting in ```android\gradle.properties``` to allow bundling .svg files
```
android.disableResourceValidation=true
```
And I am using react-native-svg-uri to render the SVG file.

I will setup a sample project.

**Comment by iTOYS** [comment]
@sujayjaju 
Please note 
https://www.npmjs.com/package/react-native-svg-uri#known-bugs
