### ISSUE TITLE
Fatal exception - Error reading binary modified date from package metadata

### ISSUE THREAD

**Issue by ajwhite** [Microsoft/react-native-code-push#123]
I've upgraded CodePush from `1.3.2-beta` to `1.5.2-beta` along with ReactNative from `0.15.0` to `0.17.0` and seem to hit a problem when starting up the app on Android:

In my `onCreate` I have the following calls on the builder:

```java
.setJSMainModuleName("index.android")
.setJSBundleFile(codePush.getBundleUrl("index.android.bundle"))
.addPackage(codePush.getReactPackage())
```

```
E/AndroidRuntime(10892): FATAL EXCEPTION: main
E/AndroidRuntime(10892): Process: com.robinpowered.rooms, PID: 10892
E/AndroidRuntime(10892): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.robinpowered.rooms/com.robinrooms.MainActivity}: com.microsoft.codepush.react.CodePushUnknownException: Error in reading binary modified date from package metadata
E/AndroidRuntime(10892): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/AndroidRuntime(10892): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/AndroidRuntime(10892): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime(10892): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/AndroidRuntime(10892): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10892): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(10892): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(10892): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10892): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(10892): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(10892): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime(10892): Caused by: com.microsoft.codepush.react.CodePushUnknownException: Error in reading binary modified date from package metadata
E/AndroidRuntime(10892): 	at com.microsoft.codepush.react.CodePush.getBundleUrl(CodePush.java:146)
E/AndroidRuntime(10892): 	at com.robinrooms.MainActivity.onCreate(MainActivity.java:62)
E/AndroidRuntime(10892): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime(10892): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime(10892): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/AndroidRuntime(10892): 	... 10 more
E/AndroidRuntime(10892): Caused by: java.lang.NumberFormatException: Invalid long: "null"
E/AndroidRuntime(10892): 	at java.lang.Long.invalidLong(Long.java:124)
E/AndroidRuntime(10892): 	at java.lang.Long.parseLong(Long.java:345)
E/AndroidRuntime(10892): 	at java.lang.Long.parseLong(Long.java:321)
E/AndroidRuntime(10892): 	at com.microsoft.codepush.react.CodePush.getBundleUrl(CodePush.java:134)
E/AndroidRuntime(10892): 	... 14 more
W/ActivityManager(  542):   Force finishing activity 1 com.robinpowered.rooms/com.robinrooms.MainActivity
```

**Comment by lostintangent** [comment]
You just need to uninstall your app from the emulator/device you're testing on. This was a breaking change in 1.5.0, and won't occur once you have a "fresh" app install that uses this plugin version.

**Comment by geof90** [comment]
So our plan to handle this is to ignore + clear away all older packages when a new binary is applied right?

**Comment by ajwhite** [comment]
Feel free to close if this isn't tracking anything new -- I'm all set after the full reinstallation of the app

**Comment by lostintangent** [comment]
@geof90 Yep, that is my preferred long term solution. I'd like to clear out packages, pending updates and failed updates as soon as we discover a new binary version. We can use the existing bug to track this change, so I'll close this bug.
