### ISSUE TITLE
Android app crashing after installing CodePush update, working fine on iOS

### ISSUE THREAD

**Issue by mdsaddam** [Microsoft/react-native-code-push#1241]
Android app crashing after installing CodePush update, working fine on iOS. Following is the CodePush configuration in react native app

```
let codePushOptions = {
      checkFrequency: CodePush.CheckFrequency.ON_APP_START,
      installMode: CodePush.InstallMode.ON_NEXT_RESTART,
      updateDialog: true
};
CodePush.sync(codePushOptions);
```

Getting following error log in android studio 

```
03-29 16:51:10.863 28164-28235/com.demo.app I/ReactNativeJS: [CodePush] Awaiting user action.
03-29 16:51:12.726 28164-28235/com.demo.app I/ReactNativeJS: [CodePush] Downloading package.
03-29 16:51:15.483 28164-28185/com.demo.app D/ReactNative: [CodePush] Applying full update.
03-29 16:51:15.491 28164-28235/com.demo.app I/ReactNativeJS: [CodePush] Installing update.
03-29 16:51:15.514 28164-28235/com.demo.app I/ReactNativeJS: [CodePush] Update is installed and will be run on the next app restart.


------------ Following is the log after app restart -------------------------

03-29 16:38:07.775 23676-23720/com.demo.app D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
03-29 16:38:08.257 23676-23719/com.demo.app E/ReactNativeJS: undefined is not an object (evaluating 'o(a[1]).NativeModules.SourceCode.scriptURL.split("://")[1].split')
03-29 16:38:08.263 23676-23719/com.demo.app E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
03-29 16:38:08.269 23676-23720/com.demo.app E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                                     Process: com.demo.app, PID: 23676
                                                                     com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'o(a[1]).NativeModules.SourceCode.scriptURL.split("://")[1].split'), stack:
                                                                     <unknown>@304:141
                                                                     d@2:768
                                                                     n@2:409
                                                                     t@2:262
                                                                     <unknown>@303:75
                                                                     d@2:768
                                                                     n@2:409
                                                                     t@2:262
                                                                     <unknown>@12:42
                                                                     d@2:768
                                                                     n@2:339
                                                                     t@2:262
                                                                     global code@1396:8
                                                                     
                                                                         at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
                                                                         at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
                                                                         at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                                         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                                         at java.lang.Thread.run(Thread.java:761)
03-29 16:38:08.279 23676-23676/com.demo.app W/com.facebook.appevents.internal.ActivityLifecycleTracker: Unexpected activity pause without a matching activity resume. Logging data may be incorrect. Make sure you call activateApp from your Application's onCreate method
03-29 16:38:08.282 23676-23695/com.demo.app V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 757
03-29 16:38:08.283 23676-23695/com.demo.app V/FA: Activity paused, time: 83722650
03-29 16:38:08.661 23676-23676/com.demo.app D/ReactNative: ReactInstanceManager.detachViewFromInstance()
03-29 16:38:08.664 23676-23719/com.demo.app E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)
03-29 16:38:13.320 23676-23695/com.demo.app V/FA: Inactivity, disconnecting from the service

```

### Environment

* react-native-code-push version:  "react-native-code-push": "^5.2.2"
* react-native version: "react-native": "0.53.2"
* Android version: 7.1.2
* Causing issue on release build
* Causing issue on real device

**Comment by iTOYS** [comment]
Hi @mdsaddam 
Did you wrap your `App` class with code push?
```javascript
class App extends React.Component {
...
}
let codePushOptions = {
      checkFrequency: CodePush.CheckFrequency.ON_APP_START,
      installMode: CodePush.InstallMode.ON_NEXT_RESTART,
      updateDialog: true
};

export default App = CodePush.sync(codePushOptions)(App);
```

**Comment by mdsaddam** [comment]
@iTOYS 

Yeah I did wrap App class with code push, same code working in iOS

**Comment by iTOYS** [comment]
@mdsaddam 
Unfortunately I can't reproduce that.

Seems like you or one of your dependencies use this: `o(a[1]).NativeModules.SourceCode.scriptURL.split("://")[1].split`.
Could you let me know, how it's used in code?

Thanks!

**Comment by mdsaddam** [comment]
Thanks @iTOYS 

Issue was due to Reactotron (https://github.com/infinitered/reactotron/blob/master/docs/quick-start-react-native.md) integration. It was a dev dependency, for now we've removed in our release, it's working fine now.
