### ISSUE TITLE
App crashes after Code Push installs updated bundle

### ISSUE THREAD

**Issue by danieloj** [Microsoft/react-native-code-push#1273]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Dependencies from `package.json`: 

```
"dependencies": {
    "babel-plugin-react-intl": "2.3.1",
    "babel-plugin-transform-class-properties": "^6.16.0",
    "babel-plugin-transform-inline-environment-variables": "^6.8.0",
    "babel-plugin-transform-remove-console": "^6.9.0",
    "babel-polyfill": "^6.9.1",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react-native": "^3.0.2",
    "babel-preset-stage-0": "^6.5.0",
    "compare-versions": "^3.1.0",
    "fbemitter": "^2.1.1",
    "globalize": "^1.3.0",
    "hoist-non-react-statics": "^2.2.1",
    "lodash": "^4.17.10",
    "moment": "^2.18.1",
    "moment-timezone": "0.5.14",
    "most": "1.0.1",
    "prop-types": "^15.6.0",
    "query-string": "^4.3.1",
    "react": "^16.3.1",
    "react-addons-create-fragment": "^15.6.0",
    "react-intl-native": "^2.1.0",
    "react-native": "0.55.3",
    "react-native-code-push": "^5.3.2",
    "react-native-cookies": "^3.2.0",
    "react-native-elements": "0.19.0",
    "react-native-exception-handler": "2.7.1",
    "react-native-fingerprint-scanner": "2.3.2",
    "react-native-firebase": "^3.2.0",
    "react-native-global-props": "^1.1.3",
    "react-native-globalize": "^1.0.1",
    "react-native-htmlview": "0.12.1",
    "react-native-iphone-x-helper": "^1.0.2",
    "react-native-keyboard-aware-scroll-view": "0.4.3",
    "react-native-keychain": "^3.0.0-rc.3",
    "react-native-masked-text": "1.6.5",
    "react-native-restart": "0.0.6",
    "react-native-vector-icons": "4.5.0",
    "react-native-version-number": "^0.3.1",
    "react-navigation": "^1.5.9",
    "react-navigation-redux-helpers": "^1.0.0",
    "react-prop-types": "0.4.0",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-form": "^7.3.0",
    "redux-persist": "5.9.1",
    "redux-thunk": "^2.2.0",
    "reselect": "^3.0.1",
    "rn-splash-screen": "5.2.0",
    "sockjs-client": "git://github.com/sockjs/sockjs-client#436e99754",
    "symbol-observable": "^1.0.2",
    "url-parse": "^1.1.9",
    "uuid": "^3.1.0",
    "validator": "^7.0.0",
    "zxcvbn": "^4.4.2"
  },
```

2. `export default codePush({ installModel: codePush.InstallMode.ON_NEXT_RESTART })(RootApp);`
3. Build the app in release mode
4. Create a code push release changing one of the colors in colors.js
5. Wait for the code push update to download
6. Restart the app
7. Crash!
8. Code push rolls back

### Expected Behavior

...
6. Restart the app
7. Updated colors are visible

### Actual Behavior
App crashes and rolls back.

```
05-08 11:47:25.093 22790 22827 D RNFirebaseAnalytics: New instance
05-08 11:47:25.093 22790 22827 D RNFirebaseCrashlytics: New instance
05-08 11:47:25.093 22790 22827 D RNFirebasePerformance: New instance
05-08 11:47:25.094 22790 22827 D ReactNative: Initializing React Xplat Bridge.
05-08 11:47:25.098 22790 22827 D ReactNative: Initializing React Xplat Bridge before initializeBridge
05-08 11:47:25.103  1186  1235 I PowerManagerService: setInteractiveWhileDozingInternal - false
05-08 11:47:25.107 22790 22827 D ReactNative: Initializing React Xplat Bridge after initializeBridge
05-08 11:47:25.107 22790 22827 D ReactNative: CatalystInstanceImpl.runJSBundle()
05-08 11:47:25.108 22790 22837 D ReactNative: ReactInstanceManager.setupReactContext()
05-08 11:47:25.108 22790 22837 D ReactNative: CatalystInstanceImpl.initialize()
05-08 11:47:25.109 22790 22837 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
05-08 11:47:25.231  1186  1232 I WindowManager: Destroying surface Surface(name=Starting com.app.staging) called by com.android.server.wm.WindowStateAnimator.destroySurface:2069 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:897 com.android.server.wm.WindowState.destroyOrSaveSurface:2121 com.android.server.wm.AppWindowToken.destroySurfaces:368 com.android.server.wm.WindowStateAnimator.finishExit:575 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:501 com.android.server.wm.WindowAnimator.updateWindowsLocked:303 com.android.server.wm.WindowAnimator.animateLocked:704
05-08 11:47:25.324 22790 22807 E Fabric  : Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/com.app.staging/settings
05-08 11:47:25.326 22790 22808 E Answers : Failed to retrieve settings
05-08 11:47:25.327 22790 22806 W CrashlyticsCore: Received null settings, skipping report submission!
05-08 11:47:25.425   699   699 I MSM-irqbalance: Decided to move IRQ216 from CPU1 to CPU0
05-08 11:47:26.350 22790 22836 E ReactNativeJS: undefined is not an object (evaluating 't.Manager')
05-08 11:47:26.357 22790 22836 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
05-08 11:47:26.446  1186  1235 I PowerManagerService: setInteractiveWhileDozingInternal - false
05-08 11:47:26.453  6183  6489 V ConnectivityManager: isActiveNetworkMetered() returns:true
05-08 11:47:26.461 22790 22821 W CrashlyticsCore: Cannot send reports. Settings are unavailable.
05-08 11:47:26.462 22790 22837 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
--
05-08 11:47:25.326 22790 22808 E Answers : Failed to retrieve settings
05-08 11:47:25.327 22790 22806 W CrashlyticsCore: Received null settings, skipping report submission!
05-08 11:47:25.425   699   699 I MSM-irqbalance: Decided to move IRQ216 from CPU1 to CPU0
05-08 11:47:26.350 22790 22836 E ReactNativeJS: undefined is not an object (evaluating 't.Manager')
05-08 11:47:26.357 22790 22836 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
05-08 11:47:26.446  1186  1235 I PowerManagerService: setInteractiveWhileDozingInternal - false
05-08 11:47:26.453  6183  6489 V ConnectivityManager: isActiveNetworkMetered() returns:true
05-08 11:47:26.461 22790 22821 W CrashlyticsCore: Cannot send reports. Settings are unavailable.
05-08 11:47:26.462 22790 22837 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
05-08 11:47:26.462 22790 22837 E AndroidRuntime: Process: com.app.staging, PID: 22790
05-08 11:47:26.462 22790 22837 E AndroidRuntime: com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 't.Manager'), stack:
05-08 11:47:26.462 22790 22837 E AndroidRuntime: <unknown>@96:381
05-08 11:47:26.462 22790 22837 E AndroidRuntime: <unknown>@96:356
05-08 11:47:26.462 22790 22837 E AndroidRuntime: d@2:768
05-08 11:47:26.462 22790 22837 E AndroidRuntime: n@2:409
05-08 11:47:26.462 22790 22837 E AndroidRuntime: t@2:262
05-08 11:47:26.462 22790 22837 E AndroidRuntime: <unknown>@46:73
05-08 11:47:26.462 22790 22837 E AndroidRuntime: d@2:768
05-08 11:47:26.462 22790 22837 E AndroidRuntime: n@2:409
05-08 11:47:26.462 22790 22837 E AndroidRuntime: t@2:262
05-08 11:47:26.462 22790 22837 E AndroidRuntime: <unknown>@45:47
05-08 11:47:26.462 22790 22837 E AndroidRuntime: d@2:768
05-08 11:47:26.462 22790 22837 E AndroidRuntime: n@2:409
05-08 11:47:26.462 22790 22837 E AndroidRuntime: t@2:262
05-08 11:47:26.462 22790 22837 E AndroidRuntime: <unknown>@44:45
05-08 11:47:26.462 22790 22837 E AndroidRuntime: d@2:768
05-08 11:47:26.462 22790 22837 E AndroidRuntime: n@2:409
05-08 11:47:26.462 22790 22837 E AndroidRuntime: t@2:262
05-08 11:47:26.462 22790 22837 E AndroidRuntime: <unknown>@166:45
05-08 11:47:26.462 22790 22837 E AndroidRuntime: d@2:768
05-08 11:47:26.462 22790 22837 E AndroidRuntime: n@2:409
05-08 11:47:26.462 22790 22837 E AndroidRuntime: t@2:262
05-08 11:47:26.462 22790 22837 E AndroidRuntime: Text@13:1240
05-08 11:47:26.462 22790 22837 E AndroidRuntime: <unknown>@698:1115
05-08 11:47:26.462 22790 22837 E AndroidRuntime: d@2:768
05-08 11:47:26.462 22790 22837 E AndroidRuntime: n@2:409
05-08 11:47:26.462 22790 22837 E AndroidRuntime: t@2:262
05-08 11:47:26.462 22790 22837 E AndroidRuntime: <unknown>@681:398
05-08 11:47:26.462 22790 22837 E AndroidRuntime: d@2:768
05-08 11:47:26.462 22790 22837 E AndroidRuntime: n@2:409
05-08 11:47:26.462 22790 22837 E AndroidRuntime: t@2:262
05-08 11:47:26.462 22790 22837 E AndroidRuntime: <unknown>@634:288
05-08 11:47:26.462 22790 22837 E AndroidRuntime: d@2:768
05-08 11:47:26.462 22790 22837 E AndroidRuntime: n@2:409
05-08 11:47:26.462 22790 22837 E AndroidRuntime: t@2:262
05-08 11:47:26.462 22790 22837 E AndroidRuntime: <unknown>@12:54
05-08 11:47:26.462 22790 22837 E AndroidRuntime: d@2:768
05-08 11:47:26.462 22790 22837 E AndroidRuntime: n@2:339
05-08 11:47:26.462 22790 22837 E AndroidRuntime: t@2:262
05-08 11:47:26.462 22790 22837 E AndroidRuntime: global code@2079:8
05-08 11:47:26.462 22790 22837 E AndroidRuntime:
05-08 11:47:26.462 22790 22837 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
05-08 11:47:26.462 22790 22837 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
05-08 11:47:26.462 22790 22837 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-08 11:47:26.462 22790 22837 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
05-08 11:47:26.462 22790 22837 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
05-08 11:47:26.462 22790 22837 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-08 11:47:26.462 22790 22837 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
05-08 11:47:26.462 22790 22837 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
05-08 11:47:26.462 22790 22837 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
05-08 11:47:26.462 22790 22837 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
05-08 11:47:26.462 22790 22837 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
05-08 11:47:26.462 22790 22837 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
--
```

### Environment

* react-native-code-push version: 5.3.2
* react-native version: 0.55.3
* iOS/Android/Windows version: Android 7.0
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Physical

Any help would be greatly appreciated! Let me know if there is any clarification needed

**Comment by NickToropov** [comment]
Hi @danieloj, 
I’ll close this issue for now. Please feel free to reopen it if you will have any questions.
