### ISSUE TITLE
TransformException: Error while generating the main dex list

### ISSUE THREAD

**Issue by xwartz** [Microsoft/react-native-code-push#1285]
Hey 

I got a "TransformException: Error while generating the main dex list " error after import the "react-native-code-push"

I have tried 5.3.3, 5.3.2 version。

the total error
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDevRelease'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithMultidexlistForDevRelease'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: Error while generating the main dex list.
        at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more
Caused by: com.android.build.api.transform.TransformException: Error while generating the main dex list.
        at com.android.build.gradle.internal.transforms.D8MainDexListTransform.transform(D8MainDexListTransform.kt:127)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        ... 41 more
Caused by: com.android.builder.multidex.D8MainDexList$MainDexListException: com.android.tools.r8.errors.CompilationError: Program type already present: net.jcip.annotations.GuardedBy
        at com.android.builder.multidex.D8MainDexList.generate(D8MainDexList.java:87)
        at com.android.build.gradle.internal.transforms.D8MainDexListTransform.transform(D8MainDexListTransform.kt:114)
        ... 44 more
Caused by: com.android.tools.r8.errors.CompilationError: Program type already present: net.jcip.annotations.GuardedBy
        at com.android.tools.r8.utils.ProgramClassCollection.resolveClassConflictImpl(ProgramClassCollection.java:64)
        at com.android.tools.r8.dex.ApplicationReader$$Lambda$391/705420520.resolveClassConflict(Unknown Source)
        at com.android.tools.r8.utils.ProgramClassCollection.lambda$create$0(ProgramClassCollection.java:25)
        at com.android.tools.r8.utils.ProgramClassCollection$$Lambda$411/2127082483.apply(Unknown Source)
        at com.android.tools.r8.utils.ProgramClassCollection.create(ProgramClassCollection.java:24)
        at com.android.tools.r8.graph.LazyLoadedDexApplication$Builder.build(LazyLoadedDexApplication.java:121)
        at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:122)
        at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:86)
        at com.android.tools.r8.GenerateMainDexList.run(GenerateMainDexList.java:36)
        at com.android.tools.r8.GenerateMainDexList.run(GenerateMainDexList.java:95)
        at com.android.builder.multidex.D8MainDexList.generate(D8MainDexList.java:83)
        ... 45 more


* Get more help at https://help.gradle.org
```

my package.json
```json
{
  "name": "token",
  "version": "0.0.1",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "configureJPush": "node node_modules/jpush-react-native/JPushConfiguration.js",
    "postinstall": "./node_modules/.bin/rn-nodeify --install buffer,events,process,stream,util,inherits,fs,path,url,crypto,vm,assert --hack",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "e2e": "detox test --configuration=ios.sim.debug",
    "e2er": "yarn e2e --reuse",
    "ios": "react-native run-ios",
    "android": "react-native run-android --variant=devDebug",
    "link": "react-native link react-native-view-shot"
  },
  "dependencies": {
    "0x.js": "^0.35.0",
    "@types/bignumber.js": "^4.0.3",
    "assert": "^1.4.1",
    "axios": "^0.16.2",
    "bignumber.js": "git+https://github.com/consenlabs/bignumber.js.git",
    "bip39": "^2.5.0",
    "bitcoinjs-lib": "^3.3.0",
    "browserify-zlib": "^0.1.4",
    "buffer": "^4.9.1",
    "console-browserify": "^1.1.0",
    "constants-browserify": "0.0.1",
    "dns.js": "^1.0.1",
    "domain-browser": "^1.1.7",
    "es6-promisify": "git+https://github.com/consenlabs/es6-promisify.git",
    "ethereumjs-abi": "0.6.5",
    "ethereumjs-util": "^5.1.2",
    "events": "^1.1.1",
    "gulp": "^3.9.1",
    "hdkey": "^0.8.0",
    "https-browserify": "0.0.1",
    "immutable": "^3.8.1",
    "inherits": "^2.0.3",
    "jcore-react-native": "^1.2.5",
    "jpush-react-native": "^2.2.0",
    "lodash": "^4.17.4",
    "mixpanel": "git+https://github.com/consenlabs/react-native-mixpanel.git",
    "moment": "^2.18.1",
    "nock": "^9.1.6",
    "numeral": "^2.0.6",
    "os-browserify": "^0.1.2",
    "path-browserify": "0.0.0",
    "process": "^0.11.10",
    "query-string": "^5.0.0",
    "querystring-es3": "^0.2.1",
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-actionsheet": "^2.3.0",
    "react-native-af-video-player": "^0.1.7",
    "react-native-animatable": "^1.2.3",
    "react-native-calendar-events": "^1.4.3",
    "react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera",
    "react-native-code-push": "^5.3.3",
    "react-native-crypto": "^2.0.2",
    "react-native-device-info": "^0.11.0",
    "react-native-easy-grid": "^0.1.15",
    "react-native-exception-handler": "^2.7.1",
    "react-native-fingerprint-scanner": "^2.2.0",
    "react-native-fs": "^2.9.12",
    "react-native-hyperlink": "^0.0.11",
    "react-native-i18n": "^2.0.6",
    "react-native-image-picker": "git+https://github.com/consenlabs/react-native-image-picker.git",
    "react-native-image-progress": "^1.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.4.4",
    "react-native-level-fs": "^3.0.0",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-modal-datetime-picker": "^4.13.0",
    "react-native-modalbox": "^1.4.2",
    "react-native-navigation": "^1.1.440 ",
    "react-native-permissions": "^1.0.6",
    "react-native-prompt-android": "^0.3.1",
    "react-native-qrcode-svg": "^5.0.2",
    "react-native-randombytes": "^3.0.0",
    "react-native-restart": "^0.0.3",
    "react-native-sentry": "^0.35.3",
    "react-native-share": "^1.0.27",
    "react-native-smart-gesture-password": "git+https://github.com/consenlabs/react-native-smart-gesture-password.git",
    "react-native-snap-carousel": "^3.5.0",
    "react-native-sortable-listview": "^0.2.6",
    "react-native-splash-screen": "^3.0.1",
    "react-native-svg": "^5.4.1",
    "react-native-swipeout": "^2.2.2",
    "react-native-tab-view": "^0.0.69",
    "react-native-view-shot": "^2.3.0",
    "react-redux": "^5.0.6",
    "readable-stream": "1.0.33",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-orm": "^0.9.4",
    "redux-persist": "^4.10.1",
    "redux-thunk": "^2.2.0",
    "rmc-date-picker": "^6.0.5",
    "rn-nodeify": "^10.0.0",
    "rn-topview": "^0.1.6",
    "stream-browserify": "^1.0.0",
    "string_decoder": "^0.10.31",
    "timers-browserify": "^1.4.2",
    "tslint": "^5.7.0",
    "tty-browserify": "0.0.0",
    "url": "^0.10.3",
    "util": "^0.10.3",
    "validate-model": "^0.0.2",
    "vm-browserify": "0.0.4",
    "web3": "git+https://github.com/consenlabs/web3.js.git",
    "zxcvbn": "^4.4.2"
  },
  "devDependencies": {
    "@types/jest": "^22.1.0",
    "@types/react": "^16.0.0",
    "@types/react-native": "^0.51.0",
    "@types/react-redux": "^5.0.6",
    "@types/redux": "^3.6.0",
    "axios-mock-adapter": "^1.10.0",
    "babel-jest": "22.1.0",
    "babel-plugin-transform-remove-console": "^6.8.5",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "detox": "^6.0.2",
    "jest": "22.1.4",
    "koa": "^2.4.1",
    "koa-body": "^2.5.0",
    "koa-router": "^7.4.0",
    "react-addons-test-utils": "^15.6.2",
    "react-dom": "^16.1.1",
    "react-native-mock": "git+https://github.com/shqld/react-native-mock.git",
    "react-native-typescript-transformer": "^1.1.4",
    "ts-jest": "^22.0.1",
    "typescript": "next",
    "url-search-params": "^0.10.0"
  },
  "jest": {
    "globals": {
      "ts-jest": {
        "useBabelrc": true
      }
    },
    "preset": "react-native",
    "modulePaths": [
      "<rootDir>"
    ],
    "setupFiles": [
      "./jest_setup"
    ],
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "moduleNameMapper": {
      "eui": "<rootDir>/src/lib/eui",
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/src/__mocks__/file-mock.js"
    },
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json"
    ],
    "transform": {
      "^.+\\.(js)$": "<rootDir>/node_modules/babel-jest",
      "\\.(ts|tsx)$": "<rootDir>/preprocessor.js"
    },
    "testRegex": "/__tests__/.*\\.(test|spec)\\.(ts|tsx|js)$",
    "testPathIgnorePatterns": [
      "\\.snap$",
      "<rootDir>/node_modules/",
      "<rootDir>/build/",
      "<rootDir>/e2e/"
    ],
    "transformIgnorePatterns": [
      "<rootDir>/node_modules/(?!(react-native|web3|jpush-react-native|react-native-device-info))"
    ],
    "cacheDirectory": ".jest/cache"
  },
  "detox": {
    "test-runner": "jest",
    "runner-config": "e2e/config.json",
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/token.app",
        "build": "xcodebuild -workspace ios/token.xcworkspace -scheme token -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 8"
      },
      "ios.sim.release": {
        "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/token.app",
        "build": "xcodebuild -workspace ios/token.xcworkspace  -scheme token -configuration Release -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 6s"
      }
    }
  },
  "react-native": {
    "crypto": "react-native-crypto",
    "path": "path-browserify",
    "fs": "react-native-level-fs",
    "_stream_transform": "readable-stream/transform",
    "_stream_readable": "readable-stream/readable",
    "_stream_writable": "readable-stream/writable",
    "_stream_duplex": "readable-stream/duplex",
    "_stream_passthrough": "readable-stream/passthrough",
    "stream": "stream-browserify",
    "vm": "vm-browserify"
  },
  "browser": {
    "crypto": "react-native-crypto",
    "path": "path-browserify",
    "fs": "react-native-level-fs",
    "_stream_transform": "readable-stream/transform",
    "_stream_readable": "readable-stream/readable",
    "_stream_writable": "readable-stream/writable",
    "_stream_duplex": "readable-stream/duplex",
    "_stream_passthrough": "readable-stream/passthrough",
    "stream": "stream-browserify",
    "vm": "vm-browserify"
  }
}

```

build.gradle
```groovy
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
repositories {
    maven { url 'https://maven.fabric.io/public' }
}
/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"]
 * ]
 */

// Note: project.ext.react should above the line that contains apply from: "../../node_modules/react-native/react.gradle"
project.ext.react = [
  entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-sentry/sentry.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"

android {

    defaultConfig {
        applicationId rootProject.ext.applicationId

        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        targetSdkVersion rootProject.ext.targetSdkVersion

        packagingOptions {
            exclude 'META-INF/LICENSE'
        }

        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }

        manifestPlaceholders = [
                JPUSH_APPKEY: rootProject.ext.JPUSH_APPKEY, //在此替换你的APPKey
                APP_CHANNEL : rootProject.ext.APP_CHANNEL    //应用渠道号
        ]

        ndk {
            abiFilters 'armeabi', 'armeabi-v7a', 'x86'
        }

        signingConfigs {
            release {
              storeFile file(MYAPP_RELEASE_STORE_FILE)
              storePassword MYAPP_RELEASE_STORE_PASSWORD
              keyAlias MYAPP_RELEASE_KEY_ALIAS
              keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }

        /**
         * enable multi-dex
         */
        multiDexEnabled true
    }

    dexOptions {
        maxProcessCount 8
        javaMaxHeapSize "4g"
    }


    buildTypes {
        release {
            minifyEnabled rootProject.ext.minifyEnabled
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField "String", "CODEPUSH_KEY", rootProject.ext.CODEPUSH_KEY
        }

        releaseStaging {
            minifyEnabled rootProject.ext.minifyEnabled
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField "String", "CODEPUSH_KEY", rootProject.ext.CODEPUSH_STAGING_KEY
            matchingFallbacks = ['debug', 'release']
        }
    }

    productFlavors {
        dev {
            minSdkVersion rootProject.ext.devMinSdkVersion
        }

        prod {
            minSdkVersion rootProject.ext.minSdkVersion
        }
    }
    buildToolsVersion '26.0.2'

    testOptions {
        unitTests.returnDefaultValues = true
    }

    android.applicationVariants.all { variant ->
      variant.outputs.all {
        outputFileName = "imToken-${variant.flavorName}-${variant.buildType.name}.apk"
      }
    }
}

dependencies {
    compile project(':react-native-code-push')
    compile project(':react-native-view-shot')
    compile project(':react-native-fs')
    compile project(':react-native-sentry')
    compile project(':react-native-exception-handler')
    compile project(':react-native-orientation')
    compile project(':react-native-vector-icons')
    compile project(':react-native-keep-awake')
    compile project(':react-native-video')
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile project(':react-native-fingerprint-scanner')
    compile project(':react-native-i18n')
    compile project(':react-native-restart')
    compile project(':react-native-calendar-events')
    compile project(':jpush-react-native')
    compile project(':jcore-react-native')
    compile project(':react-native-svg')
    compile project(':react-native-randombytes')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-device-info')
    compile (project(':react-native-camera')) {
        exclude group: "com.google.android.gms"
    }
    compile ("com.google.android.gms:play-services-vision:10.2.0") {
        force = true;
    }
    compile project(':react-native-prompt-android')
    compile project(':react-native-share')
    compile project(':react-native-navigation')
    compile project(':react-native-image-picker')

    compile project(':token-core')


    compile 'com.facebook.react:react-native:+'
    compile 'com.google.code.findbugs:jsr305:3.0.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile('com.crashlytics.sdk.android:crashlytics:2.9.1@aar') {
      transitive = true;
    }
    compile 'com.scottyab:rootbeer-lib:0.0.6'

    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    androidTestCompile 'com.google.code.findbugs:jsr305:3.0.0'
    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:1.+'
    testCompile group: 'org.json', name: 'json', version: '20171018'


    compile 'org.jetbrains:annotations-java5:15.0'
    compile 'com.facebook.fresco:animated-gif:1.3.0'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

```

gradle version
```

------------------------------------------------------------
Gradle 4.4
------------------------------------------------------------

Build time:   2017-12-06 09:05:06 UTC
Revision:     cf7821a6f79f8e2a598df21780e3ff7ce8db2b82

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_51 (Oracle Corporation 25.51-b03)
OS:           Mac OS X 10.13.4 x86_64
```

**Comment by NickToropov** [comment]
Hi @xwartz, thanks for reporting issue.

Please, could you provide us with sample app or repro steps so that we could reproduce the issue?

**Comment by NickToropov** [comment]
Hi @xwartz, I'll close this issue for now but let me know if you will see anything related you can share with us going further
