### ISSUE TITLE
restartApp() crashing

### ISSUE THREAD

**Issue by PerspectivesLab** [Microsoft/react-native-code-push#1310]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.

"react-native-code-push": "5.3.4",
"react-native": "0.55.4",

```
         codePush.sync(
              { installMode: codePush.InstallMode.IMMEDIATE, updateDialog: true }, // ON_NEXT_RESTART
              this.codePushStatusDidChange.bind(this),
              this.codePushDownloadDidProgress.bind(this)
        );
```

 

### Expected Behavior
What you expected to happen?
the app restarts

### Actual Behavior
What actually happens?
```
06-06 19:26:22.969 14021-14021/org.chromium.android_webview.shell D/AndroidRuntime: Shutting down VM
06-06 19:26:22.970 14021-14021/org.chromium.android_webview.shell E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: org.chromium.android_webview.shell, PID: 14021
                                                                                    java.lang.AssertionError: recreateReactContextInBackground should only be called after the initial createReactContextInBackground call.
                                                                                        at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:72)
                                                                                        at com.facebook.react.ReactInstanceManager.recreateReactContextInBackground(ReactInstanceManager.java:342)
                                                                                        at com.microsoft.codepush.react.CodePushNativeModule$2.run(CodePushNativeModule.java:145)
                                                                                        at android.os.Handler.handleCallback(Handler.java:789)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                        at android.os.Looper.loop(Looper.java:164)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6938)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by NickToropov** [comment]
Hi @PerspectivesLab, thanks for posting this issue. I wasn't able to reproduce the issue. 
Please, could you provide us with demo app that reproduces your issue?

**Comment by NickToropov** [comment]
I'll close the issue as of no response but feel free to reopen if you have more details about it.
