### ISSUE TITLE
code push installation issue with ios - appDelegateContents.match(/(jsCodeLocation = .*)/)[1];

### ISSUE THREAD

**Issue by imankitaman** [Microsoft/react-native-code-push#1358]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.react-native link react-native-code-push

### Expected Behavior
What you expected to happen?
package to be installed

### Actual Behavior
What actually happens?
var oldJsCodeLocationAssignmentStatement = appDelegateContents.match(/(jsCodeLocation = .*)/)[1];
                                                                                             ^

TypeError: Cannot read property '1' of null
    at Object.<anonymous> (/Users/ab/Documents/ios/ios_app/node_modules/react-native-code-push/scripts/postlink/ios/postlink.js:39:94)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ab/Documents/ios/ios_app/node_modules/react-native-code-push/scripts/postlink/run.js:1:63)
    at Module._compile (module.js:641:30)
/Users/ab/Documents/ios/ios_app/node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-code-push/scripts/postlink/run" command
    at ChildProcess.prelink (/Users/ab/Documents/ios/ios_app/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

### Environment

* react-native-code-push version: 5.3.5
* react-native version:0.50.1
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by NickToropov** [comment]
Hi @imankitaman, the error says that the script can't find substring `jsCodeLocation =` in your AppDelegate.m file. Please check if the substring is there. Also it's possible that there are more than one AppDelegate.m file in your project directory so the script tries to patch incorrect file.  Please check these assumptions and let us know if it was helpful. 
Also please look at similar [issue](https://github.com/Microsoft/react-native-code-push/issues/477).

**Comment by imankitaman** [comment]
@NickToropov  After fixing that getting this error 
The name of the given podspec 'glog' doesn't match the expected one 'GLog'

I copied this line from setup-ios doc
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'

**Comment by imankitaman** [comment]
yeah, that issue was because of AppDelegate.m file only. Thanks, @NickToropov and @alexandergoncharov Its working fine now.

**Comment by alexandergoncharov** [comment]
Good news :) 
So, if issue was resolved I'm going to close this issue for now but please feel free to reopen it if you have any questions.

Thanks,
Alexander
