### ISSUE TITLE
[Android] "Error! Public key was provided..." at first, then update succeeds but no change from background. New bundle installed on restart despite setting CheckFrequency.ON_APP_RESUME

### ISSUE THREAD

**Issue by DavideValdo** [Microsoft/react-native-code-push#1405]
### Expected Behavior
App updates on resume 

### Actual Behavior
App updates on restart, seeing strange things in logcat

### Command used
```
appcenter codepush release-react -d Staging -k ./private.pem

### "[CodePush] Applying full update" two times upon resume from background
```
09-15 23:33:33.940 18405 18459 D ReactNative: [CodePush] Applying full update.
09-15 23:33:33.940 18405 18459 E ReactNative: [CodePush] Exception
09-15 23:33:33.940 18405 18459 E ReactNative: com.microsoft.codepush.react.CodePushInvalidUpdateException: Error! Public key was provided but there is no JWT signature within app bundle to verify. Possible reasons, why that might happen: 
09-15 23:33:33.940 18405 18459 E ReactNative: 1. You've been released CodePush bundle update using version of CodePush CLI that is not support code signing.
09-15 23:33:33.940 18405 18459 E ReactNative: 2. You've been released CodePush bundle update without providing --privateKeyPath option.
09-15 23:33:33.940 18405 18459 E ReactNative: 	at com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage(CodePushUpdateManager.java:264)
09-15 23:33:33.940 18405 18459 E ReactNative: 	at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:216)
09-15 23:33:33.940 18405 18459 E ReactNative: 	at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:210)
09-15 23:33:33.940 18405 18459 E ReactNative: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
09-15 23:33:33.940 18405 18459 E ReactNative: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-15 23:33:33.940 18405 18459 E ReactNative: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-15 23:33:33.940 18405 18459 E ReactNative: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-15 23:33:33.940 18405 18459 E ReactNative: 	at java.lang.Thread.run(Thread.java:760)

[...] 

09-15 23:58:49.558 18405 19903 D ReactNative: [CodePush] The update contents succeeded the code signing check.
09-15 23:58:49.566 18405 18491 I ReactNativeJS: [CodePush] Installing update.
09-15 23:58:49.587 18405 18491 I ReactNativeJS: [CodePush] Update is installed and will be run on the next app restart.

```

(Also logcat on app restarts shows many "Downloading package"?)

### EntryPoint.js

class EntryPoint extends React.Component {
    render () {
        return (
            <Provider store={store}>
                <MenuProvider>
                    <App />
                </MenuProvider>
            </Provider>
        )
    }
}

export default codePush({ checkFrequency: codePush.CheckFrequency.ON_APP_RESUME })(EntryPoint)

### MainApplication.java
```
public class MainApplication extends Application implements ReactApplication {
  private static CallbackManager mCallbackManager = CallbackManager.Factory.create();

  public class MyReactNativeHost extends ReactNativeHost implements ReactInstanceHolder {
      MyReactNativeHost (Application application) {
        super(application);
      }

      @Override
      protected String getJSBundleFile() {
          return CodePush.getJSBundleFile();
      }

      @Override
      public boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
      }

      @Override
      protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new PickerPackage(),
          new FBSDKPackage(mCallbackManager),
          new ActionSheetPackage(),
          new RNFirebasePackage(),
          new RNFirebaseDatabasePackage(),
          new RNFirebaseAuthPackage(),
          new RNFirebaseFirestorePackage(),
          new RNFirebaseStoragePackage(),
          new RNFirebaseMessagingPackage(),
          new RNFirebaseAnalyticsPackage(),
          new RNFirebaseLinksPackage(),
          new CodePush(BuildConfig.CODEPUSH_KEY, MainApplication.this, BuildConfig.DEBUG, R.string.CodePushPublicKey)
        );
      }

      @Override
      protected String getJSMainModuleName() {
        return "index";
      }
  }

  protected static CallbackManager getCallbackManager() {
    return mCallbackManager;
  }

/*
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
   
  }; */

  private final MyReactNativeHost mReactNativeHost = new MyReactNativeHost(this);

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    CodePush.setReactInstanceHolder(mReactNativeHost);
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```
### EntryPoint.js

```
class EntryPoint extends React.Component {
    render () {
        return (
            <Provider store={store}>
                <MenuProvider>
                    <App />
                </MenuProvider>
            </Provider>
        )
    }
}

export default codePush({ checkFrequency: codePush.CheckFrequency.ON_APP_RESUME })(EntryPoint)
```

**Comment by alexandergoncharov** [comment]
Hi @DavideValdo ,
Thanks for reporting!

Could you please provide command which you used for release update?
Also could you please run this command: `code-push deployment history <yourAppName> <yourTargetDeploymentName> --format=json`
You'll see json with your releases. Find your issue release, download release package(for this use blobUrl filed), add `.zip` for your downloaded file and unzip it. Please check your root folder. It should be `CodePush` name. Please let me know if it so or wrong.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
@DavideValdo ,
Thanks for keeping us in touch!

code-push cli is still operational but it will be deprecated soon. Our recommendation is using appcenter-cli.
