### ISSUE TITLE
"error: incompatible types: ReactNativeHost cannot be converted to ReactInstanceHolder" compiler error

### ISSUE THREAD

**Issue by DavideValdo** [Microsoft/react-native-code-push#1464]
### Steps to Reproduce
1. Configure CodePush following https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-android.md#for-react-native--v029-background-react-instances
2. Configure react-native-fbsdk
3. Enclose the ReactInstanceHolder class declaration within MainApplication 

### Expected Behavior
Application should start.

### Actual Behavior
This error is given.

<img width="1192" alt="screen shot 2018-12-03 at 01 14 50" src="https://user-images.githubusercontent.com/26572302/49346900-02ab2580-f699-11e8-9446-ca7d5e6f81fd.png">

My `MainApplication.java`
```
package com.happyin.original;

import android.annotation.SuppressLint;
import android.app.Application;

import com.facebook.react.ReactApplication;
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import com.facebook.CallbackManager;
import com.facebook.FacebookSdk;
import com.facebook.reactnative.androidsdk.FBSDKPackage;

import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.analytics.RNFirebaseAnalyticsPackage;
import io.invertase.firebase.auth.RNFirebaseAuthPackage;
import io.invertase.firebase.database.RNFirebaseDatabasePackage;
import io.invertase.firebase.fabric.crashlytics.RNFirebaseCrashlyticsPackage;
import io.invertase.firebase.firestore.RNFirebaseFirestorePackage;
import io.invertase.firebase.instanceid.RNFirebaseInstanceIdPackage;
import io.invertase.firebase.links.RNFirebaseLinksPackage;
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;
import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;
import io.invertase.firebase.storage.RNFirebaseStoragePackage;

import com.airbnb.android.react.maps.MapsPackage;
import com.microsoft.codepush.react.CodePush;
import com.microsoft.codepush.react.ReactInstanceHolder;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  public class HappyInReactNativeHost extends ReactNativeHost implements ReactInstanceHolder {
    HappyInReactNativeHost(Application application) {
            super(application);
    }    

    private CallbackManager mCallbackManager = CallbackManager.Factory.create();
    protected CallbackManager getCallbackManager() {
        return mCallbackManager;
    }

    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @SuppressLint("MissingPermission")
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.asList(
        new MainReactPackage(),
        new FBSDKPackage(mCallbackManager),
        new RNGestureHandlerPackage(),
        new RNFirebasePackage(),
        // add/remove these packages as appropriate
        new RNFirebaseAnalyticsPackage(),
        new RNFirebaseAuthPackage(),
        new RNFirebaseCrashlyticsPackage(),
        new RNFirebaseDatabasePackage(),
        new RNFirebaseFirestorePackage(),
        new RNFirebaseLinksPackage(),
        new RNFirebaseMessagingPackage(),
        new RNFirebaseNotificationsPackage(),
        new RNFirebaseStoragePackage(),
        new MapsPackage(),
        new CodePush(BuildConfig.CODEPUSH_KEY, MainApplication.this, BuildConfig.DEBUG, R.string.CodePushPublicKey)
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }

    @Override
    protected String getJSBundleFile() {
        return CodePush.getJSBundleFile();
    }
  }

  private final ReactNativeHost mReactNativeHost = new HappyInReactNativeHost(this);
  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
     CodePush.setReactInstanceHolder(this.mReactNativeHost);
     super.onCreate();
  }
}

```

### Environment

* react-native-code-push version: ^5.4.2
* react-native version: 0.57.1

**Comment by NickToropov** [comment]
Hi @DavideValdo! One clarification: do you launching a React Native instance without an `Activity` (for example, from within a native push notification receiver)?

**Comment by NickToropov** [comment]
@DavideValdo did you try to use this [docs](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-android.md#for-react-native--v029) or it doesn't suit you?

As for the example code you specified then it seems it's obsolete and required to be updated.

**Comment by DavideValdo** [comment]
The docs you link don't suit me. I need to launch React Native from push notification.

I've tried to follow https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-android.md#for-react-native--v029-background-react-instances, but declaring the `ReactInstanceHolder` class within the main class for the sake of avoiding compiler errors.

**Comment by NickToropov** [comment]
Please try such code:
```
public class MainApplication extends Application implements ReactApplication {
  ...
  private ReactInstanceHolder instanceHolder = new ReactInstanceHolder() {
    @Override
    public ReactInstanceManager getReactInstanceManager() {
      return mReactNativeHost.getReactInstanceManager();
    }
  };

  @Override
  public void onCreate() {
    ...
    CodePush.setReactInstanceHolder(instanceHolder);
    ...
  }
  ...
}
```

**Comment by DavideValdo** [comment]
I managed to make it compile with this code, but I know get a white screen on `react-native run-android`

```
package com.happyin.original;

import android.annotation.SuppressLint;
import android.app.Application;

import com.facebook.react.ReactApplication;
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import com.facebook.CallbackManager;
import com.facebook.FacebookSdk;
import com.facebook.reactnative.androidsdk.FBSDKPackage;

import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.analytics.RNFirebaseAnalyticsPackage;
import io.invertase.firebase.auth.RNFirebaseAuthPackage;
import io.invertase.firebase.database.RNFirebaseDatabasePackage;
import io.invertase.firebase.fabric.crashlytics.RNFirebaseCrashlyticsPackage;
import io.invertase.firebase.firestore.RNFirebaseFirestorePackage;
import io.invertase.firebase.instanceid.RNFirebaseInstanceIdPackage;
import io.invertase.firebase.links.RNFirebaseLinksPackage;
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;
import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;
import io.invertase.firebase.storage.RNFirebaseStoragePackage;

import com.airbnb.android.react.maps.MapsPackage;
import com.microsoft.codepush.react.CodePush;
import com.microsoft.codepush.react.ReactInstanceHolder;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  public class EntryPoint extends ReactNativeHost implements ReactInstanceHolder {
    private CallbackManager mCallbackManager = CallbackManager.Factory.create();

    EntryPoint (Application _parent) {
      super(_parent);
    }

    protected CallbackManager getCallbackManager() {
        return mCallbackManager;
    }

    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @SuppressLint("MissingPermission")
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.asList(
        new MainReactPackage(),
        new FBSDKPackage(mCallbackManager),
        new RNGestureHandlerPackage(),
        new RNFirebasePackage(),
        // add/remove these packages as appropriate
        new RNFirebaseAnalyticsPackage(),
        new RNFirebaseAuthPackage(),
        new RNFirebaseCrashlyticsPackage(),
        new RNFirebaseDatabasePackage(),
        new RNFirebaseFirestorePackage(),
        new RNFirebaseLinksPackage(),
        new RNFirebaseMessagingPackage(),
        new RNFirebaseNotificationsPackage(),
        new RNFirebaseStoragePackage(),
        new MapsPackage(),
        new CodePush(BuildConfig.CODEPUSH_KEY, MainApplication.this, BuildConfig.DEBUG, R.string.CodePushPublicKey)
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }

    @Override
    protected String getJSBundleFile() {
        return CodePush.getJSBundleFile();
    }
  };

  private final EntryPoint mReactNativeHost = new EntryPoint(this);

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
     CodePush.setReactInstanceHolder(mReactNativeHost);
     super.onCreate();
  }
}
```

**Comment by NickToropov** [comment]
Great!  We'll update docs a bit later. Will leave this issue opened until fix it.

**Comment by DavideValdo** [comment]
I'm getting a `RuntimeException` as soon as I open the release build.

```
java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
 at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
 at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:216)
 at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:32)
 at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:243)
 at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1114)
 at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116)
 at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:913)
 at java.lang.Thread.run(Thread.java:760)
```

**Comment by fanzhiri** [comment]
> Please try such code:
> 
> ```
> public class MainApplication extends Application implements ReactApplication {
>   ...
>   private ReactInstanceHolder instanceHolder = new ReactInstanceHolder() {
>     @Override
>     public ReactInstanceManager getReactInstanceManager() {
>       return mReactNativeHost.getReactInstanceManager();
>     }
>   };
> 
>   @Override
>   public void onCreate() {
>     ...
>     CodePush.setReactInstanceHolder(instanceHolder);
>     ...
>   }
>   ...
> }
> ```



> Please try such code:
> 
> ```
> public class MainApplication extends Application implements ReactApplication {
>   ...
>   private ReactInstanceHolder instanceHolder = new ReactInstanceHolder() {
>     @Override
>     public ReactInstanceManager getReactInstanceManager() {
>       return mReactNativeHost.getReactInstanceManager();
>     }
>   };
> 
>   @Override
>   public void onCreate() {
>     ...
>     CodePush.setReactInstanceHolder(instanceHolder);
>     ...
>   }
>   ...
> }
> ```

with add " import com.facebook.react.ReactInstanceManager; "
