### ISSUE TITLE
react-native link react-native-code-push error

### ISSUE THREAD

**Issue by dsky1990** [microsoft/react-native-code-push#1609]
### Steps to Reproduce
1. react-native init project
2. yarn add react-native-code-push
3. react-native link react-native-code-push --verbose

### Expected Behavior
What you expected to happen?

`link success`

### Actual Behavior
What actually happens?
```
# error log
debug Available platforms: iOS, Android
debug Targeted platforms: iOS, Android
debug Getting project config for iOS...
debug Getting project config for Android...
error No package found. Are you sure this is a React Native project?
error Invalid attribute name
Line: 1
Column: 3
Char: <
debug Error: Invalid attribute name
Line: 1
Column: 3
Char: <
    at error (/Users/dsky/dsky/pxtosApp/node_modules/xmldoc/node_modules/sax/lib/sax.js:666:10)
    at strictFail (/Users/dsky/dsky/pxtosApp/node_modules/xmldoc/node_modules/sax/lib/sax.js:692:7)
    at SAXParser.write (/Users/dsky/dsky/pxtosApp/node_modules/xmldoc/node_modules/sax/lib/sax.js:1324:13)
    at new XmlDocument (/Users/dsky/dsky/pxtosApp/node_modules/xmldoc/lib/xmldoc.js:199:15)
    at readManifest (/Users/dsky/dsky/pxtosApp/node_modules/@react-native-community/cli/build/tools/android/readManifest.js:44:10)
    at Object.projectConfig (/Users/dsky/dsky/pxtosApp/node_modules/@react-native-community/cli/build/tools/android/index.js:66:46)
    at Object.keys.forEach.platform (/Users/dsky/dsky/pxtosApp/node_modules/@react-native-community/cli/build/commands/link/getProjectConfig.js:25:62)
    at Array.forEach (<anonymous>)
    at getProjectConfig (/Users/dsky/dsky/pxtosApp/node_modules/@react-native-community/cli/build/commands/link/getProjectConfig.js:22:35)
    at Object.link [as func] (/Users/dsky/dsky/pxtosApp/node_modules/@react-native-community/cli/build/commands/link/link.js:74:45)
```

### Environment

* react-native-code-push version: "^5.6.0"
* react-native version: "0.59.8"
* iOS: 12.1 
* Mac : 10.14.2

### package.json

```
{
  "name": "pxtosApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "jcore-react-native": "^1.3.2",
    "jpush-react-native": "^2.5.3",
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-code-push": "^5.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "@babel/runtime": "^7.4.5",
    "babel-jest": "^24.8.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.54.1",
    "mobx": "^5.9.4",
    "mobx-react": "^5.4.4",
    "react-native-gesture-handler": "^1.2.1",
    "react-navigation": "^3.11.0",
    "react-navigation-stack": "^1.4.0",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by yuri-kulikov** [comment]
Hi @dsky1990,
Thanks for reporting!

I've tried to reproduce the issue:

1. `react-native init project`
2. `cd project`
3. `yarn add react-native-code-push`
4. `react-native link react-native-code-push --verbose`

![Screenshot 2019-06-10 at 15 57 32](https://user-images.githubusercontent.com/42337914/59197642-74a97d80-8b9a-11e9-9fc7-f42f5bf8fc00.png)

I also tried to use your version of `package.json` and run `yarn`, but `react-native link react-native-code-push` works as expected.

Can you reproduce it with the fresh init project or it happens with your app only?

**Comment by dsky1990** [comment]
@yuri-kulikov 
it's strange , all the project is exits 
![image](https://user-images.githubusercontent.com/1579516/59198419-4772c480-8bc6-11e9-842e-314264c666ea.png)

I'll try to init a new project and test, thanks
