### ISSUE TITLE
[CodePush] 404

### ISSUE THREAD

**Issue by nolan12345** [microsoft/react-native-code-push#1693]
[CodePush] 404: <!DOCTYPE html><html><head><title></title><link rel="stylesheet" href="/js/bootstrap-3.3.7/css/bootstrap.min.css"></head><body><h1>Not Found</h1><h2>404</h2><pre>NotFoundError: Not Found
    at /code-push-server/app.js:87:15
    at Layer.handle [as handle_request] (/code-push-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/code-push-server/node_modules/express/lib/router/index.js:317:13)
    at /code-push-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/code-push-server/node_modules/express/lib/router/index.js:335:12)
    at next (/code-push-server/node_modules/express/lib/router/index.js:275:10)
    at /code-push-server/node_modules/express/lib/router/index.js:635:15
    at next (/code-push-server/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/code-push-server/node_modules/express/lib/router/index.js:174:3)
    at router (/code-push-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/code-push-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/code-push-server/node_modules/express/lib/router/index.js:317:13)
    at /code-push-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/code-push-server/node_modules/express/lib/router/index.js:335:12)
    at next (/code-push-server/node_modules/express/lib/router/index.js:275:10)
    at next (/code-push-server/node_modules/express/lib/router/route.js:127:14)
    at next (/code-push-server/node_modules/express/lib/router/route.js:131:14)
    at next (/code-push-server/node_modules/express/lib/router/route.js:131:14)
    at next (/code-push-server/node_modules/express/lib/router/route.js:131:14)
    at next (/code-push-server/node_modules/express/lib/router/route.js:131:14)
    at next (/code-push-server/node_modules/express/lib/router/route.js:131:14)
    at next (/code-push-server/node_modules/express/lib/router/route.js:131:14)</pre></body><script src="/js/jquery-3.1.1.min.js"></script><script src="/js/bootstrap-3.3.7/js/bootstrap.min.js"></script></html>

**Comment by wangbf11** [comment]
我也遇到相同问题

**Comment by nolan12345** [comment]
你解决了这个问题么

**Comment by nolan12345** [comment]
> 我也遇到相同问题

use "react-native-code-push": "git+https://git@github.com/lisong/react-native-code-push.git" instead "react-native-code-push": "x.x.x" in package.json
This approach solved my problem, other solutions didn't work

**Comment by Evan-Future** [comment]
serverUrl settings is invalid

**Comment by alexandergoncharov** [comment]
Hi all,
Thanks for reporting!

Looks like this is issue occured becasue we were updating CodePush server side. We are sorry for that. :disappointed:
It works correctly now.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or if you faced this issue again.

**Comment by yarapolana** [comment]
Strange, it is still happening today, are you still updating codepush server side?
@alexandergoncharov
