### ISSUE TITLE
Android app crash when use code push

### ISSUE THREAD

**Issue by Stjng** [microsoft/react-native-code-push#1708]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. install react-native-code-push
2. Use autolinking
3. Add `return CodePush.getJSBundleFile();` to `getJSMainModuleName()`
4. Run app

I also tried add this but still same problem
```java
@Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
            packages.add(new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), getApplicationContext(), BuildConfig.DEBUG));
          return packages;
        }
```

### Expected Behavior
What you expected to happen?
CodePush can update my code

### Actual Behavior
What actually happens?
Get Error `A CodePush instance has not been created yet. Have you added it to your app's list of ReactPackages?`
```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sting.movie/com.safety.MainActivity}: com.microsoft.codepush.react.CodePushNotInitializedException: A CodePush instance has not been created yet. Have you added it to your app's list of ReactPackages?
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3268)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3407)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7343)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
     Caused by: com.microsoft.codepush.react.CodePushNotInitializedException: A CodePush instance has not been created yet. Have you added it to your app's list of ReactPackages?
        at com.microsoft.codepush.react.CodePush.getJSBundleFile(CodePush.java:206)
        at com.microsoft.codepush.react.CodePush.getJSBundleFile(CodePush.java:201)
        at com.safety.MainApplication$1.getJSMainModuleName(MainApplication.java:35)
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:68)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:38)
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:103)
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:88)
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:83)
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:44)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3243)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3407) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7343) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933) 
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 5.7.0
* react-native version: 0.61.2
* iOS/Android/Windows version: Android 10, API 29
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by rodgomesc** [comment]
this line
>  `packages.add(new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), getApplicationContext(), BuildConfig.DEBUG));`

does the trick for me

**Comment by bhavukjain1** [comment]
@Stjng were you able to find a solution for this?

**Comment by Stjng** [comment]
@bhavukjain1    Yes, its because i was confuse about `getJSMainModuleName` and `getJSBundleFile` in `MainApplication.java` ( also not read the docs carefully ). Just add both of this function and it should work.
```java
       @Override
       protected String getJSMainModuleName() {
            return "index";
        }

        @Override
        protected String getJSBundleFile() { return CodePush.getJSBundleFile();
        }
```

**Comment by FathomSamadhan** [comment]
package com.rmw;

import android.app.Application;
import android.util.Log;

import com.facebook.react.PackageList;
import com.facebook.hermes.reactexecutor.HermesExecutorFactory;
import com.facebook.react.bridge.JavaScriptExecutorFactory;
import com.facebook.react.ReactApplication;
import com.microsoft.codepush.react.CodePush;
import com.reactnativecommunity.geolocation.GeolocationPackage;
import com.freshchat.consumer.sdk.react.RNFreshchatSdkPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.List; 

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {


    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
    @Override
    protected String getJSBundleFile() {
    return CodePush.getJSBundleFile();
    }
    
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      return packages;
    }

  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}


What is wrong in above code because i have following problem.

2019-11-05 09:33:22.240 32183-32183/com.rmw E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rmw, PID: 32183
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rmw/com.rmw.MainActivity}: com.microsoft.codepush.react.CodePushNotInitializedException: A CodePush instance has not been created yet. Have you added it to your app's list of ReactPackages?
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3169)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3304)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2013)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7217)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)
     Caused by: com.microsoft.codepush.react.CodePushNotInitializedException: A CodePush instance has not been created yet. Have you added it to your app's list of ReactPackages?
        at com.microsoft.codepush.react.CodePush.getJSBundleFile(CodePush.java:206)
        at com.microsoft.codepush.react.CodePush.getJSBundleFile(CodePush.java:201)
        at com.rmw.MainApplication$1.getJSBundleFile(MainApplication.java:25)
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:82)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:91)
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:80)
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:52)
        at com.rmw.MainActivity.onCreate(MainActivity.java:36)
        at android.app.Activity.performCreate(Activity.java:7283)
        at android.app.Activity.performCreate(Activity.java:7274)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3149)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3304) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2013) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:227) 
        at android.app.ActivityThread.main(ActivityThread.java:7217) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)

**Comment by ValterSantosMatos** [comment]
@Stjng, did the same thing... guess the docs could have a small note on this

**Comment by jeancatarina** [comment]
```
import com.microsoft.appcenter.reactnative.crashes.AppCenterReactNativeCrashesPackage;
import com.microsoft.appcenter.reactnative.analytics.AppCenterReactNativeAnalyticsPackage;
import com.microsoft.appcenter.reactnative.appcenter.AppCenterReactNativePackage;
import com.microsoft.codepush.react.CodePush;
```
```
@Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
		  packages.add(new AppCenterReactNativeCrashesPackage(MainApplication.this, getResources().getString(R.string.appCenterCrashes_whenToSendCrashes)));
      	  packages.add(new AppCenterReactNativeAnalyticsPackage(MainApplication.this, getResources().getString(R.string.appCenterAnalytics_whenToEnableAnalytics)));
		  packages.add(new AppCenterReactNativePackage(MainApplication.this));
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }

		@Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
}
```

error:
`com.microsoft.codepush.react.CodePushNotInitializedException: A CodePush instance has not been created yet. Have you added it to your app's list of ReactPackages?`

**Comment by daheeahn** [comment]
> this line
> 
> > `packages.add(new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), getApplicationContext(), BuildConfig.DEBUG));`
> 
> does the trick for me

thank you!!! you saved my day!
