### ISSUE TITLE
Task :app:generateBundledResourcesHashRelease FAILED

### ISSUE THREAD

**Issue by afrinsulthana1** [microsoft/react-native-code-push#1812]
I have a react native app and it fails when I try to make a build after adding CodePush.

### Expected Behavior
Build & run on Android without errors

### Actual Behavior
The build fails with the following message:
```
Task :app:generateBundledResourcesHashQARelease FAILED
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '../android/app/build/generated/res/react/QA/release'
    at Object.readdirSync (fs.js:871:3)
    at getFilesInFolder (../node_modules/react-native-code-push/scripts/getFilesInFolder.js:7:26)
    at Object.<anonymous> (../node_modules/react-native-code-push/scripts/generateBundledResourcesHash.js:38:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '../android/app/build/generated/res/react/QA/release'
```

### Environment

* react-native-code-push version: 6.1.0
* react-native version: 0.61.5
* iOS/Android/Windows version: Android API 28

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @afrinsulthana1 ,
Thanks for reporting!

Could you please provide demo app with reporducing issue and reprosteps? I would like to reproduce and investigate it.

**Comment by alexandergoncharov** [comment]
Hi @afrinsulthana1 

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions or provide a demo app.

**Comment by spacesuitdiver** [comment]
@alexandergoncharov this issue is duplicated across #1866 #1578 #1776 and simply put is due to us not being able to configure where codepush expects the jsbundle. One of these tickets should be reopened and tracked as it's pretty straightforward to reproduce, turn off bundling the release in the gradle file.
