### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by Adr1ann** [microsoft/react-native-code-push#1813]
I have a react native app and it fails when I try to release a version in android app from appcenter. On iOS works.

**Expected Behavior**
run appcenter codepush release-react -a owner_name/app_name -d Production and see the release in app center on android app

**Actual Behavior**
The release fails with the following message:

Running "react-native bundle" command:

node node_modules\.bin\react-native bundle --assets-dest C:\Users\Ady\AppData\Local\Temp\code-push2020217-8452-tr6cke.e6ay\CodePush --bundle-output C:\Users\Ady\AppData\Local\Temp\code-push2020217-8452-tr6cke.e6ay\CodePush\index.android.bundle --dev false --entry-file index.js --platform android
D:\..\..\node_modules\.bin\react-nat
ive:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

**SyntaxError: missing ) after argument list**
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Error: Failed to release a CodePush update.

**Environment**
react-native-code-push version: 6.1.0
react-native version: 0.61.5
appcenter: 3.0.0

ext {
        googlePlayServicesVersion = "17.0.0"
        firebaseVersion = "17.3.4"
        buildToolsVersion = "28.0.3"
        minSdkVersion = 18
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesAuthVersion = "17.0.0"
        kotlinVersion = "1.3.41"
 }

**Comment by Adr1ann** [comment]
Maybe it is because the application is not yet on google play with react-native-code-push implemented?

**Comment by AndrewMorsillo** [comment]
same thing happening here

**Comment by azilberbaum** [comment]
Same error - any luck anyone?!

**Comment by azilberbaum** [comment]
I rolled back t version  2.3.3

`npm install appcenter@2.3.3 -g`

And it is working again

**Comment by Adr1ann** [comment]
installing version 2.3.3 solves the problem

**Comment by bry-guy** [comment]
Hey folks! I just started working on this issue today. Glad you were able to find a workaround! I'm going to re-open the issue so that we can work on resolving it for version 3.0.0 of the App Center CLI as well.

We've opened a bug on our backlog to track this work. I did have a couple of questions:
- Are you using Yarn? If so, which version?
- Have you performed any custom modifications to the default `react.gradle` file from the React-Native repository?

Thanks!

**Comment by Adr1ann** [comment]
1. Yes, i use  Yarn version 1.21.1
2. More exactly?

**Comment by andreidubov** [comment]
Hi @Adr1ann,
Sorry for some delay.

We fixed this problem in this [PR.](https://github.com/microsoft/appcenter-cli/pull/766) These changes will be applied in the next release of appcenter-cli, as soon as it is done, I will inform you.

**Comment by andreidubov** [comment]
Hay, @Adr1ann,

The release with the fix of this error has already been made in appcenter cli, please update your cli. 
I'm going to close this issue for now. Please feel free to reopen it if you still have this issue after installation update.

**Comment by AlexanderWeigand** [comment]
Hey, @andreidubov

I am using appcenter in a monorepo with pnpm and NX.
On my local windows machine, the `appcenter codepush release-react` command works perfectly. It finds the correct bundler command in the root node_modules. Here is the output from my windows machine:

```
Running "react-native bundle" command:

node D:\Projects\patzo\repositories\main\node_modules\.pnpm\react-native@0.72.10_@babel+core@7.24.0_@babel+preset-env@7.24.0_react@18.2.0\node_modules\react-native\local-cli\cli.js bundle --assets-dest C:\Users\Alex\AppData\Loca
l\Temp\code-push2024320-10696-fxv8dz.iv3ph\CodePush --bundle-output C:\Users\Alex\AppData\Local\Temp\code-push2024320-10696-fxv8dz.iv3ph\CodePush\index.android.bundle --dev false --entry-file index.js --platform android
```

However, when I run the command in my Gitlab CI on a [saas-linux-small-amd64](https://docs.gitlab.com/ee/ci/runners/hosted_runners/linux.html#machine-types-available-for-linux-x86-64) machine, it throws the error mentioned in this issue:

```
Running "react-native bundle" command:

node node_modules/.bin/react-native bundle --assets-dest /tmp/code-push2024320-167-h6n0is.4an7n/CodePush --bundle-output /tmp/code-push2024320-167-h6n0is.4an7n/CodePush/index.android.bundle --dev false --entry-file index.js --platform android
/builds/patzo1/main/packages/apps/mobile/node_modules/.bin/react-native:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
 ^^^^^^^
SyntaxError: missing ) after argument list
```

I am a bit confused, since all of the issues related to this seem to indicate that this error only happens on windows. But here I am, getting the error on linux.
Maybe it has something to do with me running the `appcenter codepush release-react` command via `nx run`, but I'm not sure.

**Comment by DordeDimitrijev** [comment]
Closing due to inactivity

**Comment by suwu150** [comment]
any update?

**Comment by DmitriyKirakosyan** [comment]
@suwu150 please check comment https://github.com/microsoft/react-native-code-push/issues/1813/#issuecomment-2139089148
