### ISSUE TITLE
Android app crashed after restarting the app

### ISSUE THREAD

**Issue by Alejinho** [microsoft/react-native-code-push#1824]
### Steps to Reproduce
1. After code push tries to restart the app, the application crashes

### Expected Behavior
The application does not crash.

### Actual Behavior
After the application starts, and some update is intalled the application crashes, this is the logcat output.
```
2020-03-28 03:55:03.639 7444-7444/com.lapix.harperlatam D/ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
2020-03-28 03:55:06.577 7444-7511/com.lapix.harperlatam I/ReactNativeJS: [CodePush] Checking for update.
2020-03-28 03:55:06.580 7444-7511/com.lapix.harperlatam I/ReactNativeJS: [CodePush] Reporting binary update (1.7)
2020-03-28 03:55:07.559 7444-7511/com.lapix.harperlatam I/ReactNativeJS: [CodePush] Downloading package.
2020-03-28 03:55:08.609 7444-7479/com.lapix.harperlatam D/ReactNative: [CodePush] Applying full update.
2020-03-28 03:55:08.615 7444-7511/com.lapix.harperlatam I/ReactNativeJS: [CodePush] Installing update.
2020-03-28 03:55:08.627 7444-7512/com.lapix.harperlatam D/ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.lapix.harperlatam/files/CodePush/b782e819c5b2b9a20610f96e35e323a5258f670ae7a/CodePush/index.android.bundle"
2020-03-28 03:55:08.631 7444-7512/com.lapix.harperlatam D/ReactNative: [CodePush] Update did not finish loading the last time, rolling back to a previous version.
2020-03-28 03:55:08.644 7444-7512/com.lapix.harperlatam D/ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
2020-03-28 03:55:08.645 7444-7512/com.lapix.harperlatam D/ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
2020-03-28 03:55:08.647 7444-7511/com.lapix.harperlatam I/ReactNativeJS: [CodePush] Restarting app
2020-03-28 03:55:08.678 7444-7444/com.lapix.harperlatam E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lapix.harperlatam, PID: 7444
    java.lang.AssertionError: recreateReactContextInBackground should only be called after the initial createReactContextInBackground call.
        at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:72)
        at com.facebook.react.ReactInstanceManager.recreateReactContextInBackground(ReactInstanceManager.java:357)
        at com.microsoft.codepush.react.CodePushNativeModule$2.run(CodePushNativeModule.java:151)
```
We use `react-native-navigation` so the MainApplication.java looks like this:
```java
public class MainApplication extends NavigationApplication {

    @Override
    public void onCreate() {
        super.onCreate();
        SoLoader.init(this, /* native exopackage */ false);
    }

    @Override
    public ReactNativeHost getReactNativeHost() {
        ReactNativeHost host = new NavigationReactNativeHost(this) {
            @Override
            protected String getJSMainModuleName() {
                return "index";
            }

            @Override
            public boolean getUseDeveloperSupport() {
                return BuildConfig.DEBUG;
            }

            protected List<ReactPackage> getPackages() {
                @SuppressWarnings("UnnecessaryLocalVariable")
                List<ReactPackage> packages = new PackageList(this).getPackages();
                // Packages that cannot be autolinked yet can be added manually here, for example:
                // packages.add(new MyReactNativePackage());
                return packages;
            }

            @Override
            protected String getJSBundleFile() {
                return CodePush.getJSBundleFile();
            }
        };

        return host;
    }
}
```
This is the MainActivity.java. *If it matters.*
```java
public class MainActivity extends NavigationActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        SplashScreen.show(this, R.style.SplashScreen_SplashAnimation);
        super.onCreate(savedInstanceState);
    }
}
```
The `app/android/build.bradle` already has this line `apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"`

We use the codepush HOC to wrap one of out components, this component is the first one that `react-native-navigation` uses.

### Environment

* react-native-code-push version: 6.1.1
* react-native version: 0.61.5
* iOS/Android/Windows version: Android 7.0
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Simulator, and physical devices.

**Comment by Alejinho** [comment]
I'm sorry, it was a pretty simple error. If someone else has this problem, this is what happened.
When code-push tries to restart the application it calls the method `getReactNativeHost` this will return the current `ReactNativeHost` instance, in this case I was creating a new instance every time the method was called, that way we could not restart the application with the given context, so we just need to make sure the same instance is returned always.

This is how the `MainApplication.java` looks now.

```java
public class MainApplication extends NavigationApplication {
    
    // Now this is an instance property
    //   ||
    //  \||/
    //   V
    ReactNativeHost host = new NavigationReactNativeHost(this) {
        @Override
        protected String getJSMainModuleName() {
            return "index";
        }

        @Override
        public boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        protected List<ReactPackage> getPackages() {
            @SuppressWarnings("UnnecessaryLocalVariable")
            List<ReactPackage> packages = new PackageList(this).getPackages();
            // Packages that cannot be autolinked yet can be added manually here, for example:
            // packages.add(new MyReactNativePackage());
            return packages;
        }

        @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }
    };

    @Override
    public void onCreate() {
        super.onCreate();
        SoLoader.init(this, /* native exopackage */ false);
    }

    @Override
    public ReactNativeHost getReactNativeHost() {
        return host;
    }
}
```
