### ISSUE TITLE
Android RN 0.62 Compile error

### ISSUE THREAD

**Issue by DLevai94** [microsoft/react-native-code-push#1828]
### Steps to Reproduce
1. Create a new RN project
2.  Integrate Codepush
3. Run `yarn android' or 'cd android && ./gradlew clean`

### Expected Behavior
Compile the app

### Actual Behavior

```
  FAILURE: Build failed with an exception.

* Where:
Script '/Users/davidlevai/Work/Classy/Unipie/UnipieApp/node_modules/react-native/react.gradle' line: 10

* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'project' for settings 'UnipieApp' of type org.gradle.initialization.DefaultSettings.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

    at makeError (/Users/davidlevai/Work/Classy/Unipie/UnipieApp/node_modules/execa/index.js:174:9)
    at /Users/davidlevai/Work/Classy/Unipie/UnipieApp/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (/Users/davidlevai/Work/Classy/Unipie/UnipieApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/davidlevai/Work/Classy/Unipie/UnipieApp/node_modules/@react-native-community/cli/build/index.js:186:9)
```

### Environment

* react-native-code-push version: 6.1.1
* react-native version: 0.62
* iOS/Android/Windows version: Android SDK 28

**Comment by virdesai** [comment]
https://github.com/microsoft/react-native-code-push/issues/1822#issuecomment-605497321

**Comment by alexandergoncharov** [comment]
Hi @DLevai94 ,
Thanks for reporting!

Unfortunately we already have opened the issue for that: https://github.com/microsoft/react-native-code-push/pull/1829

So, I'm going to close this issue as duplicate.
