### ISSUE TITLE
Could not determine the dependencies of task ':react-native-code-push:compileDebugAidl'.

### ISSUE THREAD

**Issue by yash1511** [microsoft/react-native-code-push#1833]
The issue occurs only in Android and not in iOS

### Steps to Reproduce
1. ```react-native init``` v0.61.4
2. Configure Codepush for Android
3. Attempt to build

### Expected Behavior
What you expected to happen?
Build succeeds and codepush is configured
### Actual Behavior
What actually happens?
```
  FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-code-push:compileDebugAidl'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.3.1
  ,2.3]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.nimbusds:nimbus-jose-jwt:5.1 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2
  .3.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends on project 'react' which depends onto net.minidev:json-smart@{strictly 2.3}
  -- Project 'app' depends on project 'react' which depends onto com.nimbusds:nimbus-jose-jwt@{strictly 5.1}
  -- Project 'app' depends on project 'react' which depends onto com.nimbusds:nimbus-jose-jwt@5.1

  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s

    at checkExecSyncError (child_process.js:621:11)
    at execFileSync (child_process.js:639:15)
    at runOnAllDevices (C:\Users\Tanay Jain\Desktop\realyze-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at buildAndRun (C:\Users\Tanay Jain\Desktop\realyze-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)   
    at C:\Users\Tanay Jain\Desktop\realyze-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Command.handleAction (C:\Users\Tanay Jain\Desktop\realyze-app\node_modules\@react-native-community\cli\build\index.js:164:9)
```

### Environment

* react-native-code-push version: 6.1.1
* react-native version: 0.61.4
* Android version: 10
* Does this reproduce on a debug build or release build?
Both
* Does this reproduce on a simulator, or only on a physical device?
Physical Device
(The more info the faster we will be able to address it!)

**Comment by Harshitha91** [comment]
https://github.com/microsoft/react-native-code-push/issues/1640 check this

**Comment by yash1511** [comment]
Thanks @Harshitha91  I'll check it out

**Comment by alexandergoncharov** [comment]
HI @yash1511 ,
Thanks for reporting!

Thanks @Harshitha91 for the provided link.

I'm going to close this issue as a duplicate. Please feel free to reopen it if you have any questions.

**Comment by Deependra-jhariya87** [comment]
can you share a working solution about these issue ...
