### ISSUE TITLE
ask :app:generateBundledResourcesHashRelease FAILED

### ISSUE THREAD

**Issue by zayantharani** [microsoft/react-native-code-push#1866]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. git clone https://github.com/SyedGhazanferAnwar/LBReactApp.git
2. npm install
3. cd android & gradlew assembleRelease -x bundleReleaseJsAndAssets

### Expected Behavior
Build release apk

### Actual Behavior
FAILURE: Build failed with an exception.
```
  STACK TRACE AND/OR SCREENSHOTS

 Task :app:generateBundledResourcesHashRelease FAILED
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Zayan\Desktop\CS\ReactNative\LBReactApp\android\app\build\generated\res\react\release'
    at Object.readdirSync (fs.js:854:3)
    at getFilesInFolder (C:\Users\Zayan\Desktop\CS\ReactNative\LBReactApp\node_modules\react-native-code-push\scripts\getFilesInFolder.js:7:26)
    at Object.<anonymous> (C:\Users\Zayan\Desktop\CS\ReactNative\LBReactApp\node_modules\react-native-code-push\scripts\generateBundledResourcesHash.js:38:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Zayan\\Desktop\\CS\\ReactNative\\LBReactApp\\android\\app\\build\\generated\\res\\react\\release'
}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateBundledResourcesHashRelease'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 27s
247 actionable tasks: 247 executed


### Environment

* react-native-code-push version: 6.2.0
* react-native version: 0.62
* iOS/Android/Windows version: Android:  
   buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? physical

(The more info the faster we will be able to address it!)

**Comment by zayantharani** [comment]
https://github.com/microsoft/react-native-code-push/issues/1578#issuecomment-503993512
This solution worked.
The file to edit can be found at: 
node_modules\react-native-code-push\android\codepush.gradle

**Comment by sameer-kotwal** [comment]
#1578 solution is not working

**Comment by spacesuitdiver** [comment]
It's worth noting that you can also copy your bundle into `./android/app/build/generated/res/react/release` so CodePush doesn't explode prior to building your app.
