### ISSUE TITLE
Error: Unable to resolve module `../utils/code-push-error` from `node_modules/code-push/script/acquisition-sdk.js`:

### ISSUE THREAD

**Issue by tusharpandey** [microsoft/react-native-code-push#1975]
![Screenshot 2020-11-06 at 1 56 30 PM](https://user-images.githubusercontent.com/4696846/98343552-ff183a00-2037-11eb-93fd-f611125d48a3.png)

**Comment by huuthinh245** [comment]
i run npx react-native start --reset-cache solved the problem
Hope can help you

**Comment by pranshuchittora** [comment]
`npx react-native start --reset-cache` this works. But not sure about the origin of the error.

**Comment by HimiGame** [comment]
npx react-native start --reset-cache not helping ... sad

**Comment by garanguillorycapitalrx** [comment]
@HimiGame https://github.com/microsoft/react-native-code-push/issues/2060#issuecomment-812034655

**Comment by gabrielmoncea** [comment]
My app fails to build with the same error

**Comment by justinairbase** [comment]
```
[Sat Apr 03 2021 19:55:24.833]  BUNDLE  ./index.js 

error: Error: Unable to resolve module code-push/script/acquisition-sdk from /Users/<user>/Projects/<project-name>/node_modules/react-native-code-push/CodePush.js: code-push/script/acquisition-sdk could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
> 1 | import { AcquisitionManager as Sdk } from "code-push/script/acquisition-sdk";
    |                                            ^
  2 | import { Alert } from "./AlertAdapter";
  3 | import requestFetchAdapter from "./request-fetch-adapter";
  4 | import { AppState, Platform } from "react-native";
    at ModuleResolver.resolveDependency (/Users/<user>/Projects/<project-name>/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:191:15)
    at DependencyGraph.resolveDependency (/Users/<user>/Projects/<project-name>/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at Object.resolve (/Users/<user>/Projects/<project-name>/node_modules/metro/src/lib/transformHelpers.js:271:42)
    at resolve (/Users/<user>/Projects/<project-name>/node_modules/metro/src/DeltaBundler/traverseDependencies.js:571:33)
    at /Users/<user>/Projects/<project-name>/node_modules/metro/src/DeltaBundler/traverseDependencies.js:587:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/<user>/Projects/<project-name>/node_modules/metro/src/DeltaBundler/traverseDependencies.js:586:33)
    at /Users/<user>/Projects/<project-name>/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/<user>/Projects/<project-name>/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

Getting this error after trying all of the below
1. Cleared all packages using: `rm -rf node_modules/ yarn.lock ios/Pods ios/Podfile.lock`
2. Cleared yarn cache: `yarn cache clean`
3. Removed 'DerivedData` and `Caches` contents
4. Installed packages again using `yarn`
5. Installed Pods using `npx pod-install`, also tried `--repo-update` flag
6. Cleaned native projects: `./gradlew clean` and `xcodebuild clean`

**Comment by justinairbase** [comment]
Update: This helped me, it works after running: `yarn upgrade code-push@4.0.2`

Link to original answer: https://github.com/microsoft/react-native-code-push/issues/2060#issuecomment-812066464

**Comment by gabrielmoncea** [comment]
please don't do that
