### ISSUE TITLE
App restart does not perform with InstallMode.Immediate

### ISSUE THREAD

**Issue by danut-t** [microsoft/react-native-code-push#1980]
Hello,

We're seeing an issue where the soft restart that Codepush tries to perform randomly does not actually happen. This seems to occur in combination with RNGestureHandler and ReactNavigation, but it isn't clear where the issue comes from exactly.

**Log when it's working:**

```
InputMethodManager		hideSoftInputFromWindow ignore mServedView == null or mServedView.getWindowToken() != windowToken, mServedView :com.reactnativecommunity.webview.RNCWebViewManager$RNCWebView{997faa7 VFEDHVC.. .F...... 0,0-972,1896 #87}
ReactNative		[GESTURE HANDLER] Gesture handler is already enabled for a parent view
ReactNativeJNI		Memory warning (pressure level: TRIM_MEMORY_UI_HIDDEN) received by JS VM, ignoring because it's non-severe
ReactNative		[CodePush] Loading JS bundle from "assets://index.android.bundle"
System.err			at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87)
System.err			at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
ReactNativeFirebaseApp		received application context.
SoLoader		About to load: libreactnativejni.so
SoLoader		libreactnativejni.so not found on /data/data/<appName>/lib-main
SoLoader		libreactnativejni.so found on /data/app/<appName>-qHqBlnExKNughD4g3Ogt-g==/lib/arm64
SoLoader		Not resolving dependencies for libreactnativejni.so
SoLoader		Loaded: libreactnativejni.so
unknown:ReactNative		ReactInstanceManager.createReactContext: mJSIModulePackage null
ReactNativeJNI		logMarker CREATE_REACT_CONTEXT_END
ReactNativeJNI		logMarker RUN_JS_BUNDLE_START
unknown:ReactNative		ReactInstanceManager.attachRootViewToInstance()
unknown:ReactNative		Unable to launch logbox because react was unable to create the root view
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTGroupViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTGroupShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTShapeViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTShapeShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTTextViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTTextShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTSurfaceViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTSurfaceViewShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class org.reactnative.maskedview.RNCMaskedViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.webview.RNCWebViewManager
SoLoader		About to load: libreactnativeblob.so
SoLoader		libreactnativeblob.so not found on /data/data/<appName>/lib-main
SoLoader		libreactnativeblob.so found on /data/app/<appName>-qHqBlnExKNughD4g3Ogt-g==/lib/arm64
SoLoader		Not resolving dependencies for libreactnativeblob.so
SoLoader		Loaded: libreactnativeblob.so
ReactNativeJNI		logMarker RUN_JS_BUNDLE_END
ReactNativeJS		Running "<appName>" with {"initialProps":{"some":"props"},"rootTag":1}
ReactNative		[CodePush] Applying full update.
ReactNative		[CodePush] Loading JS bundle from "<bundlePath>index.android.bundle"
ReactNative		[CodePush] Restarting app
unknown:ReactNative		Invoking JS callback after bridge has been destroyed.
unknown:ReactNative		ReactInstanceManager.createReactContext: mJSIModulePackage null
ReactNativeJNI		logMarker CREATE_REACT_CONTEXT_END
ReactNativeJNI		logMarker RUN_JS_BUNDLE_START
unknown:ReactNative		ReactInstanceManager.attachRootViewToInstance()
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTGroupViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTGroupShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTShapeViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTShapeShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTTextViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTTextShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTSurfaceViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTSurfaceViewShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class org.reactnative.maskedview.RNCMaskedViewManager
unknown:ReactNative		Unable to launch logbox because react was unable to create the root view
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.webview.RNCWebViewManager
ReactNativeJNI		logMarker RUN_JS_BUNDLE_END
ReactNativeJS		Running "<appName>" with {"initialProps":{"some":"props"},"rootTag":1}
ReactNativeJS		[CodePush] Reporting CodePush update success (v165)
ReactNative		[GESTURE HANDLER] Gesture handler is already enabled for a parent view
ReactNative		[GESTURE HANDLER] Initialize gesture handler for root view com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView{e324910 V.E...... ......ID 0,0-1080,2076 #b}
```

**Log when it's not working:**

```
ReactNativeJNI		Memory warning (pressure level: TRIM_MEMORY_UI_HIDDEN) received by JS VM, ignoring because it's non-severe
ApkSoSource		not allowing consideration of lib/arm64-v8a/libreactnativeblob.so: deferring to libdir
ApkSoSource		not allowing consideration of lib/arm64-v8a/libreactnativejni.so: deferring to libdir
ReactNative		[CodePush] Loading JS bundle from "assets://index.android.bundle"
System.err			at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87)
System.err			at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
ReactNativeFirebaseApp		received application context.
SoLoader		About to load: libreactnativejni.so
SoLoader		libreactnativejni.so not found on /data/data/<appName>/lib-main
SoLoader		libreactnativejni.so found on /data/app/<appName>-qHqBlnExKNughD4g3Ogt-g==/lib/arm64
SoLoader		Not resolving dependencies for libreactnativejni.so
SoLoader		Loaded: libreactnativejni.so
ReactNativeJNI		logMarker CREATE_REACT_CONTEXT_END
unknown:ReactNative		ReactInstanceManager.createReactContext: mJSIModulePackage null
ReactNativeJNI		logMarker RUN_JS_BUNDLE_START
unknown:ReactNative		ReactInstanceManager.attachRootViewToInstance()
unknown:ReactNative		Unable to launch logbox because react was unable to create the root view
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTGroupViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTGroupShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTShapeViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTShapeShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTTextViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTTextShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTSurfaceViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTSurfaceViewShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class org.reactnative.maskedview.RNCMaskedViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.webview.RNCWebViewManager
SoLoader		About to load: libreactnativeblob.so
SoLoader		libreactnativeblob.so not found on /data/data/<appName>/lib-main
SoLoader		libreactnativeblob.so found on /data/app/<appName>-qHqBlnExKNughD4g3Ogt-g==/lib/arm64
SoLoader		Not resolving dependencies for libreactnativeblob.so
SoLoader		Loaded: libreactnativeblob.so
ReactNativeJNI		logMarker RUN_JS_BUNDLE_END
ReactNativeJS		Running "<appName>" with {"initialProps":{"some":"props"},"rootTag":1}
ReactNativeJS		[CodePush] Reporting binary update (1.0.174)
ReactNative		[CodePush] Applying full update.
ReactNative		[CodePush] Loading JS bundle from "<bundlePath>/index.android.bundle"
ReactNative		[CodePush] Restarting app
ReactNativeJNI		logMarker CREATE_REACT_CONTEXT_END
unknown:ReactNative		ReactInstanceManager.createReactContext: mJSIModulePackage null
ReactNativeJNI		logMarker RUN_JS_BUNDLE_START
unknown:ReactNative		ReactInstanceManager.attachRootViewToInstance()
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.webview.RNCWebViewManager
unknown:ReactNative		Unable to launch logbox because react was unable to create the root view
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTGroupViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTGroupShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTShapeViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTShapeShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTTextViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTTextShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTSurfaceViewManager
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class com.reactnativecommunity.art.ARTSurfaceViewShadowNode
unknown:ViewManagerPropertyUpdater		Could not find generated setter for class org.reactnative.maskedview.RNCMaskedViewManager
unknown:ReactNative		Invoking JS callback after bridge has been destroyed.
unknown:ReactNative		Invoking JS callback after bridge has been destroyed.
ReactNative		[GESTURE HANDLER] Gesture handler is already enabled for a parent view
ReactNative		[GESTURE HANDLER] Initialize gesture handler for root view com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView{885953 V.E...... ......ID 0,0-1080,2076 #b}
unknown:ReactNative		Invoking JS callback after bridge has been destroyed.
unknown:ReactNative		Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
unknown:ReactNative		Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
unknown:ReactNative		Tried to enqueue runnable on already finished thread: 'js... dropping Runnable.
unknown:ReactNative		Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
ReactNativeJNI		logMarker RUN_JS_BUNDLE_END
ReactNativeJS		Running "<appName>" with {"initialProps":{"some":"props"},"rootTag":11}
ReactNativeJS		[CodePush] Reporting CodePush update success (v165)
ReactNative		[GESTURE HANDLER] Gesture handler is already enabled for a parent view
```

There's also the following exception that silently appears after restarting the app:

```
Unhandled SoftException
com.facebook.react.bridge.ReactNoCrashSoftException: Cannot get UIManager because the context doesn't contain an active CatalystInstance.
	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:59)
	at com.facebook.react.uimanager.UIManagerHelper.getEventDispatcher(UIManagerHelper.java:90)
	at com.facebook.react.uimanager.UIManagerHelper.getEventDispatcherForReactTag(UIManagerHelper.java:80)
	at com.facebook.react.views.textinput.ReactTextInputManager.getEventDispatcher(ReactTextInputManager.java:881)
	at com.facebook.react.views.textinput.ReactTextInputManager.access$000(ReactTextInputManager.java:85)
	at com.facebook.react.views.textinput.ReactTextInputManager$ReactScrollWatcher.<init>(ReactTextInputManager.java:1178)
	at com.facebook.react.views.textinput.ReactTextInputManager.setOnScroll(ReactTextInputManager.java:383)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:87)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:270)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:186)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:911)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1028)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:48)
	at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:986)
	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7811)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

As can be seen in the two logs, when the restart completes without issues, the root view is initialized after the codepush lifecycle has finished, but when the restart crashes, the root view initializes while the lifecycle is still ongoing.
This would suggest that the issue is coming from RNGestureHandler, but the actual initialization is performed by React Native as far as I know. Either way there seems to be a race condition that happens and leads to this problem, but I'm kind of at a loss here.

Any help with this would be much appreciated. Let me know if you need more info

Versions:

"react-native": "0.63.3",
"react-native-code-push": "6.4.0",
"react-native-gesture-handler": "1.8.0",
"@react-navigation/native": "5.8.6",
"@react-navigation/stack": "5.12.3"

**Comment by sunweiyang** [comment]
@danut-t I also experienced this issue, but then it appeared to become much better (either completely or partially eliminated, not sure; I've only tested it 3 times) when I updated my packages, specifically react-native-gesture-handler to 1.9.0.

For completeness, here are my package versions:
"react-native": "0.63.4",
"react-native-code-push": "6.4.0",
"react-native-gesture-handler": "1.9.0",
"@react-navigation/native": "5.8.10",
"@react-navigation/stack": "5.12.8"

**Comment by danut-t** [comment]
@sunweiyang We tried with the newer versions and the same thing happened unfortunately. Thank you for the suggestion though
