### ISSUE TITLE
[Android] Codepush crash on downloading update in Samsung devices

### ISSUE THREAD

**Issue by neeshurajput** [microsoft/react-native-code-push#2027]
My app is crashing in samsung devices while downloading the update.

Devices crashing on : 
Galaxy S10+
Galaxy C9 Pro
Galaxy J2 Pro
Galaxy S9+
Galaxy S7
Galaxy A9 (2018)
Galaxy A7 (2018)

Library versions :
React Native : 0.62.2
react-native-code-push : 6.3.0

Crash Log : 
Caused by java.lang.IllegalStateException: closed
       at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:175)
       at com.android.okhttp.internal.http.HttpEngine$2.read(HttpEngine.java:1025)
       at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:397)
       at com.google.firebase.perf.network.InstrHttpInputStream.read(InstrHttpInputStream.java:121)
       at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
       at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
       at com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage(CodePushUpdateManager.java:181)
       at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:290)
       at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:284)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

Can anyone help me out in knowing what's leading to this crash?

**Comment by feiyingx** [comment]
Did you find a solution?

**Comment by rkaartikeyan** [comment]
Hi @neeshurajput did you find any solution for this crash?
