### ISSUE TITLE
Void android.content.res.StringBlock.close() error when using react-native-code-push

### ISSUE THREAD

**Issue by rajeshmarotu** [microsoft/react-native-code-push#2028]
## Description
Hi, I am able to create a build successfully but the app is getting crashed on opening the app with above error description when checking using logcat.

## React Native version:
react-native-cli: 2.0.1
react-native: 0.59.10
react-native-code-push:5.6.1

## Error in console

E/System: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.res.StringBlock.close()' on a null object reference
     at android.content.res.ApkAssets.close(ApkAssets.java:201)
     at android.content.res.ApkAssets.finalize(ApkAssets.java:191)
     at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
     at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
     at java.lang.Daemons$Daemon.run(Daemons.java:137)
     at java.lang.Thread.run(Thread.java:929)

**Comment by lironsher** [comment]
Hi,

Have the same issue after upgrading rn from 0.61.5 to 0.64.2 and code push from 6 to 7 

any ideas?

**Comment by Pinwheeler** [comment]
+1

**Comment by peltax** [comment]
In our case this error was printed when the app was loading react-native-hms-maps and the huawei device didn't have HMS core installed. The actual error was UnsatisfiedLinkException (HuaweiMapsProvider.apk) and this was logged after it, just before crash.
