### ISSUE TITLE
Exception on loading package on Android

### ISSUE THREAD

**Issue by gekitz** [microsoft/react-native-code-push#2098]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Try to use CodePush on Android 9 or above
2. On downloading a package an exception will happen
3.

### Expected Behavior
The exception doesn't happen and the package is loaded correctly

### Actual Behavior
What actually happens?
```
E/ReactNative: [CodePush] Exception
    java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: AndroidOpenSSL, class: com.android.org.conscrypt.DefaultSSLContextImpl)
        at javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:284)
        at javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:306)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:181)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
        at com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage(CodePushUpdateManager.java:181)
        at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:290)
        at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:284)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: AndroidOpenSSL, class: com.android.org.conscrypt.DefaultSSLContextImpl)
        at java.security.Provider$Service.newInstance(Provider.java:1656)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:190)
        at javax.net.ssl.SSLContext.getDefault(SSLContext.java:130)
        at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:150)
        at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:343)
        at com.android.okhttp.HttpsHandler.createHttpsOkUrlFactory(HttpsHandler.java:92)
        at com.android.okhttp.HttpsHandler.newOkUrlFactory(HttpsHandler.java:53)
        at com.android.okhttp.HttpHandler.openConnection(HttpHandler.java:44)
        at java.net.URL.openConnection(URL.java:1006)
        at com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage(CodePushUpdateManager.java:169)
        at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:290) 
        at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:284) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.io.FileNotFoundException: hpg-ecr-2018.ts (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at java.io.FileInputStream.<init>(FileInputStream.java:112)
        at com.android.org.conscrypt.DefaultSSLContextImpl.getTrustManagers(DefaultSSLContextImpl.java:112)
        at com.android.org.conscrypt.OpenSSLContextImpl.<init>(OpenSSLContextImpl.java:85)
        at com.android.org.conscrypt.DefaultSSLContextImpl.<init>(DefaultSSLContextImpl.java:60)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at java.security.Provider$Service.newInstance(Provider.java:1634)
        	... 18 more
```

### Reproducible Demo

Creating the demo didn't work with the provided command, it fails with a "command not found" error

### Environment

* react-native-code-push version: 7.0.1
* react-native version: 0.60.5
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Both

We use JAVA_8 if that matters

**Comment by gekitz** [comment]
Apparently setting 
```
((HttpsURLConnection)connection).setSSLSocketFactory(new TLSSocketFactory());
```
helps and fixes the issue, no idea why though.

**Comment by gourav-singhal** [comment]
@gekitz can you share the file where we need to update this setting?
