### ISSUE TITLE
Updates fail to deliver for expo-bare application on Android

### ISSUE THREAD

**Issue by stopachka** [Microsoft/react-native-code-push#2171]
Hey team, I am installing CodePush on a react-native application, on the expo "bare" workflow. All is well on iOS, but I'm having issues with Android. 

### Expected Behavior

I expect CodePush to install updates.

### Actual Behavior

It installs updates on a _fresh_ install. However, it does not install subsequent updates. this is the error I see:

```
10-18 15:59:47.098  4930  4993 E AndroidRuntime: FATAL EXCEPTION: create_react_context
10-18 15:59:47.098  4930  4993 E AndroidRuntime: Process: com.consistentmobile, PID: 4930            
10-18 15:59:47.098  4930  4993 E AndroidRuntime: com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/com.consistentmobile/files/CodePush/
b6b59ef689b1b32c1beb93d69d2138cef6d7e6ca46c4c40268f37733cb90c7df/CodePush/index.android.bundle: No such file or directory
10-18 15:59:47.098  4930  4993 E AndroidRuntime:        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
10-18 15:59:47.098  4930  4993 E AndroidRuntime:        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile(CatalystInstanceImpl.java:240)
10-18 15:59:47.098  4930  4993 E AndroidRuntime:        at com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:48)                             
10-18 15:59:47.098  4930  4993 E AndroidRuntime:        at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:258)
10-18 15:59:47.098  4930  4993 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1293)
10-18 15:59:47.098  4930  4993 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
10-18 15:59:47.098  4930  4993 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
10-18 15:59:47.098  4930  4993 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)
```

**On first install, CodePush _does_ seem to download the latest update.**

**However, once the app is running, on cold-starts, updates no longer apply**. 

I _did_ notice that the app crashed and rolled back. Looking at the logs, the only thing I can see is the above error, but I am not sure _why_ it can't open that file.

### Reproducible Demo

The changes I made: 

https://gist.github.com/stopachka/f3e02eea4744c677c4fd4e7cba39dd27 

I also saw _this_ [issue](https://github.com/microsoft/react-native-code-push/issues/1891) -- it mentioned that some stuff needed to be deleted, that expo kept around from the "expo bare" workflow. I am not sure what needs to change though. 

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.63.4
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Both

(The more info the faster we will be able to address it!)

**Comment by stopachka** [comment]
Update: 

The bug was due to `expo-updates`. Expo "bare" apps come with expo-updates installed, and this hinders CodePush. To fix, remove expo-updates by following these instructions: 

https://github.com/expo/expo/blob/master/packages/expo-updates/README.md#uninstalling-expo-updates-for-expo-updates--090
