### ISSUE TITLE
Supporting for RN 0.70.0

### ISSUE THREAD

**Issue by felipejh** [microsoft/react-native-code-push#2334]
Is code-push compatible with RN 0.70.0?

**Comment by thiagovpaz** [comment]
Yes, tested on:

```javascript
"react": "18.1.0",
"react-native": "0.70.0",
"react-native-code-push": "^7.0.5"
```
🥹

**Comment by MajidNajafi** [comment]
Works fine on Linux, but throwing errors on Mac.

tested on:
```
"react": "18.1.0",
"react-native": "0.70.1",
"react-native-code-push": "^7.0.5",
```

Output:
```
Converting JS bundle to byte code via Hermes, running command:

node_modules/hermesvm/osx-bin/hermes -emit-binary -out /var/folders/2t/400g164s3tv_4d95hg_05mgw0000gn/T/code-push2022918-21996-mzow4k.5v3y/CodePush/index.android.bundle.hbc /var/folders/2t/400g164s3tv_4d95hg_05mgw0000gn/T/code-push2022918-21996-mzow4k.5v3y/CodePush/index.android.bundle -w
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/hermesvm/osx-bin/hermes ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node_modules/hermesvm/osx-bin/hermes',
  path: 'node_modules/hermesvm/osx-bin/hermes',
  spawnargs: [
    '-emit-binary',
    '-out',
    '/var/folders/2t/400g164s3tv_4d95hg_05mgw0000gn/T/code-push2022918-21996-mzow4k.5v3y/CodePush/index.android.bundle.hbc',
    '/var/folders/2t/400g164s3tv_4d95hg_05mgw0000gn/T/code-push2022918-21996-mzow4k.5v3y/CodePush/index.android.bundle',
    '-w'
  ]
}
```
