### ISSUE TITLE
Error: spawn node_modules/hermesvm/osx-bin/hermes ENOENT in turborepo 

### ISSUE THREAD

**Issue by ajiehatajie** [microsoft/react-native-code-push#2375]
```
info Writing bundle output to:, /var/folders/ds/g6jgv1651rl3_sdrxg24fdtm0000gn/T/code-push20221016-71341-1pogwdr.m3nh/CodePush/index.android.bundle
info Done writing bundle output
info Copying 14 asset files
info Done copying assets
Converting JS bundle to byte code via Hermes, running command:

node_modules/hermesvm/osx-bin/hermes -emit-binary -out /var/folders/ds/g6jgv1651rl3_sdrxg24fdtm0000gn/T/code-push20221016-71341-1pogwdr.m3nh/CodePush/index.android.bundle.hbc /var/folders/ds/g6jgv1651rl3_sdrxg24fdtm0000gn/T/code-push20221016-71341-1pogwdr.m3nh/CodePush/index.android.bundle -w
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/hermesvm/osx-bin/hermes ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node_modules/hermesvm/osx-bin/hermes',
  path: 'node_modules/hermesvm/osx-bin/hermes',
  spawnargs: [
    '-emit-binary',
    '-out',
    '/var/folders/ds/g6jgv1651rl3_sdrxg24fdtm0000gn/T/code-push20221016-71341-1pogwdr.m3nh/CodePush/index.android.bundle.hbc',
    '/var/folders/ds/g6jgv1651rl3_sdrxg24fdtm0000gn/T/code-push20221016-71341-1pogwdr.m3nh/CodePush/index.android.bundle',
    '-w'
  ]
}
node:child_process:915
    throw err;
    ^

Error: Command failed: appcenter codepush release-react --app ajie/Lgo-dev-android --bundle-name index.android.bundle --target-binary-version 1.0.2 --deployment-name Development
    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:912:15)
    at outputAndExecSync (/Users/legit-group/Documents/Works/mobile-apps/apps/lgo/scripts/codepush-release.js:22:3)
    at Object.<anonymous> (/Users/legit-group/Documents/Works/mobile-apps/apps/lgo/scripts/codepush-release.js:70:3)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 71341,
  stdout: null,
  stderr: null
}
```

### Environment

* react-native-code-push version: 7.0.5
* turbo repo: 1.6.3
* hermes enabled : true
* react-native version: 0.70.5
* iOS/Android/Windows version: 11
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? 

(The more info the faster we will be able to address it!)

**Comment by elliotdickison** [comment]
Duplicate of #2368, posted an answer there.
