### ISSUE TITLE
Receiving No virtual method object()Lorg/json/e on app start

### ISSUE THREAD

**Issue by pkpardeep482** [microsoft/react-native-code-push#2399]
Hi, i am receiving this crash on my release build on app start. Debug builds are working fine. I am using react-native 0.67.4

    "appcenter": "4.3.0",
    "appcenter-analytics": "4.3.0",
    "appcenter-crashes": "4.3.0",
    "react-native-code-push": "7.0.5",

Fatal Exception: java.lang.NoSuchMethodError: No virtual method object()Lorg/json/e; in class Lorg/json/e; or its super classes (declaration of 'org.json.e' appears in /data/app/~~dXfc0orwEajJECAG2s1hEg==/com.discoverpilgrim-UwOxwAIQKiGoBUKhGkdoOg==/base.apk!classes4.dex)
       at com.microsoft.appcenter.ingestion.models.json.DefaultLogSerializer.writeLog(DefaultLogSerializer.java:35)
       at com.microsoft.appcenter.ingestion.models.json.DefaultLogSerializer.serializeLog(DefaultLogSerializer.java:58)
       at com.microsoft.appcenter.persistence.DatabasePersistence.putLog(DatabasePersistence.java:269)
       at com.microsoft.appcenter.channel.DefaultChannel.enqueue(DefaultChannel.java:679)
       at com.microsoft.appcenter.AppCenter.sendStartServiceLog(AppCenter.java:1047)
       at com.microsoft.appcenter.AppCenter.finishStartServices(AppCenter.java:1032)
       at com.microsoft.appcenter.AppCenter.access$600(AppCenter.java:61)
       at com.microsoft.appcenter.AppCenter$7.run(AppCenter.java:935)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:263)
       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by Mahimsharma** [comment]
+1. having the exact same issue

**Comment by ajiehatajie** [comment]
+1. having the exact same issue

**Comment by Mahimsharma** [comment]
"appcenter": "4.3.0",
"appcenter-analytics": "4.3.0",
"appcenter-crashes": "4.3.0",

@ajiehatajie Removing the above-mentioned dependencies solved the issue for me. They were of no use because we have Firebase Crashlytics and Analytics. The Code Push works fine as usual without these dependencies. I was not able to find the actual fix, but this workaround worked for me!

**Comment by AnatolyPristensky** [comment]
Closing due to absence of activity.
