### ISSUE TITLE
[Android] Crash on app start "I/O error during system call, Software caused connection abort" with Hermes engine

### ISSUE THREAD

**Issue by retyui** [microsoft/react-native-code-push#2431]
### Steps to Reproduce

- Hermes: true
- react-native-code-push@7.0.1
- react-native@0.70.6

### Expected Behavior

no crash on app start when can't download a package with enabled Hermes engine 

### Actual Behavior

```
 at java.lang.Thread.run(Thread.java:929)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at android.os.AsyncTask$3.call(AsyncTask.java:389)
 at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:284)
 at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:290)
 at com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage(CodePushUpdateManager.java:195)
 at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
 at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
 at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
 at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
 at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
 at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
 at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
 at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@224814030@22.48.14 (100408-493411920):6)
 at com.google.android.gms.org.conscrypt.NativeSsl.read(:com.google.android.gms@224814030@22.48.14 (100408-493411920):3)
 at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_read(Native Method)
 javax.net.ssl.SSLException: Read error: ssl=0x76ea863848: I/O error during system call, Software caused connection abort
 [CodePush] Exception

```

### Reproducible Demo

only stack trace, sorry 

### Environment

* react-native-code-push version: 7.0.1
* react-native version: 0.70
* iOS/Android/Windows version: Android
* release build
* physical device (Huawei HUAWEI nova 5T (YAL-L21),  Android10 (v10)(Level 29), Mandaluyong City, Philippines)

**Comment by ko-devHong** [comment]
you can upgrade `7.0.5` and ref : https://github.com/microsoft/react-native-code-push/tree/v7.0.5/Examples/CodePushDemoApp

**Comment by retyui** [comment]
Ok will try the latest version
