### ISSUE TITLE
could not open file

### ISSUE THREAD

**Issue by cmdparkour** [microsoft/react-native-code-push#2451]
Process Name: 'io.dcloud.XXXXXX'
Thread Name: 'create_react_context'
Back traces starts.
com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/io.dcloud.H576E6CC7/files/CodePush/50cf041c9a6125ca47a1ba1092fdc7785669535f4d0026e211db423401634edb/CodePush/index.android.bundle: No such file or directory
	at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(CatalystInstanceImpl.java)
	at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile(CatalystInstanceImpl.java:254)
	at com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:48)
	at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:277)
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1422)
	at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1111)
	at java.lang.Thread.run(Thread.java:929)
Back traces ends.

**Comment by cmdparkour** [comment]
this is a online bug, and i use the react native in a hybrid app , the js engine i use more than one, maybe one page one engine.
