### ISSUE TITLE
[Android] App crash after codepush restart 

### ISSUE THREAD

**Issue by ddtien510** [microsoft/react-native-code-push#2513]
My app is crashing after codepush restart
I could reproduce that bug

Devices crashing on :
Galaxy A53 5G
Redmi 10 2022
Redmi 10C
Poco C40

Library versions :
React Native : 0.65.2
react-native-code-push : 7.0.4

Crash log:
Fatal Exception: java.lang.IllegalStateException: Trying to call native module before CatalystInstance has been set!
       at com.facebook.react.bridge.ReactContext.raiseCatalystInstanceMissingException(ReactContext.java:134)
       at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:177)
       at com.wix.reactnativeuilib.keyboardinput.utils.RuntimeUtils$1.run(RuntimeUtils.java:12)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:1012)

Can anyone help me. Thank you!

**Comment by shuraman69** [comment]
Any updates?

**Comment by DmitriyKirakosyan** [comment]
Hi @ddtien510 , based on your crash log it doesn't look related to the code-push library. Also the RN version 0.65 is out of support. Please upgrade to 0.69 or above if possible.

**Comment by Pushkar952** [comment]
We have similar issue. The app crashes post bundle is installed and app tried code push restart on android. 

The error log goes as this.
ActivityManager: Unable to start service Intent { act=android.service.smartspace.SmartspaceService cmp=com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiSmartspaceService } U=0: not found

**Comment by Felipe-Tomazetti** [comment]
I am having the same problem as @Pushkar952, cannot seem to solve it yet

**Comment by Namnp1521** [comment]
any update? i got this error on android device
```
"react": "18.1.0",
"react-native": "0.70.0",
"react-native-code-push": "^7.1.0",
```
