### ISSUE TITLE
New release - The asset cannot be uploaded

### ISSUE THREAD

**Issue by losheredos** [microsoft/react-native-code-push#2559]
I made an issue here already 
https://github.com/microsoft/appcenter-cli/issues/2411

### Steps to Reproduce
I just try to make a new build from
1. appcenter codepush release-react -a losheredos/aea-ios -d Staging
2. appcenter codepush release-react -a losheredos/aea-android -d Staging
3.
Both ways same issue.

### Expected Behavior
Release a new build as I did eralier

### Actual Behavior
What actually happens?
```
    appcenter-cli:commands:codepush:release-base Upload client message: Setting state: New (0) +4ms
  appcenter-cli:commands:codepush:release-base Upload client message: Upload Initialized +1ms
  appcenter-cli:commands:codepush:release-base Upload client message: Setting metadata for AssetId:  ad12fa32-070c-40b2-9394-36c2d947c97e +0ms
  appcenter-cli:commands:codepush:release-base Upload client message: File name: 2pkGtfB9rsavyDZ.zip +1ms
  appcenter-cli:commands:codepush:release-base Upload client message: File size: 8894269 +0ms
  appcenter-cli:commands:codepush:release-base Upload client message: CorrelationId: ad12fa32-070c-40b2-9394-36c2d947c97e +0ms
  appcenter-cli:commands:codepush:release-base Upload client message: ContentType: undefined +0ms
  appcenter-cli:commands:codepush:release-base Upload client message: Setting asset metadata on server +1ms
  appcenter-cli:commands:codepush:release-base Upload client message: Set metadata failed: AssetId: ad12fa32-070c-40b2-9394-36c2d947c97e, StatusCode: none, errorMessage: undefined +589ms
  appcenter-cli:commands:codepush:release-base Upload client message: Setting state: FatalError (500) +1ms
  appcenter-cli:commands:codepush:release-base Failed to release a CodePush update - Error: The asset cannot be uploaded. Try creating a new one
  appcenter-cli:commands:codepush:release-base     at fileUploadError (/opt/homebrew/lib/node_modules/appcenter-cli/node_modules/appcenter-file-upload-client/dist/core/file-upload-error.js:5:17)
  appcenter-cli:commands:codepush:release-base     at FileUploadClient.onMessage (/opt/homebrew/lib/node_modules/appcenter-cli/node_modules/appcenter-file-upload-client/dist/index.js:136:71)
  appcenter-cli:commands:codepush:release-base     at SingleThreadUploadController.FileUploadController.fatalError (/opt/homebrew/lib/node_modules/appcenter-cli/node_modules/appcenter-file-upload-client/dist/core/controller.js:75:29)
  appcenter-cli:commands:codepush:release-base     at Object.onError (/opt/homebrew/lib/node_modules/appcenter-cli/node_modules/appcenter-file-upload-client/dist/core/controller-requests/metadata.js:41:34)
  appcenter-cli:commands:codepush:release-base     at /opt/homebrew/lib/node_modules/appcenter-cli/node_modules/appcenter-file-upload-client/dist/core/request.js:40:32
  appcenter-cli:commands:codepush:release-base     at runMicrotasks (<anonymous>)
  appcenter-cli:commands:codepush:release-base     at processTicksAndRejections (internal/process/task_queues.js:95:5) +2ms
Error: Error: The asset cannot be uploaded. Try creating a new one

```
ConteType is undefined, maybe thats the issue?

### Environment

* react-native-code-push version: "https://github.com/johnf/react-native-code-push#rn-0.71"
* react-native version: "0.71.3",
* iOS/Android/Windows version: Ventura 13.1
* Does this reproduce on a debug build or release build? - Release

(The more info the faster we will be able to address it!)

**Comment by losheredos** [comment]
Looks like there is some issue 

https://status.appcenter.ms

**Comment by AnatolyPristensky** [comment]
Closing due to the absence of activity.
