### ISSUE TITLE
[ANDROID] : Crash and rollback after updating codepush version in App

### ISSUE THREAD

**Issue by Neeal20** [microsoft/react-native-code-push#2618]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Generate signed APK
2. Install it on device
3. Open the application
4. Install the code-push version proposed by the dialog
5. Then crash

### Expected Behavior
It was expected to not crash. Just restart the application or not but make the changes

### Actual Behavior
The app crash when updating the codepush version, then no changes / new bundle push by code-push
```java 
  STACK TRACE AND/OR SCREENSHOTS
2023-11-16 16:08:39.855 28447-28901 ReactNative             fr....enterprise.ecm.android.debug  D  [CodePush] Applying full update.
2023-11-16 16:08:39.862 28447-28592 ReactNative             fr....enterprise.ecm.android.debug  D  [CodePush] Loading JS bundle from "/data/user/0/fr.bouyguestelecom.ecm.android.debug/files/CodePush/3c54de8cc6d594aa49d85b1142f2984731cd2dab4a2d55c23671df78734c80b3/CodePush/index.android.bundle"
2023-11-16 16:08:39.862 28447-28592 ReactNative             fr....enterprise.ecm.android.debug  D  [CodePush] Restarting app
2023-11-16 16:08:39.864 28447-28592 ReactNative             fr....enterprise.ecm.android.debug  I  [GESTURE HANDLER] Tearing down gesture handler registered for root view com.facebook.react.ReactRootView{32311ca V.E...... ......ID 0,0-1080,2256}
2023-11-16 16:08:39.864 28447-28592 unknown:Re...JavaModule fr....enterprise.ecm.android.debug  E  Unhandled SoftException
                                                                                                    java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by DeviceInfo
                                                                                                    	at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:4)
                                                                                                    	at com.facebook.react.modules.deviceinfo.DeviceInfoModule.invalidate(DeviceInfoModule.java:2)
                                                                                                    	at com.facebook.react.bridge.ModuleHolder.destroy(ModuleHolder.java:2)
                                                                                                    	at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceDestroy(NativeModuleRegistry.java:4)
                                                                                                    	at com.facebook.react.bridge.CatalystInstanceImpl$1.run(CatalystInstanceImpl.java:1)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2023-11-16 16:08:39.865 28447-28592 AndroidRuntime          fr....guestelecom.ecm.android.debug  E  FATAL EXCEPTION: mqt_native_modules
                                                                                                    Process: fr.bouyguestelecom.ecm.android.debug, PID: 28447
                                                                                                    java.lang.InternalError: cannot instantiate DNSSDjava.lang.ClassNotFoundException: com.github.druk.dnssd.AppleDNSSD
                                                                                                    	at com.github.druk.dnssd.d.<clinit>(InternalDNSSD.java:3)
                                                                                                    	at com.github.druk.dnssd.a.<init>(DNSSD.java:5)
                                                                                                    	at com.github.druk.dnssd.a.<init>(DNSSD.java:1)
                                                                                                    	at com.github.druk.dnssd.b.<init>(DNSSDBindable.java:1)
                                                                                                    	at j9.d.<init>(Rx2DnssdBindable.java:1)
                                                                                                    	at y3.e.<init>(DnssdImpl.java:6)
                                                                                                    	at w3.a.a(ZeroConfImplFactory.java:3)
                                                                                                    	at w3.a.b(ZeroConfImplFactory.java:2)
                                                                                                    	at com.balthazargronon.RCTZeroconf.ZeroconfModule.getZeroconfImpl(ZeroconfModule.java:1)
                                                                                                    	at com.balthazargronon.RCTZeroconf.ZeroconfModule.stop(ZeroconfModule.java:1)
                                                                                                    	at com.balthazargronon.RCTZeroconf.ZeroconfModule.onCatalystInstanceDestroy(ZeroconfModule.java:3)
                                                                                                    	at com.facebook.react.bridge.BaseJavaModule.invalidate(BaseJavaModule.java:1)
                                                                                                    	at com.facebook.react.bridge.ModuleHolder.destroy(ModuleHolder.java:2)
                                                                                                    	at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceDestroy(NativeModuleRegistry.java:4)
                                                                                                    	at com.facebook.react.bridge.CatalystInstanceImpl$1.run(CatalystInstanceImpl.java:1)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```
### Environment

* react-native-code-push version: 7.0.2
* react-native": "0.68.x
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build?: Release
* Does this reproduce on a simulator, or only on a physical device? Physical Device

My Android Code-Push : 

settings.gradle : 
```
include ':app', ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')
```

android/app/build.gradle:
```
   resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())

    buildTypes {

        debug {
            applicationIdSuffix ".debug"
            signingConfig signingConfigs.debug
        }
        release {
            applicationIdSuffix ".debug"
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            resValue "string", "CodePushDeploymentKey", "MY_KEY"
        }
        production {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            matchingFallbacks = ['release']
            resValue "string", "CodePushDeploymentKey", "MY_KEY"
        }
        releaseStaging {
          resValue "string", "CodePushDeploymentKey", "MY_KEY"
          matchingFallbacks = ['release']
        }
    }

dependencies {
  implementation project(':react-native-code-push')
}
  

apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
```

android/MainApplication.java
```
import com.microsoft.codepush.react.CodePush;

          packages.add(new CodePush("MY_KEY", getApplicationContext(), BuildConfig.DEBUG));


     @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }
```

strings.xml
```
  <string name="appCenterCrashes_whenToSendCrashes" moduleConfig="true" translatable="false">DO_NOT_ASK_JAVASCRIPT</string>
  <string name="appCenterAnalytics_whenToEnableAnalytics" moduleConfig="true" translatable="false">ALWAYS_SEND</string>
```

index.tsx
```
AppRegistry.registerComponent(appName, () => () => <App partialAppContext={partialAppContext} />)

const codePushOptions = {
  checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME,
  installMode: CodePush.InstallMode.IMMEDIATE,
  updateDialog: false,
}

export default CodePush(codePushOptions)(App)
```

App.tsx
```
  useEffect(() => {
    CodePush.notifyAppReady()
    checkForUpdates()
  }, [])

  const checkForUpdates = async () => {
    const update = await CodePush.checkForUpdate()
    if (update) {
      CodePush.sync(
        {
          installMode: CodePush.InstallMode.IMMEDIATE,
          rollbackRetryOptions: {
            maxRetryAttempts: 2,
          },
        },
        codePushStatusDidChange,
      )
    }
  }

  const codePushStatusDidChange = (syncStatus) => {
    switch (syncStatus) {
      case CodePush.SyncStatus.CHECKING_FOR_UPDATE:
        console.log('Checking for update.')
        break
      case CodePush.SyncStatus.DOWNLOADING_PACKAGE:
        console.log('Download packaging....')
        break
      case CodePush.SyncStatus.AWAITING_USER_ACTION:
        console.log('Awaiting user action....')
        break
      case CodePush.SyncStatus.INSTALLING_UPDATE:
        console.log('Installing update')
        break
      case CodePush.SyncStatus.UP_TO_DATE:
        console.log('CodePush status up to date')
        break
      case CodePush.SyncStatus.UPDATE_IGNORED:
        console.log('update cancel by user')
        break
      case CodePush.SyncStatus.UPDATE_INSTALLED:
        console.log('Update installed and will be applied on restart.')
        break
      case CodePush.SyncStatus.UNKNOWN_ERROR:
        console.log('An unknown error occurred')
        break
    }
  }
App.displayName = 'App'

export default App
```

**Comment by Neeal20** [comment]
The problem seems to come from CodePush wrap of the application. I have tried to wrap it like this : 

"export default CodePush(codePushOptions)(App)" the application doesn't start. I have tried also to wrap it like a component inside my application : 

```js
    <CodePush>
      <ToasterProvider>
        <PrismeProvider partialAppContext={partialAppContext}>
          <AxiosProvider>
            <StoreProvider partialAppContext={partialAppContext}>
              <Booter>
                <ApolloProviderCustom>
                  <AppFlowProvider>
                    <NavigationContainer />
                  </AppFlowProvider>
                </ApolloProviderCustom>
              </Booter>
            </StoreProvider>
          </AxiosProvider>
        </PrismeProvider>
      </ToasterProvider>
    </CodePush>
  )
})
```

It doesn't work too. 

I don't have any solutions.. I tried on a new application in react native 0.72, having 0 issue, working perfectly

**Comment by Neeal20** [comment]
I founded the problem : 

I added this line to the `android/app/build.gradle` : 
```js
consumerProguardFiles("lib-proguard-rules.txt")
```

And this line to the `proguard-rules.pro` : 

# RxDNSSD
-keep class com.github.druk.dnssd.** {*;}

Fix the crash and make the application updating with the new bundle.

**Comment by iita71737** [comment]
> I founded the problem :
> 
> I added this line to the `android/app/build.gradle` :
> 
> ```js
> consumerProguardFiles("lib-proguard-rules.txt")
> ```
> 
> And this line to the `proguard-rules.pro` :
> 
> ```js
> # RxDNSSD
> -keep class com.github.druk.dnssd.** {*;}
> ```
> 
> Fix the crash and make the application updating with the new bundle.

Excuse me, 
I found the same issue on Android.
Which line should I added `proguard-rules.pro`  ?

**Comment by Laviniaxyz** [comment]
> > I founded the problem :
> > I added this line to the `android/app/build.gradle` :
> > ```js
> > consumerProguardFiles("lib-proguard-rules.txt")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And this line to the `proguard-rules.pro` :
> > ```js
> > # RxDNSSD
> > -keep class com.github.druk.dnssd.** {*;}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Fix the crash and make the application updating with the new bundle.
> 
> Excuse me, I found the same issue on Android. Which line should I added below code?
> 
> ```js
> consumerProguardFiles("lib-proguard-rules.txt")
> ```

You have to add it in
android {
    ...
    defaultConfig {
    ...
