### ISSUE TITLE
React Native 0.74 (Bridgeless) Support

### ISSUE THREAD

**Issue by oktaysenkan** [microsoft/react-native-code-push#2696]
Hello,

React Native is transitioning to bridgeless architecture with version 0.74. This architecture aims to improve performance and maintainability by removing the JavaScript bridge, which has traditionally been a bottleneck.

I am currently using your library `react-native-code-push` in my project. It's been incredibly useful, and I appreciate all the effort that goes into maintaining it. With the changes in React Native 0.74, it appears that the library may require updates to ensure full compatibility with the new architecture.

## Links

**[About the New Architecture](https://reactnative.dev/docs/next/the-new-architecture/landing-page)**
**[New Architecture working group](https://github.com/reactwg/react-native-new-architecture)**
**[Library support for New Architecture + Bridgeless in 2024](https://github.com/reactwg/react-native-new-architecture/discussions/167)**
**[Already migrated libs to take as an example](https://reactnative.dev/blog/2022/06/16/resources-migrating-your-react-native-library-to-the-new-architecture#migration-status-of-popular-libraries)**

**Comment by ramonxm** [comment]
Is anyone looking at this? @MikhailSuendukov

**Comment by lucen-ms** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.

**Comment by BenIrving** [comment]
@oktaysenkan fwiw, we have internally been able to apply minimal changes to the lib to get it operating for our use case (basic OTA updates) using the following patch. Please let me know if it works (or doesn't) for you and we can investigate further. 

[react-native-code-push-npm-8.2.1-f956f94445.patch](https://github.com/user-attachments/files/16845901/react-native-code-push-npm-8.2.1-f956f94445.patch)

**Comment by BenIrving** [comment]
@oktaysenkan fwiw we have managed to get codepush OTA updates working in bridgeless / interop mode on rn0.74.5 using the attached patch. It serves our use case of simple OTA updates, both forced and optional. Please let me know if it works for you, happy to investigate further if additional changes are required

[react-native-code-push-npm-8.3.1-9608679893.patch](https://github.com/user-attachments/files/16845925/react-native-code-push-npm-8.3.1-9608679893.patch)

**Comment by lenkaiser** [comment]
@lucen-ms Checking on this topic since I noticed you're contributor on the standalone codepush server as well. Can this change be part of the standalone repo? Is there a plan / vision how requests by the community can be made part of the standalone repo without having many forks?

**Comment by lucen-ms** [comment]
As we stated in the readme of the standalone version, we do not accept pull requests for features. We will only maintain security updates till March 31, 2025. Hence for adding features, we recommend implementing them in your fork. E.g. there is already a fork with AWS support.

**Comment by vir-skiplagged** [comment]
> [@oktaysenkan](https://github.com/oktaysenkan) fwiw we have managed to get codepush OTA updates working in bridgeless / interop mode on rn0.74.5 using the simple patch below. It serves our use case of simple OTA updates, both forced and optional. Please let me know if it works for you, happy to investigate further if additional changes are required
> 
> [react-native-code-push-npm-8.3.1-9608679893.patch](https://github.com/user-attachments/files/16846062/react-native-code-push-npm-8.3.1-9608679893.patch)

@BenIrving tried implementing your patch but I'm getting this error like the `invalidateCurrentInstance` is being called or the package isn't being added to the generated PackageList. I verified that the generated autolinking PackageList has this CodePush initialization in there. I'm on react-native 0.75.4 with react-native-code-push 8.3.1 with the new architecture enabled and bridgeless mode enabled. when bridgeless mode is disabled this error doesn't occur.

```
                                                                                                    E  Unhandled SoftException
                                                                                                    com.facebook.react.bridge.ReactNoCrashSoftException: raiseSoftException(getOrCreateDestroyTask()): handleHostException(message = "null")
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.raiseSoftException(SourceFile:0)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.getOrCreateDestroyTask(Unknown Source:5)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.lambda$destroy$7(Unknown Source:25)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.$r8$lambda$uso21_D6dCZdcf-JomVD56kdG4c(SourceFile:0)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl$$ExternalSyntheticLambda44.call(SourceFile:0)
                                                                                                    	at com.facebook.react.runtime.internal.bolts.Task$2.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at expo.modules.ReactNativeHostWrapperBase.invokeDelegateMethod$expo_release(Unknown Source:36)
                                                                                                    	at expo.modules.ReactNativeHostWrapperBase.getJSBundleFile(Unknown Source:27)
                                                                                                    	at expo.modules.ExpoReactHostFactory$ExpoReactHostDelegate.getJsBundleLoader(Unknown Source:17)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.lambda$getJsBundleLoader$26(Unknown Source:2)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.$r8$lambda$7mHFCl1T6X_2-pYKdhDvi-JqDUI(SourceFile:0)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl$$ExternalSyntheticLambda14.call(SourceFile:0)
                                                                                                    	at com.facebook.react.runtime.internal.bolts.Task$2.run(Unknown Source:4)
                                                                                                    	at com.facebook.react.runtime.internal.bolts.Executors$ImmediateExecutor.execute(Unknown Source:0)
                                                                                                    	at com.facebook.react.runtime.internal.bolts.Task.call(SourceFile:0)
                                                                                                    	at com.facebook.react.runtime.internal.bolts.Task.call(SourceFile:0)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.getJsBundleLoader(Unknown Source:34)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.lambda$getOrCreateReactInstanceTask$24(Unknown Source:13)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.$r8$lambda$bTI5MePZZsV3HRHvI1gYwNMIwCY(SourceFile:0)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl$$ExternalSyntheticLambda31.get(SourceFile:0)
                                                                                                    	at com.facebook.react.runtime.BridgelessAtomicRef.getOrCreate(Unknown Source:38)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.getOrCreateReactInstanceTask(Unknown Source:12)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.waitThenCallGetOrCreateReactInstanceTaskWithRetries(Unknown Source:64)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.waitThenCallGetOrCreateReactInstanceTask(Unknown Source:2)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.$r8$lambda$pQZAQOO5LKYIY0sOQYajWrj6-Rc(SourceFile:0)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl$$ExternalSyntheticLambda15.call(SourceFile:0)
                                                                                                    	... 4 more
                                                                                                    Caused by: com.microsoft.codepush.react.CodePushNotInitializedException: A CodePush instance has not been created yet. Have you added it to your app's list of ReactPackages?
                                                                                                    	at com.microsoft.codepush.react.CodePush.getJSBundleFile(SourceFile:0)
                                                                                                    	at com.microsoft.codepush.react.CodePush.getJSBundleFile(SourceFile:0)
                                                                                                    	at com.[company].MainApplication$reactNativeHost$1.getJSBundleFile(Unknown Source:0)
                                                                                                    	... 25 more
```

**Comment by FightFarewellFearless** [comment]
@vir-skiplagged have you found any solution?

**Comment by vir-skiplagged** [comment]
> [@vir-skiplagged](https://github.com/vir-skiplagged) have you found any solution?

haven't found a fix yet. are you running into the same issue?

**Comment by FightFarewellFearless** [comment]
> > [@vir-skiplagged](https://github.com/vir-skiplagged) have you found any solution?
> 
> [@FightFarewellFearless](https://github.com/FightFarewellFearless) haven't found a fix yet. are you running into the same issue?

Yes, same issue here running on react native 0.75.1

**Comment by vir-skiplagged** [comment]
> > > [@vir-skiplagged](https://github.com/vir-skiplagged) have you found any solution?
> > 
> > 
> > [@FightFarewellFearless](https://github.com/FightFarewellFearless) haven't found a fix yet. are you running into the same issue?
> 
> Yes, same issue here running on react native 0.75.1

@FightFarewellFearless I feel like the issue has something to do with the changes to autolinking but I've been trying a variety of things without success. if you figure it out let me know, I'll do the same. hopefully maybe someone else has solved this issue

**Comment by FightFarewellFearless** [comment]
Yes, sure, lemme try something in the next weekend

**Comment by vir-skiplagged** [comment]
@FightFarewellFearless just a bit of an update. I figured it out a bit but haven't solved the issue. So we're integrating expo modules into a bare react native project. From `MainApplication.kt` here https://docs.expo.dev/bare/installing-expo-modules/#configuration-for-android if you revert to the bare react native stuff for everything other than the `ApplicationLifecycleDispatcher` and `onConfigurationChanged` changes, it will build for me. digging in further

**Comment by FightFarewellFearless** [comment]
Oops, forgot to mention my project is already having expo modules integrated

**Comment by esbenvb** [comment]
> As we do not have plans to add support for this feature in the next year, I'm closing the issue.


Why is that? Since NA is enabled by default now, it's probably going to be the default of future apps. 

I'm not sure whether CodePush is considered dead or similar, but since MS has released a standalone server, we're no longer dependent on App Center, and can continue using Code Push after the end of App Center, as long as the client SDK supports the current React Native version.

I maintain plenty of apps for different customers, which all plans to keep using CodePush in the future, with the standalone server.

**Comment by DordeDimitrijev** [comment]
RNCP won't support NA please check https://github.com/microsoft/react-native-code-push/issues/2774#issuecomment-2507636494 for reference.

**Comment by DordeDimitrijev** [comment]
You could try out  approach mentioned in this comment to use new architecture https://github.com/microsoft/react-native-code-push/issues/2781#issuecomment-2519480160
