### ISSUE TITLE
A JS bundle file named "null" could not be found within the downloaded contents.

### ISSUE THREAD

**Issue by quany** [microsoft/react-native-code-push#2704]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
2024-06-03 15:02:40.284 11460-11519 ReactNative             com.rn74                             E  [CodePush] Exception
                                                                                                    com.microsoft.codepush.react.CodePushInvalidUpdateException: Update is invalid - A JS bundle file named "null" could not be found within the downloaded contents. Please check that you are releasing your CodePush updates using the exact same JS bundle file name that was shipped with your app's binary.
                                                                                                    	at com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage(CodePushUpdateManager.java:255)
                                                                                                    	at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:300)
                                                                                                    	at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:294)
                                                                                                    	at android.os.AsyncTask$3.call(AsyncTask.java:394)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1251)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:668)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2024-06-03 15:02:40.308 11460-11502 ReactNativeJS           com.rn74                             I  [CodePush] An unknown error occurred.
2024-06-03 15:02:40.308 11460-11502 ReactNativeJS           com.rn74                             I  [CodePush] Update is invalid - A JS bundle file named "null" could not be found within the downloaded contents. Please check that you are releasing your CodePush updates using the exact same JS bundle file name that was shipped with your app's binary.
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:8.2.2
* react-native version:0.74.1
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by DordeDimitrijev** [comment]
Hello @quany thank you for reporting this issue. You can find a possible solution for this problem here https://github.com/microsoft/react-native-code-push/issues/2083#issuecomment-1411745157 Please let me know if this resolves the issue.

**Comment by DmitriyKirakosyan** [comment]
Closing due to inactivity.
