### ISSUE TITLE
[CodePush] Error in getting binary resources modified time

### ISSUE THREAD

**Issue by SameedSymits** [microsoft/react-native-code-push#2736]
### Steps to Reproduce
1. react native : 0.68 version
2. update gradle to 7.5 
3. update android build tools classpath('com.android.tools.build:gradle:7.4.2')

### Expected Behavior
The resources should download completely

### Actual Behavior
But i am getting this error:

 [CodePush] Exception
com.microsoft.codepush.react.CodePushUnknownException: Error in getting binary resources modified time
at com.microsoft.codepush.react.CodePush.getBinaryResourcesModifiedTime(CodePush.java:207)
at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:289)
at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:284)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
at android.content.res.Resources.getText(Resources.java:462)
at android.content.res.Resources.getString(Resources.java:555)
at com.microsoft.codepush.react.CodePush.getBinaryResourcesModifiedTime(CodePush.java:204)
at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:289) 
at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:284) 
at android.os.AsyncTask$3.call(AsyncTask.java:394) 
at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
at java.lang.Thread.run(Thread.java:1012) 

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.68.5

**Comment by DordeDimitrijev** [comment]
Hi @SameedSymits  thank you for reaching out. This issue should be resolved with react-native-code-push 7.1.0. Please try updating to that version and let me know if helps out.

**Comment by SameedSymits** [comment]
Fixed. Thank you soo much @DordeDimitrijev

**Comment by DordeDimitrijev** [comment]
No problem, will be closing this thread now.
