### ISSUE TITLE
java.lang.VerifyError using latest version (v1.10.1-beta)

### ISSUE THREAD

**Issue by jamieathans** [Microsoft/react-native-code-push#286]
I just tried upgrading to v1.10.1-beta and now the app crashes on startup with the following:

*********************************
`637-31650/? I/dalvikvm: Could not find method android.webkit.CookieManager.setCookie, referenced from method com.facebook.react.modules.network.ForwardingCookieHandler.addCookieAsync
04-13 10:40:29.924 31637-31650/? I/dalvikvm: Could not find method android.webkit.CookieManager.removeAllCookies, referenced from method com.facebook.react.modules.network.ForwardingCookieHandler.clearCookiesAsync
04-13 10:40:29.924 31637-31650/? I/dalvikvm: Could not find method android.webkit.CookieManager.flush, referenced from method com.facebook.react.modules.network.ForwardingCookieHandler$CookieSaver.flush
04-13 10:40:29.929 31637-31650/? W/dalvikvm: VFY:  rejected Lcom/microsoft/codepush/react/CodePush$CodePushNativeModule;.loadBundle ()V
04-13 10:40:29.929 31637-31650/? W/dalvikvm: VFY:  rejected Lcom/microsoft/codepush/react/CodePush$CodePushNativeModule;.loadBundle ()V
04-13 10:40:29.929 31637-31650/? W/dalvikvm: Verifier rejected class Lcom/microsoft/codepush/react/CodePush$CodePushNativeModule;
04-13 10:40:29.934 31637-31650/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                   java.lang.RuntimeException: An error occured while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:299)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:239)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                       at java.lang.Thread.run(Thread.java:841)
                                                    Caused by: java.lang.VerifyError: com/microsoft/codepush/react/CodePush$CodePushNativeModule
                                                       at com.microsoft.codepush.react.CodePush.createNativeModules(CodePush.java:669)
                                                       at com.facebook.react.ReactInstanceManagerImpl.processPackage(ReactInstanceManagerImpl.java:894)
                                                       at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:822)
                                                       at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:104)
                                                       at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:200)
                                                       at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:183)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                                                       at java.lang.Thread.run(Thread.java:841)`
*********************************

Note that this does not happen on v1.10.0-beta and rolling back to this version resolves the issue.

This happens with the following Android specs:

Phone Model: Samsung Galaxy S3 (GT-I9305T)
Android version: 4.3

Interestingly, the error does not occur on a Nexus 5 running Android 4.4.4 or HTC One M8 running Android 6.0

**Comment by lostintangent** [comment]
Interesting! We hadn't seen this issue, but it's possible that we missed something specific to Android 4.3. I apologize about the inconvenience here. We'll investigate this ASAP in the morning and will try to figure out what is going on. Thanks for the patience!

**Comment by jjding1986** [comment]
also got this issue using 1.9.1-beta on HUAWEI G750-T00 running Android 4.2.2
and when using Nexus 6 running Android 6.0.1 everything is ok.
I just create a simple React Native project by 'react-native init AwesomeProject', and add code push function by 'npm install --save react-native-code-push'

**Comment by lostintangent** [comment]
@jjding1986 Did you mean 1.10.1-beta? I don't believe that we released a 1.9.1-beta version. It seems like we regressed pre-KitKat devices with 1.10.1-beta, so we'll investigate the bug and try to get a fix out ASAP.

**Comment by lostintangent** [comment]
@jamieathans Could you let me know how you were running the app when you had this error? Was it a debug or release build? If debug, did you have Chrome debugging enabled? From looking into the issue briefly, it looks like it should only occur in debug builds on a pre Android 4.4 device. We'll try to narrow this down, but it would be awesome to know if you get this issue in a release build.

**Comment by lostintangent** [comment]
This was just resolved by #288, so if you want to grab the latest bits from GitHub, you should be able to run the latest CodePush plugin on pre-KitKat Android devices. We'll ship this to NPM tomorrow. Thanks for reporting this issue!
