### ISSUE TITLE
[Android] NullPointerException in CodePushUtils

### ISSUE THREAD

**Issue by dhrrgn** [Microsoft/react-native-code-push#309]
Seeing a a good number of crash reports from CodePushUtils.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tackk.squad/com.tackk.squad.MainActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
       at android.app.ActivityThread.access$900(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5694)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at com.microsoft.codepush.react.CodePushUtils.tryGetString(CodePushUtils.java:219)
       at com.microsoft.codepush.react.CodePushPackage.getCurrentPackageBundlePath(CodePushPackage.java:104)
       at com.microsoft.codepush.react.CodePush.getBundleUrlInternal(CodePush.java:150)
       at com.microsoft.codepush.react.CodePush.getBundleUrl(CodePush.java:141)
       at com.microsoft.codepush.react.CodePush.getBundleUrl(CodePush.java:133)
       at com.tackk.squad.MainActivity.getJSBundleFile(MainActivity.java:53)
       at com.facebook.react.ReactActivity.createReactInstanceManager(ReactActivity.java:108)
       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:140)
       at android.app.Activity.performCreate(Activity.java:5541)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
       at android.app.ActivityThread.access$900(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5694)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by lostintangent** [comment]
@dhrrgn Investigating right now. Are you able to repro this by any chance? Or do your crash reports indicate what the user was doing? (e.g. was this a fresh install? did they just update from the store) I can see where the NullPointerException would happen, but I'm not sure how the app would get into the state necessary to hit it.

Thanks so much for the extremely helpful stack! We'll try to get out a fix today.

**Comment by dhrrgn** [comment]
@lostintangent I cannot reproduce this.  I can't see any information as to what the user was doing.  However, I am seeing that 9 users have had this happen 44 times.  So, I assume that it is not a first-launch type issue...unless those users keep re-installing...which is highly unlikely.

**Comment by lostintangent** [comment]
@dhrrgn OK cool, that is helpful to know. Thanks so much and stay tuned for a fix.

**Comment by lostintangent** [comment]
Doh! I didn't mean for this to auto-close this bug. Either way, this has been resolved via the linked PR, and I'll release the update to NPM tonight. Thanks again for letting us know about this issue, and apologies for the two exceptions!
