### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by L-Jovi** [Microsoft/react-native-code-push#317]
I follow the tutorial step and finish all configuration, but I always find the error when I build the application,

react-native version: `0.21`

code-push version: `1.8.0-beta`

by the way, I'm confused that whether I'll add `main.jsbundle` to project manually after executed
```
react bundle --platfrom ios --dev false --entry-file index.ios.js --bundle-output bundles/main.jsbundle

code-push release Demo bundles/main.jsbundle 0.0.1 --mandatory false
```

thanks for your time.

---

__error log from xcode__

```
+ DEST=/Users/mengwenqiaoxindongcom/Library/Developer/Xcode/DerivedData/CodePushDemoApp-daskyeoxgnwatbbfvygzfhycsbfn/Build/Products/Debug-iphonesimulator/CodePushDemoApp.app
+ node /Users/mengwenqiaoxindongcom/pra/javascript/react-full_stack/react-native/0.24/react-native-code-push/Examples/CodePushDemoApp/node_modules/react-native/local-cli/cli.js bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/mengwenqiaoxindongcom/Library/Developer/Xcode/DerivedData/CodePushDemoApp-daskyeoxgnwatbbfvygzfhycsbfn/Build/Products/Debug-iphonesimulator/CodePushDemoApp.app/main.jsbundle --assets-dest /Users/mengwenqiaoxindongcom/Library/Developer/Xcode/DerivedData/CodePushDemoApp-daskyeoxgnwatbbfvygzfhycsbfn/Build/Products/Debug-iphonesimulator/CodePushDemoApp.app
bundle: Created ReactPackager
uncaught error Error: Error: Uncaught error in the transformer worker: /Users/mengwenqiaoxindongcom/pra/javascript/react-full_stack/react-native/0.24/react-native-code-push/Examples/CodePushDemoApp/node_modules/react-native/packager/transformer.js
    at index.js:164:37
    at tryCallOne (/Users/mengwenqiaoxindongcom/pra/javascript/react-full_stack/react-native/0.24/react-native-code-push/Examples/CodePushDemoApp/node_modules/promise/lib/core.js:37:12)
    at /Users/mengwenqiaoxindongcom/pra/javascript/react-full_stack/react-native/0.24/react-native-code-push/Examples/CodePushDemoApp/node_modules/promise/lib/core.js:123:15
    at flush (/Users/mengwenqiaoxindongcom/pra/javascript/react-full_stack/react-native/0.24/react-native-code-push/Examples/CodePushDemoApp/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
See logs /var/folders/ym/9kftgsm13435827mg4j0lylr0000gn/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:144:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/mengwenqiaoxindongcom/pra/javascript/react-full_stack/react-native/0.24/react-native-code-push/Examples/CodePushDemoApp/node_modules/bser/index.js:289:10)
    at /Users/mengwenqiaoxindongcom/pra/javascript/react-full_stack/react-native/0.24/react-native-code-push/Examples/CodePushDemoApp/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
Command /bin/sh failed with exit code 1
```

**Comment by lostintangent** [comment]
@L-Jovi Could you try restarting the packager and also running `rm -rf $TEMP/react-*`? Additionally, did you recently upgrade you React Native version, without running `react-native upgrade`? If you remove CodePush from your project do you still get this error? It doesn't seem like a CodePush issue on the surface, but I'd love to try to determine if it is.

**Comment by L-Jovi** [comment]
@lostintangent  thanks for your reply, I eventually ensure it's react native version cause issue.

**Comment by anthonywebb** [comment]
@L-Jovi but how did you fix it?  I have the same issue.

**Comment by L-Jovi** [comment]
@anthonywebb  you could try to remove __Bundle React Native code and images__ of __Build Phases__ in Xcode to prevent that shell script execute.
