### ISSUE TITLE
[Android] crashes on release with react native being build from source

### ISSUE THREAD

**Issue by chirag04** [Microsoft/react-native-code-push#388]
Crash log:

```
06-20 18:29:51.183 27092-27092/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.qsi, PID: 27092
                                                   java.lang.UnsatisfiedLinkError: could find DSO to load: libreactnativejni.so
                                                       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:213)
                                                       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:178)
                                                       at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:31)
                                                       at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:41)
                                                       at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
                                                       at com.microsoft.codepush.react.CodePushPackage.getCurrentPackageInfo(CodePushPackage.java:68)
                                                       at com.microsoft.codepush.react.CodePushPackage.getCurrentPackageFolderPath(CodePushPackage.java:89)
                                                       at com.microsoft.codepush.react.CodePushPackage.getCurrentPackageBundlePath(CodePushPackage.java:99)
                                                       at com.microsoft.codepush.react.CodePush.getBundleUrlInternal(CodePush.java:161)
                                                       at com.microsoft.codepush.react.CodePush.getBundleUrl(CodePush.java:152)
                                                       at com.microsoft.codepush.react.CodePush.getBundleUrl(CodePush.java:144)
                                                       at com.qsi.MainActivity.getJSBundleFile(MainActivity.java:32)
                                                       at com.facebook.react.ReactActivity.createReactInstanceManager(ReactActivity.java:109)
                                                       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:141)
                                                       at android.app.Activity.performCreate(Activity.java:6251)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

``` 
// app.gradle
compile(project(':react-native-code-push')) {
        exclude group: 'com.facebook.react', module: 'react-native'
    }
```

**Comment by lostintangent** [comment]
Do you get this error when the app is restarted after installing a CodePush update?

**Comment by chirag04** [comment]
app works fine in dev mode. in release mode it crashes immediately even before the initial screen is displayed.

**Comment by lostintangent** [comment]
Hmm, everything is working great for me using RN 0.28 RC. Are you running the RN bits from master? If so, it's possible that there was a breaking change that we haven't seen yet.

**Comment by chirag04** [comment]
yeah i'm using RN bits from master. There was something broken between 28 and master i guess. I updated to a more recent version of RN and it works fine now.

Couldn't update to master break of this breaking change: https://github.com/facebook/react-native/commit/49f20f41546e3ba8e7fe43c84c4c701684d0434d. That would be a breaking change for code-push also i suppose.

Thanks for the help. Keep up the amazing work 👍

**Comment by lostintangent** [comment]
Awesome, thanks so much for confirming that. Yeah, I actually just noticed that commit earlier and also noticed your comment :) We'll definitely need to figure out how to respond to that change, since we currently require a reference to the Activity.

**Comment by chirag04** [comment]
@lostintangent https://github.com/facebook/react-native/commit/49f20f41546e3ba8e7fe43c84c4c701684d0434d#commitcomment-18003386

Can we update code-push to match that ^

**Comment by lostintangent** [comment]
@chirag04 We're making that change right now :) We should have an RN 0.29 compatible release out by early next week.

**Comment by chirag04** [comment]
awesome
