### ISSUE TITLE
[Android] Crash on sync

### ISSUE THREAD

**Issue by rilyu** [Microsoft/react-native-code-push#440]
I press Home key to sent app to background when codePush.sync running, the app will crash sometimes, error message in logcat:

```
java.lang.NullPointerException
   at android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:143)
   at android.app.AlertDialog$Builder.<init>(AlertDialog.java:360)
   at com.microsoft.codepush.react.CodePushDialog.showDialog(CodePushDialog.java:21)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
   at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
   at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
   at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:432)
   at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
   at android.os.Handler.handleCallback(Handler.java:733)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
   at android.os.Looper.loop(Looper.java:136)
   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:193)
   at java.lang.Thread.run(Thread.java:841)
```

source code:
`codePush.sync({installMode: codePush.InstallMode.IMMEDIATE, updateDialog: true});
`

**Comment by geof90** [comment]
This should be caused by `getCurrentActivity()` returning null when the app is backgrounded. Should be a simple fix, I will get this out by today.
