### ISSUE TITLE
[Android]NullPointerException

### ISSUE THREAD

**Issue by lekenny** [Microsoft/react-native-code-push#458]
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference

	at android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:154)
	at android.app.AlertDialog$Builder.<init>(AlertDialog.java:379)
	at com.microsoft.codepush.react.CodePushDialog.showDialog(CodePushDialog.java:21)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
	at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
	at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
	at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:432)
	at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:135)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
	at java.lang.Thread.run(Thread.java:818)`

**Comment by geof90** [comment]
Which version of `react-native-code-push` are you using?

**Comment by silhouettes** [comment]
@lekenny, did you still need help with this?
