### ISSUE TITLE
error when linking code push

### ISSUE THREAD

**Issue by vincentlkl** [Microsoft/react-native-code-push#484]
I am on 
react-native -v 0.31.0

when I run
$ react-native link react-native-code-push

I am getting error
`
module.js:339
    throw err;
    ^

Error: Cannot find module "glob"
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/vincent/work/ror/museprojects/ab_survey_app/react native/ABSurveyApp/node_modules/react-native-code-push/scripts/postlink/ios/postlink.js:2:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
/Users/vincent/work/ror/museprojects/ab_survey_app/react native/ABSurveyApp/node_modules/react-native/local-cli/rnpm/core/src/makeCommand.js:19
        throw new Error("Error occured during executing "${ command }" command");
        ^

Error: Error occured during executing "node node_modules/react-native-code-push/scripts/postlink/run" command
    at ChildProcess.prelink (makeCommand.js:19:15)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
`

Did I miss out anything from it?

**Comment by geof90** [comment]
Hmm. What version of NPM are you using? `npm -v`

**Comment by geof90** [comment]
[I assumed `glob` should be there as brought in by a dependency of React Native](https://github.com/facebook/react-native/blob/master/package.json#L156). I guess we might have to take a direct dependency on it

**Comment by vincentlkl** [comment]
My npm version is 2.14.7

**Comment by vincentlkl** [comment]
thanks @geof90 , it is working now.
