### ISSUE TITLE
Android crash after any update:  Attempt to invoke virtual method 'java.util.Iterator org.json.JSONObject.keys()' on a null object reference

### ISSUE THREAD

**Issue by jerson** [Microsoft/react-native-code-push#520]
Using React Native v0.34-rc
Using React Native Code Push 1.14.6-beta

This crash happens whenever a new version is deployed to CodePush and the app finishes the update. The app seems to successfully update itself, but it crashes after the update. The app works as intended after relaunching.
 similar to #515

```
09-18 23:50:33.881   833  1033 D AudioService: Stream muted, skip playback
09-18 23:50:33.925 20648 20648 D AudioPlayerModule: onHostResume
09-18 23:50:33.959 20648 20648 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.setbeat.music.staging/files/CodePush/56f364d115d2d57af414323a839517e2264cae4eebb2825658acab4a3cf8020e/CodePush/index.android.bundle"
09-18 23:50:34.015 20648 20648 D AudioPlayerModule: onHostPause
09-18 23:50:34.021 20648 20648 D AudioPlayerModule: onHostDestroy
09-18 23:50:34.034 20648 20648 W PhoneWindow: Previously focused view reported id 10 during save, but can't be found during restore.
09-18 23:50:34.034 20648 20648 D AudioPlayerModule: onHostResume
09-18 23:50:34.069 20648 20648 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.setbeat.music.staging/files/CodePush/56f364d115d2d57af414323a839517e2264cae4eebb2825658acab4a3cf8020e/CodePush/index.android.bundle"
09-18 23:50:34.095 20648 20648 D AudioPlayerModule: onHostPause
09-18 23:50:34.119 20648 20648 D AudioPlayerModule: onHostDestroy
09-18 23:50:34.126 20648 20648 D AudioPlayerModule: onHostResume
09-18 23:50:34.154 20648 20648 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.setbeat.music.staging/files/CodePush/56f364d115d2d57af414323a839517e2264cae4eebb2825658acab4a3cf8020e/CodePush/index.android.bundle"
09-18 23:50:34.173 20648 20648 D AudioPlayerModule: onHostPause
09-18 23:50:34.182 20648 20715 I ReactNativeJS: Running application "Setbeat" with appParams: {"initialProps":{},"rootTag":11}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
09-18 23:50:34.200 20648 20648 D AudioPlayerModule: onHostDestroy
09-18 23:50:34.210 20648 20648 D AudioPlayerModule: onHostResume
09-18 23:50:34.237 20648 20648 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.setbeat.music.staging/files/CodePush/56f364d115d2d57af414323a839517e2264cae4eebb2825658acab4a3cf8020e/CodePush/index.android.bundle"
09-18 23:50:34.262 20648 20648 D AudioPlayerModule: onHostPause
09-18 23:50:34.282 20648 20648 D AudioPlayerModule: onHostDestroy
09-18 23:50:34.291 20648 20648 D AudioPlayerModule: onHostResume
09-18 23:50:34.323 20648 20648 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.setbeat.music.staging/files/CodePush/56f364d115d2d57af414323a839517e2264cae4eebb2825658acab4a3cf8020e/CodePush/index.android.bundle"
09-18 23:50:34.344 20648 20648 D AudioPlayerModule: onHostPause
09-18 23:50:34.365 20648 20648 D AudioPlayerModule: onHostDestroy
09-18 23:50:34.375 20648 20648 D AudioPlayerModule: onHostResume
09-18 23:50:34.421 20648 20648 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.setbeat.music.staging/files/CodePush/56f364d115d2d57af414323a839517e2264cae4eebb2825658acab4a3cf8020e/CodePush/index.android.bundle"
09-18 23:50:34.447 20648 20648 D AudioPlayerModule: onHostPause
09-18 23:50:34.478 20648 20648 D AudioPlayerModule: onHostDestroy
09-18 23:50:34.490 20648 20648 D AudioPlayerModule: onHostResume
09-18 23:50:34.490 20648 20674 I art     : Background sticky concurrent mark sweep GC freed 48647(3MB) AllocSpace objects, 45(900KB) LOS objects, 16% free, 17MB/20MB, paused 9.502ms total 112.667ms
09-18 23:50:34.519 20648 20648 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.setbeat.music.staging/files/CodePush/56f364d115d2d57af414323a839517e2264cae4eebb2825658acab4a3cf8020e/CodePush/index.android.bundle"
09-18 23:50:34.539 20648 20648 D AudioPlayerModule: onHostPause
09-18 23:50:34.568 20648 20648 D AudioPlayerModule: onHostDestroy
09-18 23:50:34.574 20648 20715 I ReactNativeJS: Running application "Setbeat" with appParams: {"initialProps":{},"rootTag":21}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
09-18 23:50:34.583 20648 20648 D AudioPlayerModule: onHostResume
09-18 23:50:34.590 20648 20715 I ReactNativeJS: Running application "Setbeat" with appParams: {"initialProps":{},"rootTag":31}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
09-18 23:50:34.614 20648 20648 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.setbeat.music.staging/files/CodePush/56f364d115d2d57af414323a839517e2264cae4eebb2825658acab4a3cf8020e/CodePush/index.android.bundle"
09-18 23:50:34.686 20648 20715 I ReactNativeJS: Running application "Setbeat" with appParams: {"initialProps":{},"rootTag":41}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
09-18 23:50:34.706 20648 20698 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
09-18 23:50:34.706 20648 20698 E AndroidRuntime: Process: com.setbeat.music.staging, PID: 20648
09-18 23:50:34.706 20648 20698 E AndroidRuntime: Theme: themes:{}
09-18 23:50:34.706 20648 20698 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
09-18 23:50:34.706 20648 20698 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
09-18 23:50:34.706 20648 20698 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
09-18 23:50:34.706 20648 20698 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
09-18 23:50:34.706 20648 20698 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
09-18 23:50:34.706 20648 20698 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-18 23:50:34.706 20648 20698 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-18 23:50:34.706 20648 20698 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-18 23:50:34.706 20648 20698 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
09-18 23:50:34.706 20648 20698 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator org.json.JSONObject.keys()' on a null object reference
09-18 23:50:34.706 20648 20698 E AndroidRuntime: 	at com.microsoft.codepush.react.CodePushUtils.convertJsonObjectToWritable(CodePushUtils.java:65)
09-18 23:50:34.706 20648 20698 E AndroidRuntime: 	at com.microsoft.codepush.react.CodePushNativeModule$4.doInBackground(CodePushNativeModule.java:307)
09-18 23:50:34.706 20648 20698 E AndroidRuntime: 	at com.microsoft.codepush.react.CodePushNativeModule$4.doInBackground(CodePushNativeModule.java:283)
09-18 23:50:34.706 20648 20698 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-18 23:50:34.706 20648 20698 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-18 23:50:34.706 20648 20698 E AndroidRuntime: 	... 4 more
09-18 23:50:34.718   833  1792 W ActivityManager:   Force finishing activity com.setbeat.music.staging/com.setbeat.music.MainActivity
```

**Comment by silhouettes** [comment]
Closing this so that we can use #515 to track it
