### ISSUE TITLE
NullPointerException on downloading an update

### ISSUE THREAD

**Issue by MattDavies** [Microsoft/react-native-code-push#531]
Had this crash report come in which looks like an issue in the latest code-push.

```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:299)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
       at java.util.concurrent.FutureTask.run(FutureTask.java:239)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.lang.NullPointerException
       at com.microsoft.codepush.react.CodePushUtils.convertJsonObjectToWritable(CodePushUtils.java:65)
       at com.microsoft.codepush.react.CodePushNativeModule$4.doInBackground(CodePushNativeModule.java:307)
       at com.microsoft.codepush.react.CodePushNativeModule$4.doInBackground(CodePushNativeModule.java:283)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
```

Sorry for the limited detail, this just came in from an automated crash report. I'll try to contact the user and get more information.

* react-native-code-push version: 1.14.6-beta
* react-native version: 0.30.0
* iOS/Android version: 6.0.1
* Does this repro on a simulator, or only on a physical device? Physical device

**Comment by silhouettes** [comment]
This looks to be the same as #515, so I'm going to close this so that we can track it there. Thanks for filing this - based on your description, it seems like it's not a problem with RN 0.33, but with react-native-code-push 1.14.6-beta.
