### ISSUE TITLE
Error during react native link if already installed

### ISSUE THREAD

**Issue by StevePotter** [Microsoft/react-native-code-push#539]
Latest react-native, react-native-code-push, latest OSX.

When I run 'react-native link react-native-code-push' I get

rnpm-install info Android module react-native-code-push is already linked 
rnpm-install info iOS module react-native-code-push is already linked 
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/Users/stephen/Dropbox/VydiaDev/vydiaMobileTemp/node_modules/react-native-code-push/scripts/postlink/ios/postlink.js:13:24)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
/Users/stephen/Dropbox/VydiaDev/vydiaMobileTemp/node_modules/react-native/local-cli/core/makeCommand.js:19
        throw new Error(`Error occured during executing "${ command }" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-code-push/scripts/postlink/run" command
    at ChildProcess.prelink (/Users/stephen/Dropbox/VydiaDev/vydiaMobileTemp/node_modules/react-native/local-cli/core/makeCommand.js:19:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by silhouettes** [comment]
Now that I look at it, this actually seems to be the same as #534 - I'll close this one too so that we can track it there.
