### ISSUE TITLE
npm start failed 

### ISSUE THREAD

**Issue by uyson** [Microsoft/react-native-code-push#568]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):
- react-native-code-push version: 0.15
- react-native version: 0.35.0
- iOS/Android/Windows version: android 4.2.2
- Does this reproduce on a debug build or release build: debug
- Does this reproduce on a simulator, or only on a physical device: physical device
- Repro steps and/or stack trace

error info : 

```
 ERROR  watch /home/alim/projects/tvreste/app-v2/node_modules/react-native-code-push/android/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.1/res/values-et-rEE ENOSPC
{"code":"ENOSPC","errno":"ENOSPC","syscall":"watch /home/alim/projects/tvreste/app-v2/node_modules/react-native-code-push/android/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.1/res/values-et-rEE","filename":"/home/alim/projects/tvreste/app-v2/node_modules/react-native-code-push/android/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.1/res/values-et-rEE"}
Error: watch /home/alim/projects/tvreste/app-v2/node_modules/react-native-code-push/android/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.0.1/res/values-et-rEE ENOSPC
    at exports._errnoException (util.js:1036:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at NodeWatcher.watchdir (/home/alim/projects/tvreste/app-v2/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/home/alim/projects/tvreste/app-v2/node_modules/sane/src/node_watcher.js:353:12)
    at emitTwo (events.js:106:13)
    at Walker.emit (events.js:191:7)
    at /home/alim/projects/tvreste/app-v2/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/alim/projects/tvreste/app-v2/node_modules/graceful-fs/graceful-fs.js:149:14)
    at go$readdir$cb (/home/alim/projects/tvreste/app-v2/node_modules/graceful-fs/graceful-fs.js:149:14)

```

**Comment by silhouettes** [comment]
Sorry, what were the steps you took to make this error happen?

**Comment by uyson** [comment]
不好意思， 我都忘了什么时候出的错误，
