### ISSUE TITLE
React Native 0.36 and 0.37 Support

### ISSUE THREAD

**Issue by silhouettes** [Microsoft/react-native-code-push#582]
- react-native-code-push version: 1.15.0-beta
- react-native version: 0.36.0/0.37.0

RN 0.36.0 has not been officially tested against CodePush yet, but we will verify this within the next two days. If you have tested this and run into specific issues, please post them here! In the meantime, RN 0.35 has been verified against CodePush.

**Comment by brettpappas** [comment]
everything is working for me using 0.36 and 1.15.0-beta

**Comment by ericnograles** [comment]
Working nicely using 0.36 and 1.15.0-beta for me as well!

**Comment by vonovak** [comment]
btw [rn-diff](https://github.com/ncuillery/rn-diff/compare/rn-0.35.0...rn-0.36.0) repo might help figuring out whether something got broken

**Comment by silhouettes** [comment]
I was able to verify that everything is working smoothly on RN 0.36, with the exception of specifically immediate restarts, on Android specifically. Most of our users are not using this method to install their updates, but if anybody is urgently in need of this, please upvote/comment and I will prioritize accordingly!

**Comment by jerson** [comment]
immediate restarts  on Android  :(

**Comment by tomauty** [comment]
Yes please. What's the recommended 'next best thing' to immediate restarts for mandatory updates?

**Comment by EladPlayground** [comment]
I can confirm that IMMEDIATE and ON_NEXT_RESUME mandatory installation crashes. Any suggestions?

**Comment by silhouettes** [comment]
Basically, something has changed in React Native that has caused the mechanism we use to restart/re-construct the app to crash (hence why it only affects `IMMEDIATE`/`ON_NEXT_RESUME`). I am investigating it now, but if anyone has any pointers that would also be really appreciated! This is the stack trace, it seems like the old instance of the app is not cleanly destroyed.

```
W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {ca8f682} sending message to a Handler on a dead thread
                java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {ca8f682} sending message to a Handler on a dead thread
                    at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                    at android.os.Handler.enqueueMessage(Handler.java:643)
                    at android.os.Handler.sendMessageAtTime(Handler.java:612)
                    at android.os.Handler.sendMessageDelayed(Handler.java:582)
                    at android.os.Handler.post(Handler.java:338)
                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                    at android.os.Handler.handleCallback(Handler.java:751)
                    at android.os.Handler.dispatchMessage(Handler.java:95)
                    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                    at android.os.Looper.loop(Looper.java:154)
                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                    at java.lang.Thread.run(Thread.java:761)
W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {ca8f682} sending message to a Handler on a dead thread
                java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {ca8f682} sending message to a Handler on a dead thread
                    at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                    at android.os.Handler.enqueueMessage(Handler.java:643)
                    at android.os.Handler.sendMessageAtTime(Handler.java:612)
                    at android.os.Handler.sendMessageDelayed(Handler.java:582)
                    at android.os.Handler.post(Handler.java:338)
                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                    at android.os.Handler.handleCallback(Handler.java:751)
                    at android.os.Handler.dispatchMessage(Handler.java:95)
                    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                    at android.os.Looper.loop(Looper.java:154)
                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                    at java.lang.Thread.run(Thread.java:761)
```

**Comment by silhouettes** [comment]
It seems like the `onHostResume()` event on React's `LifeCycleEventListener` has been modified to fire immediately when added if the app is in the foreground, rather than waiting for it to be backgrounded and then resumed. This has caused a few downstream effects which I'm still investigating.

**Comment by benedicthsieh** [comment]
So I believe that as a result of this bug, any deployment that has a mandatory upgrade anywhere in its history will now crash starting from a clean install, is that correct? That's what we're seeing with our deployment. I'm guessing it's because even after we pushed a non-mandatory upgrade to 'hide' the mandatory one, the upgrade itself will still happen with mandatory behavior (due to the behavior specced under 'Mandatory Parameter' here: https://microsoft.github.io/code-push/docs/cli.html#link-10.

Can we fix our codepush production deployment by clearing history `code-push deployment clear`? The docs say not to do this in a production environment, but I'm not sure what else we could do.

**Comment by silhouettes** [comment]
Hi @benedicthsieh - my sincere apologies, we will have a fix for RN 0.36 and 0.37 out today or tomorrow. In the mean-time, I think the best way would be to [patch the offending release using the `code-push patch` command](https://github.com/Microsoft/code-push/tree/master/cli#patching-update-metadata)`.

**Comment by benedicthsieh** [comment]
Patching the mandatory flag out of our history worked, thanks for the tip!

**Comment by silhouettes** [comment]
I was able to fix the crash and rollback (originally caused by our resume handler being triggered twice due to a change in RN's `LifeCycleEventManager`).

Separately, I was not able to prevent the following warning being logged to the console when run in debug mode. It is coming from somewhere in React Native, but I'm unable to pinpoint exactly which object is attempting to queue the `Runnable`, as the behavior changes when breakpoints are set.

However as far as I can see, the warning is completely benign - it will be logged to the console anywhere from 0-2 times on restart, and seems to depend on the order in which React Native objects are re-initialized. Other than that, there seems to be no ill effects.

```
W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {ca8f682} sending message to a Handler on a dead thread
                java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {ca8f682} sending message to a Handler on a dead thread
                    at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                    at android.os.Handler.enqueueMessage(Handler.java:643)
                    at android.os.Handler.sendMessageAtTime(Handler.java:612)
                    at android.os.Handler.sendMessageDelayed(Handler.java:582)
                    at android.os.Handler.post(Handler.java:338)
                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                    at android.os.Handler.handleCallback(Handler.java:751)
                    at android.os.Handler.dispatchMessage(Handler.java:95)
                    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                    at android.os.Looper.loop(Looper.java:154)
                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                    at java.lang.Thread.run(Thread.java:761)
```

**Comment by silhouettes** [comment]
I have released the fix to `react-native-code-push@1.16.0-beta` ([release notes](https://github.com/Microsoft/react-native-code-push/releases/tag/v1.16.0-beta)). Please feel free to use RN 36 and 37!

In future we will endeavor to ensure compatibility earlier in the cycle, including verifying React Native 0.38.0 before it comes out next week.

Please let us know if you have any feedback!

**Comment by silhouettes** [comment]
@jerson, @codyhazelwood, @tomauty, @ivpusic, @EladPlayground, @benedicthsieh

**Comment by burgalon** [comment]
@silhouettes I'm experiencing this exception when calling `codePush.appRestart()` manually, with RN 0.39.2 and react-native-code-push `1.17.0-beta`

**Comment by silhouettes** [comment]
HI @burgalon, that is a warning rather than an exception, and it seems to be benign. Basically, when the app restarts, there may be some messages left in the queue targeting the old React Native instance. These messages will be dropped, but that's okay because that's what we want (we're rebooting the app from scratch).

**Comment by beansoftapp** [comment]
I've found an problem which causes this exception, eg my React JS used a customized native component, however this native component doesn't added to the ReactInstanceManager.Builder by method addPackage, then this problem will occur.
