### ISSUE TITLE
react-native link code-push make mistake

### ISSUE THREAD

**Issue by fanyuRN** [Microsoft/react-native-code-push#586]
rnpm-install info Android module react-native-code-push is already linked 
rnpm-install info iOS module react-native-code-push is already linked 
/Users/fanyu/workspace/tc-intervacation-app/aggron/node_modules/react-native-code-push/scripts/postlink/ios/postlink.js:26
var oldJsCodeLocationAssignmentStatement = appDelegateContents.match(/(jsCodeLocation = .*)\n/)[1];
                                                                                               ^

TypeError: Cannot read property '1' of null
    at Object.<anonymous> (/Users/fanyu/workspace/tc-intervacation-app/aggron/node_modules/react-native-code-push/scripts/postlink/ios/postlink.js:26:96)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/fanyu/workspace/tc-intervacation-app/aggron/node_modules/react-native-code-push/scripts/postlink/run.js:1:63)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
/Users/fanyu/workspace/tc-intervacation-app/aggron/node_modules/react-native/local-cli/core/makeCommand.js:19
        throw new Error(`Error occured during executing "${ command }" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-code-push/scripts/postlink/run" command
    at ChildProcess.prelink (/Users/fanyu/workspace/tc-intervacation-app/aggron/node_modules/react-native/local-cli/core/makeCommand.js:19:15)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

react-native-code-push version is ^1.14.6-beta;react-native version is 0.35.0,thank you!

**Comment by yimingtang** [comment]
The same.

I'd like to say the `link` command is so buggy that I have to integrate Code Push myself manually again. I should have done it manually from the beginning if I had realized that your script was broken 😢

**Comment by gouravsood** [comment]
@fanyuRN was there any resolution identified for this issue? @thiagoterleski and myself both had the same issue and were referred to this issue.

Can you please suggest and help here?

**Comment by fanyuRN** [comment]
@gouravsood  oh, I forget  the resolution, maybe you can upgrade your code-push version
