### ISSUE TITLE
App perpetually restarting after code install

### ISSUE THREAD

**Issue by ljhender** [Microsoft/react-native-code-push#590]
* react-native-code-push version: 1.15.0-beta
* react-native version: 0.35.0
* iOS/Android/Windows version: Android 4.3
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Device
* Repro steps and/or stack trace:

Using the old method of manually calling codepush sync. App downloads update and installs, however on restart it loops restarting until it has to be closed by holding down the home button and killing the app. I have implemented the part where you create an instance of ReactInstanceHolder, and use that in MainApplication.java. Haven't had an issue with this before, coming from 1.7.3-beta.
```
    public class MyReactNativeHost extends ReactNativeHost implements ReactInstanceHolder {
        MyReactNativeHost(Application application) {
            super(application);
        }
        @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }

        @Override
        protected boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            mInAppPurchase = new InAppPurchasePackage(MainApplication.this);
            return Arrays.<ReactPackage>asList(
                new MainReactPackage(),
                new FBSDKPackage(mCallbackManager),
                new CodePush("key", MainApplication.this, BuildConfig.DEBUG),
                new RNDeviceInfo(),
                new PushwooshPackage(),
                mInAppPurchase
            );
        }
    }
```

using manual sync

```
var codePush = require('react-native-code-push');
export default class AppView extends Component {
// other stuff
componentDidMount() {
        codePush.sync({ updateDialog: {appendReleaseDescription: true, descriptionPrefix: "\n\nUpdate Includes:\n"}, installMode: codePush.InstallMode.IMMEDIATE}, (status) => {
             switch (status) {
                 case codePush.SyncStatus.DOWNLOADING_PACKAGE:
                     // Show "downloading" modal
                     this.setState({downloadingUpdate: true});
                     break;
             }
         });
}
]
```
Here is the logcat of what is happening:
```
I/ReactNativeJS(13919): [CodePush] Installing update.
I/ReactNativeJS(13919): [CodePush] Restarting app
I/ReactNativeJS(13919): Running application "Football" with appParams: {"initialProps":{},"rootTag":11}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
I/ReactNativeJS(13919): 'state', { loginInfo: null, hasTeam: null, modalVisible: false }
I/ReactNativeJS(13919): Render method
I/ReactNativeJS(13919): Showing LoginView
I/ReactNativeJS(13919): [CodePush] Checking for update.
I/ReactNativeJS(13919): Running application "Football" with appParams: {"initialProps":{},"rootTag":21}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
I/ReactNativeJS(13919): 'state', { loginInfo: null, hasTeam: null, modalVisible: false }
I/ReactNativeJS(13919): Render method
I/ReactNativeJS(13919): Showing LoginView
I/ReactNativeJS(13919): [CodePush] Sync already in progress.
I/ReactNativeJS(13919): [CodePush] App is up to date.
I/ReactNativeJS(13919): Running application "Football" with appParams: {"initialProps":{},"rootTag":31}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
I/ReactNativeJS(13919): 'state', { loginInfo: null, hasTeam: null, modalVisible: false }
I/ReactNativeJS(13919): Render method
I/ReactNativeJS(13919): Showing LoginView
I/ReactNativeJS(13919): [CodePush] Checking for update.
I/ReactNativeJS(13919): Running application "Football" with appParams: {"initialProps":{},"rootTag":41}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
I/ReactNativeJS(13919): 'state', { loginInfo: null, hasTeam: null, modalVisible: false }
I/ReactNativeJS(13919): Render method
I/ReactNativeJS(13919): Showing LoginView
I/ReactNativeJS(13919): [CodePush] Sync already in progress.
I/ReactNativeJS(13919): [CodePush] App is up to date.
```

SO link: http://stackoverflow.com/questions/40409200/react-native-code-push-app-restart-loop

**Comment by ljhender** [comment]
Digging into this, it looks like CodePush thinks we are running an older version of RN even though we are on 35. 

Adding some logging into CodePushNativeModule, its throwing an exception trying to find a method createFileLoader, shown here 
```
E/CodePushTest(11058): exception figuring out which RN version.
E/CodePushTest(11058): java.lang.NoSuchMethodException: Could not find a recognized 'createFileLoader' method
E/CodePushTest(11058): 	at com.microsoft.codepush.react.CodePushNativeModule.setJSBundle(CodePushNativeModule.java:121)
E/CodePushTest(11058): 	at com.microsoft.codepush.react.CodePushNativeModule.loadBundle(CodePushNativeModule.java:164)
E/CodePushTest(11058): 	at com.microsoft.codepush.react.CodePushNativeModule.access$1100(CodePushNativeModule.java:37)
E/CodePushTest(11058): 	at com.microsoft.codepush.react.CodePushNativeModule$6$1.onHostResume(CodePushNativeModule.java:468)
```

Then since this is throwing an exception it thinks we are running a RN version < 31 shown here:
```
V/CodePushTest(11058): RN < v0.31
E/CodePushTest(11058): exception doing other stuff.
E/CodePushTest(11058): java.lang.NoSuchFieldException: mJSBundleFile
E/CodePushTest(11058): 	at java.lang.Class.getDeclaredField(Class.java:546)
E/CodePushTest(11058): 	at com.microsoft.codepush.react.CodePushNativeModule.setJSBundle(CodePushNativeModule.java:145)
E/CodePushTest(11058): 	at com.microsoft.codepush.react.CodePushNativeModule.loadBundle(CodePushNativeModule.java:164)
```

Looping continually trying to load the bundle the 'new' way, then falling back to the legacy way, which throws an exception since those methods don't exist since we are on RN 35. Will update as I figure out what is going on in case someone else runs into this issue.

**Comment by silhouettes** [comment]
Hi @ljhender, I believe I know the root cause - it should be fixed in master, and I'll publish a release with the fix today.

**Comment by ljhender** [comment]
@silhouettes Sounds great, appreciate the work you guys are doing. I'll update and try again when its released.

**Comment by silhouettes** [comment]
Hi @ljhender, `react-native-code-push@1.15.1-beta` has been published with a fix for this ([release notes](https://github.com/Microsoft/react-native-code-push/releases/tag/1.15.1-beta)). Please let me know if that resolves it for you!

**Comment by ljhender** [comment]
@silhouettes Thanks for the update, everything looking good from our end!

**Comment by cherniv** [comment]
Hey, can you please show your MainApplication.java file to help me show this: https://github.com/Microsoft/react-native-code-push/issues/872
