### ISSUE TITLE
Android crashes when restarting for applying the update

### ISSUE THREAD

**Issue by awesomejerry** [Microsoft/react-native-code-push#631]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

* react-native-code-push version: 1.14.6-beta / 1.16.1-beta
* react-native version: 0.32.0 / 0.36.1
* iOS/Android/Windows version: 5.0
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? emulator
* Repro steps and/or stack trace:
1. release an update through code-push
2. open app to download update in background
3. restart app to apply the update, which crash immediately
```
Process: com.example.app, PID: 29541
                                                                       java.lang.RuntimeException: SyntaxError: Invalid character '\u0005' (/data/data/com.example.app/files/CodePush/4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945/index.android.bundle:1)
                                                                           at com.facebook.react.cxxbridge.CatalystInstanceImpl.loadScriptFromFile(Native Method)
                                                                           at com.facebook.react.cxxbridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:39)
                                                                           at com.facebook.react.cxxbridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:177)
                                                                           at com.facebook.react.XReactInstanceManagerImpl$4.call(XReactInstanceManagerImpl.java:889)
                                                                           at com.facebook.react.XReactInstanceManagerImpl$4.call(XReactInstanceManagerImpl.java:882)
                                                                           at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:74)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                           at java.lang.Thread.run(Thread.java:818)
```
(The more info the faster we will be able to address it!)

**Comment by awesomejerry** [comment]
After upgrading RN to 0.39.0, React to 15.4.1 and RNCP to 1.16.1-beta. It's solved.
