### ISSUE TITLE
Android release builds crash on fetching bundle (RN 0.42)

### ISSUE THREAD

**Issue by lappalj4** [Microsoft/react-native-code-push#777]
### Description

After upgrading to react-native 0.42.3 and CodePush 1.17.2-beta, my app began crashing on startup. This is only happening on release builds, after running ```react-native run-android --variant=release```or ```cd android && ./gradlew assembleRelease```.

Interestingly enough, after installing the app on a device, the first time running it works fine. Only after closing the app once, and then trying to run it again does the crashing begin. 

I managed to deduce the problem was being caused by CodePush, since opening the app in airplane mode fixed the issue, as well as did commenting out the following lines in MainApplication.java:
```
        @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }
```

Debug builds of the app work like normal.

### Reproduction

All setup has been done exactly as in the documentation (manual, not rnpm).

I have not been able to reproduce this with the example project, and also I have been having trouble debugging this as it only happens on release builds - is there an easy way to see complete log output for release builds?

I have read through the suggestions in  #272, and at least the following did NOT solve it for me:

> Do an actual release build

> Modify the android\app\react.gradle file to enable generating the APK-bundled JS bundle file even in debug builds. Simply changing [this line](https://github.com/facebook/react-native/blob/a7cde8045ba10d67896cc5b203d397eaf4f395d6/react.gradle#L82) to enabled true would do the trick.

> ... cleared node_modules, killed watchman and node, cleared watchman with watchman watch-del-all, rm -rf ~/.npm and then from scratch re-installed code push (w/o using rnpm). I also removed the android/app/build folder and android/build folder (I only had removed app's build folder in the past, which may have been the actual issue)...

### Additional Information

* react-native-code-push version: 1.17.2-beta
* react-native version: 0.42.3
* iOS/Android/Windows version: Android 6.0.1 / API 23
* Does this reproduce on a debug build or release build? Release builds only
* Does this reproduce on a simulator, or only on a physical device? Both

Thanks for any help in advance! :)

EDIT: 
I ran logcat on the release build and here is the stacktrace. Not really sure what to make of it, is it even related to CodePush per se:

````
04-03 07:47:40.018  3369  3433 I ReactNativeJS: [CodePush] App is up to date.
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: Error while updating prop d
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `string', but had type `array'
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at com.facebook.react.bridge.ReadableNativeMap.getString(Native Method)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at com.facebook.react.uimanager.ReactStylesDiffMap.getString(ReactStylesDiffMap.java:73)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$StringPropSetter.extractProperty(ViewManagersPropertyCache.java:241)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:99)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:148)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:52)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at com.facebook.react.uimanager.ReactShadowNode.updateProperties(ReactShadowNode.java:264)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:184)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:245)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:136)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at android.os.Handler.handleCallback(Handler.java:739)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at android.os.Looper.loop(Looper.java:148)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
04-03 07:47:40.041  3369  3434 E unknown:ViewManager: 	at java.lang.Thread.run(Thread.java:818)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
04-03 07:47:40.063  3369  3434 E AndroidRuntime: Process: ch.enluf.laaxexplore, PID: 3369
04-03 07:47:40.063  3369  3434 E AndroidRuntime: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'd' in shadow node of type: RNSVGPath
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:111)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:148)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:52)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at com.facebook.react.uimanager.ReactShadowNode.updateProperties(ReactShadowNode.java:264)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:184)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:245)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:136)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: Caused by: com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `string', but had type `array'
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getString(Native Method)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at com.facebook.react.uimanager.ReactStylesDiffMap.getString(ReactStylesDiffMap.java:73)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$StringPropSetter.extractProperty(ViewManagersPropertyCache.java:241)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:99)
04-03 07:47:40.063  3369  3434 E AndroidRuntime: 	... 15 more
```

**Comment by lappalj4** [comment]
Ok, it seems like the issue in this case is _what_ is being codepushed, not in CodePush itself. Thanks again, and sorry for the troubles.
