### ISSUE TITLE
[Android] Error while trying to release-react

### ISSUE THREAD

**Issue by maggialejandro** [Microsoft/react-native-code-push#886]
### Description
I'm trying to release a React Native Android app with the following command:

```bash
MacBook-Air:react-native-demo$ code-push release-react Appname-Android Android
Detecting android app version:

/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:28
		to[key] = val;
		        ^

TypeError: Cannot assign to read only property '0' of object '[object String]'
    at assignKey (/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:28:11)
    at assign (/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:43:4)
    at assignKey (/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:30:13)
    at assign (/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:43:4)
    at deepAssign (/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:64:3)
    at deepParse (/usr/local/lib/node_modules/code-push-cli/node_modules/gradle-to-js/lib/parser.js:135:27)
    at deepParse (/usr/local/lib/node_modules/code-push-cli/node_modules/gradle-to-js/lib/parser.js:137:27)
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/code-push-cli/node_modules/gradle-to-js/lib/parser.js:392:13)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at ReadStream.Readable.push (_stream_readable.js:136:10)
    at onread (fs.js:1938:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:629:17)
```

### Reproduction
My /app/build.gradle file looks like this:

```gradle
apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
apply from: "../../node_modules/react-native-sentry/sentry.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.1'

    defaultConfig {
        applicationId "com.my.app"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        debug {
            if (project.hasProperty('MYAPP_DEBUG_STORE_FILE')) {
                storeFile file(MYAPP_DEBUG_STORE_FILE)
                storePassword MYAPP_DEBUG_STORE_PASSWORD
                keyAlias MYAPP_DEBUG_KEY_ALIAS
                keyPassword MYAPP_DEBUG_KEY_PASSWORD
            }
        }

        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        debug {
            buildConfigField "String", "CODEPUSH_KEY", '""'
            signingConfig signingConfigs.debug
        }

        releaseStaging {
            buildConfigField "String", "CODEPUSH_KEY", '"y2jzwfrXgmT8lwhKUnTLMbMuH3L-236f2208-56d8-4f25-9a56-bf137e5207e2"'
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }

        release {
            buildConfigField "String", "CODEPUSH_KEY", '"zGyzpgDsrN8xXgxhWeEninpMyGu-236f2208-56d8-4f25-9a56-bf137e5207e2"'
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-code-push')
    compile project(':react-native-spinkit')
    compile project(':react-native-sentry')
    compile project(':react-native-splash-screen')
    compile project(':react-native-facebook-login')
    compile (project(':react-native-fcm')){
        exclude group: "com.google.firebase"
    }
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
    compile(project(":react-native-google-signin")){
        exclude group: "com.google.android.gms"
    }
    compile ('com.google.firebase:firebase-core:10.0.1') {
        force = true;
    }
    compile ('com.google.firebase:firebase-messaging:10.0.1') {
        force = true;
    }
    compile ('com.google.android.gms:play-services-auth:10.0.1') {
        force = true;
    }
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:10.0.1'
    compile ('com.google.android.gms:play-services-maps:10.0.1') {
        force = true;
    }
}

task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
```

If I comment one of these dependencies the command works
```bash
compile(project(":react-native-google-signin")){
    exclude group: "com.google.android.gms"
}

// OR

compile(project(':react-native-maps')){
    exclude group: 'com.google.android.gms', module: 'play-services-base'
    exclude group: 'com.google.android.gms', module: 'play-services-maps'
}
```

any ideas?
Thanks in advance!

### Additional Information
* react-native-code-push version: 2.1.0-beta
* react-native version: 0.45.1

**Comment by sergey-akhalkov** [comment]
Hi @maggialejandro, thanks for reaching us and for filling out the issue. The issue is in `gradle-to-js` plugin that we are using to parse `build.gradle` file. To fix it you should add spaces ` ` between `compile` and `(project` like this: `compile (project(":react-native-google-signin")){` and `compile (project(':react-native-maps')){`

Please let me know if it works.

**Comment by maggialejandro** [comment]
Hi @sergey-akhalkov , I just did that but I get the same error..

**Comment by sergey-akhalkov** [comment]
Hi @maggialejandro, got it, I've created new issue https://github.com/ninetwozero/gradle-to-js/issues/8
As of now you can use `targetBinaryVersion` parameter to workaround this issue.

**Comment by jaseemabbas** [comment]
@sergey-akhalkov That was magic!
