### ISSUE TITLE
[Android] CodePush crashes on start due to malformed file

### ISSUE THREAD

**Issue by dhruvp** [Microsoft/react-native-code-push#907]
### Description

I've set up a multi stage react native deployment and upon deploying either version of my app, on the first download of the js bundle the app immediately crashes. It crashes with the following exception:
```bash
06-27 19:05:07.827 10281-10281/com.athelas E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.athelas, PID: 10281
                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.athelas/com.athelas.MainActivity}: com.microsoft.codepush.react.CodePushMalformedDataException: Unable to parse contents of /data/user/0/com.athelas/files/CodePush/75f331d41f23bc33dd64d74e58ca021db6d10fd47bcc4656f060a7f6bd30dfd0/app.json, the file may be corrupted.
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                 at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6540)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
```
I deployed the application via `code-push release-react <App-name> android`.

### Reproduction

My setup:
react-native-code-push: 2.1.0-beta
react-native: 0.45.1

### Additional Information

* react-native-code-push version: 2.1.0-beta
* react-native version: 0.45.1
* iOS/Android/Windows version: crashes on all builds
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? both

Thank you!

**Comment by dhruvp** [comment]
As a heads up this same app works fine with codepush in iOS. It seems something specific to how I'm configuring it or using it with Android.

Thank you again!

**Comment by dhruvp** [comment]
Closing this - turns out I just had to resync my gradle build and it then somehow worked :)
