### ISSUE TITLE
[Android] After code-push release-react, device will Crash.

### ISSUE THREAD

**Issue by Jakevin** [Microsoft/react-native-code-push#912]
### Description

Android get Release update, same time will crash.

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
                   at android.os.AsyncTask$3.done(AsyncTask.java:325)
                   at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                   at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                   at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                   at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.NullPointerException
                  at java.io.File.<init>(File.java:262)
                  at com.microsoft.codepush.react.FileUtils.copyDirectoryContents(FileUtils.java:19)
                  at com.microsoft.codepush.react.CodePushUpdateUtils.copyNecessaryFilesFromCurrentPackage(CodePushUpdateUtils.java:71)
                  at com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage(CodePushUpdateManager.java:226)
                  at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:230)
                  at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:224)
```

### Reproduction

Use command: same times will crash
```
code-push release-react app_android android --dev false --d Production -m true
```
And use code-push bundle, then code-push release, 100% work. but Image file will lose.

```
react-native bundle --platform android --entry-file index.android.js --bundle-output ./bundles/main.jsbundle --assets-dest ./bundles --dev false

code-push release app_android ./bundles/main.jsbundle  4.0.1  --deploymentName Production --mandatory true
```

### Additional Information

* react-native-code-push version: 3.0.0-beta
* react-native version:0.45.1
* iOS/Android/Windows version: Android 7.0
* Does this reproduce on a debug build or release build?
release
* Does this reproduce on a simulator, or only on a physical device? 
physical device（HTC10 and xiaomi 5）

(The more info the faster we will be able to address it!)

**Comment by sergey-akhalkov** [comment]
Hi @Jakevin, thanks for reaching us, the issue has been fixed in [v3.0.1](https://github.com/Microsoft/react-native-code-push/releases/tag/v3.0.1-beta), please upgrade and let me know if you see any issues.

So I'm closing this for now, please feel free to reopen if needed.
