### ISSUE TITLE
[Android] Rollback + Binary update causes app to crash

### ISSUE THREAD

**Issue by AndrewJack** [Microsoft/react-native-code-push#921]
### Description

`initializeUpdateAfterRestart` is called (in the constructor of `CodePush`)  before `getJSBundleFileInternal` & `clearUpdates`. This can be confirmed by running the example app.

This causes the app to get into a unexpected state and crash when rolling back because the expected `codepush.json` status file has been deleted.

If a binary update has occurred the `CodePush/` directory and settings are cleared. If the app has a  pending update which has to be rolled back the app will crash because the necessary file have been deleted.

I will post a few stack traces captured by crashlytics, which are side effects of this core issue.

~The use of headlessTask may be part of this issue.~ HeadlessTask only caused the rollbacks due to the absense of `notifyAppReady`

### Reproduction

1. Run the example app with `InstallMode.ON_NEXT_RESTART`
2. Push a code push update that causes a rollback or don't call `codePush.notifyAppReady()` or `sync`
3. Let the code push install
4. Quit the app and remove from memory
5. Open app
6. Quit the app and remove from memory
7. Install a new binary version 
8. Run the app

**Actual**:
Observe crash
**Expected**:
Should load binary version without crashing

### Additional Information

* react-native-code-push version: 2.1.0
* react-native version: 0.44.2
* iOS/Android/Windows version: Android (any)
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? either

**Comment by AndrewJack** [comment]
```
Fatal Exception: java.lang.RuntimeException: Unable to start service com.example.react.headlessTask.CodePushTaskService@ef12e5f with Intent { cmp=com.example/.react.headlessTask.CodePushTaskService }: com.microsoft.codepush.react.g: Error updating current package info
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3314)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by com.microsoft.codepush.react.g: Error updating current package info
       at com.microsoft.codepush.react.CodePushUpdateManager.updateCurrentPackageInfo(CodePushUpdateManager.java:67)
       at com.microsoft.codepush.react.CodePushUpdateManager.rollbackPackage(CodePushUpdateManager.java:295)
       at com.microsoft.codepush.react.CodePush.rollbackPackage(CodePush.java:246)
       at com.microsoft.codepush.react.CodePush.initializeUpdateAfterRestart(CodePush.java:205)
       at com.microsoft.codepush.react.CodePush.(CodePush.java)
       at com.example.MainReactNativeHost.getPackages(MainReactNativeHost.java:63)
       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:74)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
       at com.facebook.react.HeadlessJsTaskService.startTask(HeadlessJsTaskService.java:100)
       at com.facebook.react.HeadlessJsTaskService.onStartCommand(HeadlessJsTaskService.java:53)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3297)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by java.io.FileNotFoundException: /data/user/0/com.example/files/CodePush/codepush.json (No such file or directory)
       at java.io.FileOutputStream.open(FileOutputStream.java)
       at java.io.FileOutputStream.(FileOutputStream.java)
       at java.io.FileOutputStream.(FileOutputStream.java)
       at java.io.PrintWriter.(PrintWriter.java)
       at com.microsoft.codepush.react.FileUtils.writeStringToFile(FileUtils.java:184)
       at com.microsoft.codepush.react.CodePushUtils.writeJsonToFile(CodePushUtils.java:228)
       at com.microsoft.codepush.react.CodePushUpdateManager.updateCurrentPackageInfo(CodePushUpdateManager.java:64)
       at com.microsoft.codepush.react.CodePushUpdateManager.rollbackPackage(CodePushUpdateManager.java:295)
       at com.microsoft.codepush.react.CodePush.rollbackPackage(CodePush.java:246)
       at com.microsoft.codepush.react.CodePush.initializeUpdateAfterRestart(CodePush.java:205)
       at com.microsoft.codepush.react.CodePush.(CodePush.java)
       at com.example.MainReactNativeHost.getPackages(MainReactNativeHost.java:63)
       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:74)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
       at com.facebook.react.HeadlessJsTaskService.startTask(HeadlessJsTaskService.java:100)
       at com.facebook.react.HeadlessJsTaskService.onStartCommand(HeadlessJsTaskService.java:53)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3297)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by AndrewJack** [comment]
```
Fatal Exception: com.microsoft.codepush.react.g: Unable to read failedUpdates data stored in SharedPreferences.
       at com.microsoft.codepush.react.SettingsManager.isFailedHash(SettingsManager.java:62)
       at com.microsoft.codepush.react.CodePushNativeModule.isFailedUpdate(CodePushNativeModule.java:486)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
       at java.lang.Thread.run(Thread.java:818)
Caused by org.json.JSONException: Value null at 2 of type org.json.JSONObject$1 cannot be converted to JSONObject
       at org.json.JSON.typeMismatch(JSON.java:100)
       at org.json.JSONArray.getJSONObject(JSONArray.java:525)
       at com.microsoft.codepush.react.SettingsManager.isFailedHash(SettingsManager.java:56)
       at com.microsoft.codepush.react.CodePushNativeModule.isFailedUpdate(CodePushNativeModule.java:486)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by AndrewJack** [comment]
```
Fatal Exception: java.lang.RuntimeException: Unable to start service com.example.react.headlessTask.CodePushTaskService@426b0e30 with Intent { cmp=com.example/.react.headlessTask.CodePushTaskService }: com.microsoft.codepush.react.d: Unable to parse contents of /data/data/com.example/files/CodePush/codepush.json, the file may be corrupted.
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3007)
       at android.app.ActivityThread.access$2200(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by com.microsoft.codepush.react.d: Unable to parse contents of /data/data/com.example/files/CodePush/codepush.json, the file may be corrupted.
       at com.microsoft.codepush.react.CodePushUtils.getJsonObjectFromFile(CodePushUtils.java:198)
       at com.microsoft.codepush.react.CodePushUpdateManager.getCurrentPackageInfo(CodePushUpdateManager.java:55)
       at com.microsoft.codepush.react.CodePushUpdateManager.getCurrentPackageHash(CodePushUpdateManager.java:105)
       at com.microsoft.codepush.react.CodePushUpdateManager.getCurrentPackage(CodePushUpdateManager.java:115)
       at com.microsoft.codepush.react.CodePush.rollbackPackage(CodePush.java:244)
       at com.microsoft.codepush.react.CodePush.initializeUpdateAfterRestart(CodePush.java:205)
       at com.microsoft.codepush.react.CodePush.(CodePush.java:72)
       at com.example.MainReactNativeHost.getPackages(MainReactNativeHost.java:63)
       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:74)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
       at com.facebook.react.HeadlessJsTaskService.startTask(HeadlessJsTaskService.java:100)
       at com.facebook.react.HeadlessJsTaskService.onStartCommand(HeadlessJsTaskService.java:53)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2990)
       at android.app.ActivityThread.access$2200(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by org.json.JSONException: End of input at character 0 of 
       at org.json.JSONTokener.syntaxError(JSONTokener.java:450)
       at org.json.JSONTokener.nextValue(JSONTokener.java:97)
       at org.json.JSONObject.(JSONObject.java:155)
       at org.json.JSONObject.(JSONObject.java:172)
       at com.microsoft.codepush.react.CodePushUtils.getJsonObjectFromFile(CodePushUtils.java:195)
       at com.microsoft.codepush.react.CodePushUpdateManager.getCurrentPackageInfo(CodePushUpdateManager.java:55)
       at com.microsoft.codepush.react.CodePushUpdateManager.getCurrentPackageHash(CodePushUpdateManager.java:105)
       at com.microsoft.codepush.react.CodePushUpdateManager.getCurrentPackage(CodePushUpdateManager.java:115)
       at com.microsoft.codepush.react.CodePush.rollbackPackage(CodePush.java:244)
       at com.microsoft.codepush.react.CodePush.initializeUpdateAfterRestart(CodePush.java:205)
       at com.microsoft.codepush.react.CodePush.(CodePush.java:72)
       at com.example.MainReactNativeHost.getPackages(MainReactNativeHost.java:63)
       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:74)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
       at com.facebook.react.HeadlessJsTaskService.startTask(HeadlessJsTaskService.java:100)
       at com.facebook.react.HeadlessJsTaskService.onStartCommand(HeadlessJsTaskService.java:53)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2990)
       at android.app.ActivityThread.access$2200(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by AndrewJack** [comment]
Edit: Added reproduction steps
